### ISSUE TITLE
Unable to run __iar_program_start

### ISSUE THREAD

**Issue by Gigaclank** [Marus/cortex-debug#100]
Not sure if an issue or more lack of understanding,

![image](https://user-images.githubusercontent.com/12459794/47345450-ae2c8780-d6a2-11e8-8b5e-167e65f22248.png)

Configuration as follows:
![image](https://user-images.githubusercontent.com/12459794/47345536-e5029d80-d6a2-11e8-9fd8-ce65c84b0e07.png)

and User settings:
![image](https://user-images.githubusercontent.com/12459794/47345562-f350b980-d6a2-11e8-8dad-c8e01a8b11cb.png)

Unable to go to __iar_program_start therefore breakpoints not working.

**Comment by 0ge** [comment]
I was slowly writing a bug report (#101) while you posted this. Does the workaround work for you? (Open Debug Console and hit Enter)

**Comment by Gigaclank** [comment]
> I was slowly writing a bug report (#101) while you posted this. Does the workaround work for you? (Open Debug Console and hit Enter)

Yes this works! How strange!

**Comment by Gigaclank** [comment]
closing issue needed to add "runToMain": true,
close #100
