### ISSUE TITLE
Take ipAddress from environment variable

### ISSUE THREAD

**Issue by ligantx** [Marus/cortex-debug#1016]
I would like to do remote debugging using the `ipAddress` attribute. The IP should be dynamically changed according to the IP address of the developer doing the debugging.

This is working fine:
`"ipAddress": "192.168.1.5"`

but this doesn't:
`"ipAddress": "${env:myIp}"`

And i take this warning: `'env.', 'config.' and 'command.' are deprecated, use 'env:', 'config:' and 'command:' instead.`, although environment variables [are supported](https://code.visualstudio.com/docs/editor/variables-reference#_environment-variables) by VS Code (it is assumed that there is a script or something setting `myIp` to the developer's ip address). Is there any way to implement this?

**Comment by haneefdm** [comment]
Please use our bug submission template. Not enough detail here.

VSCode handles the "${env...". Not us, btw.
