### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by Arman92** [Marus/cortex-debug#102]
When I try to start the debug, VS code shows this error: 
Cannot convert undefined or null to object

My launch.json configs:
```
// {
//     // Use IntelliSense to learn about possible attributes.
//     // Hover to view descriptions of existing attributes.
//     // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
{
  "version": "0.2.0",
  "configurations": [{
      "cwd": "${workspaceRoot}",
      "executable": "./build/RigController.elf",
      "name": "Debug Microcontroller",
      "request": "launch",
      "type": "cortex-debug",
      "servertype": "jlink",
      "device": "STM32F103RE",
      "interface": "jtag",
    },
    {
      "type": "cortex-debug",
      "request": "launch",
      "servertype": "openocd",
      "cwd": "${workspaceRoot}",
      "executable": "./build/RigController.elf",
      "name": "Debug (OpenOCD)",
      "device": "STM32F103RB",
      "configFiles": [
        "target/stm32f1x.cfg"
      ]
    }
  ]
}
```

And there is no output in "Debug Console" window.
VS code version: 1.28.1

**Comment by Gigaclank** [comment]
have you added your path for openocd and for armToolchainPath?
e.g.
```json
{
"cortex-debug.JLinkGDBServerPath": "C:\\Program Files (x86)\\SEGGER\\JLink_V634g\\JLinkGDBServerCL.exe",
"cortex-debug.armToolchainPath": "C:\\Program Files (x86)\\GNU Tools Arm Embedded\\7 2018-q2-update\\bin\\",
"cortex-debug.stutilPath": "C:\\Program Files (x86)\\STMicroelectronics\\stlink-1.3.0-win64\\bin\\st-util.exe"
}
  ```

does  your executable exist?

**Comment by Arman92** [comment]
JLinkGDBServer and openocd were already in my PATH, however I added them in vs code settings manually:
```
{
    "cortex-debug.JLinkGDBServerPath": "/usr/bin/JLinkGDBServer",
    "cortex-debug.armToolchainPath": "/home/arman/opt/gcc-arm-none-eabi-7-2017-q4-major/bin/",
    "cortex-debug.openocdPath": "/usr/local/bin/openocd"
}
```

I'm not getting the previous error anymore, but here is a new one:
![image](https://user-images.githubusercontent.com/3900575/47496144-d6fb7b00-d862-11e8-8fae-989b0fe0e074.png)

**Comment by Gigaclank** [comment]
> JLinkGDBServer and openocd were already in my PATH, however I added them in vs code settings manually:
> 
> ```
> {
>     "cortex-debug.JLinkGDBServerPath": "/usr/bin/JLinkGDBServer",
>     "cortex-debug.armToolchainPath": "/home/arman/opt/gcc-arm-none-eabi-7-2017-q4-major/bin/",
>     "cortex-debug.openocdPath": "/usr/local/bin/openocd"
> }
> ```
> I'm not getting the previous error anymore, but here is a new one:
> ![image](https://user-images.githubusercontent.com/3900575/47496144-d6fb7b00-d862-11e8-8fae-989b0fe0e074.png)

I had this issue also. might be a stupid question is your device attached to your debugger?

**Comment by Arman92** [comment]
> > JLinkGDBServer and openocd were already in my PATH, however I added them in vs code settings manually:
> > ```
> > {
> >     "cortex-debug.JLinkGDBServerPath": "/usr/bin/JLinkGDBServer",
> >     "cortex-debug.armToolchainPath": "/home/arman/opt/gcc-arm-none-eabi-7-2017-q4-major/bin/",
> >     "cortex-debug.openocdPath": "/usr/local/bin/openocd"
> > }
> > ```
> > I'm not getting the previous error anymore, but here is a new one:
> > ![image](https://user-images.githubusercontent.com/3900575/47496144-d6fb7b00-d862-11e8-8fae-989b0fe0e074.png)
> 
> I had this issue also. might be a stupid question is your device attached to your debugger?

Of course!
I can even debug my target with OpenOCD, using Jlink or ST-Link. (using my own debug setup)

**Comment by 0ge** [comment]
I get this error when a) I have forgot to connect my debugger or 2) there is another processing using the debugger (viewing SWO, separate debug session, etc).

**Comment by aguirrem** [comment]
@Arman92 did you ever get to the bottom of this?

**Comment by nickray** [comment]
This issue is helpful: https://github.com/Marus/cortex-debug/issues/27
