### ISSUE TITLE
Default value of "Live Watch Refresh Rate" should be a number

### ISSUE THREAD

**Issue by xy-23** [Marus/cortex-debug#1020]
Hi, the default value has been set as a string: 
https://github.com/Marus/cortex-debug/blob/cfff611cc3578386c7ea83eebe6627bc2c013cef/package.json#L23
which probably should be modified to: 
```
"default": 300, 
```

**Comment by haneefdm** [comment]
Fixed in the next release. Thanks for letting us know.
