### ISSUE TITLE
Missing variables in the Variables View

### ISSUE THREAD

**Issue by AndriiLishchynskyi** [Marus/cortex-debug#1023]
**Summary**

GDB provides the ability to use debug symbols from multiple files. That can be achieved, for example, by using _add-symbol-file_ GDB command.
I noticed that _Variables_ VSCode menu does not list some global variables when debug symbols were loaded using _add-symbol-file_ command.

**Details**

I have a TrustZone project divided into two subprojects: proj_secure, proj_non_secure. Non-secure part (proj_non_secure) defines a global variable. To have access to debug symbols of both subprojects I launch debug session by specifying symbol file of proj_secure subproject via _file_ GDB command and symbol files of proj_non_secure subproject via _add-symbol-file_ command.
Once debug session I can observe a problem that _Global_ dropdown under _Variables_ view does not list global variable defines in proj_non_secure while it can be accessed via _Watch_ view:
<img src="https://github.com/Marus/cortex-debug/assets/48319111/fb569f01-6b20-45ba-88f9-be07f675d0f7" width="280">

Once symbol file of proj_non_secure is fed via _file_ command I am able to see global variable in the list:
 <img src="https://github.com/Marus/cortex-debug/assets/48319111/184dbca4-1e74-48b2-b0ef-17843cb2f8c7" width="280">

What can be the reason of such behavior? Can it be somehow fixed?

**Comment by PhilippHaefele** [comment]
As this extension does not (only) use GDB directly to get variables. It also uses objdump and nm for this.

So most likely you only need to use the `symbolFiles` (and `loadFiles` if you like to load both of them on debug start) in `launch.json` instead of the `add-symbol-file` GDB command.
