### ISSUE TITLE
Peripherals/XPeripherals view not showing

### ISSUE THREAD

**Issue by al-martyn1** [Marus/cortex-debug#1045]
Initially the view was displayed. Some time ago it disappeared and there is no way to find it to enable display.

I don't know how to reproduce it. My colleague has the same version of VSCode and Cortex-Debug plugin, and everything is displayed for him.

 - Cortex-Debug Version (this extension) - 1.12.1 (autoupdate enabled)
 - OS: Windows 10
 - GDB Version: GNU gdb (Arm GNU Toolchain 13.2.rel1 (Build arm-13.7)) 13.2.90.20231008-git
 - Compiler Toolchain Version: arm-none-eabi-g++.exe (Arm GNU Toolchain 13.2.rel1 (Build arm-13.7)) 13.2.1 20231009

**`launch.json`**
```
{
  "configurations" : 
  [
    {
      "name": "Host App Debug",
      "type": "cppdbg",
      "request": "launch",
      "program": "${command:cmake.launchTargetPath}",
      "cwd": "${workspaceFolder}",
      "args": [],
      "stopAtEntry": false,
      "environment": [],
      "externalConsole": false,
      "MIMode": "gdb",
      "miDebuggerPath": "gdb",
      "preLaunchTask": "FW: build",
      "presentation" : {
          "group": "win32"
      }
    },
    {
      "name" : "Cortex Debug (Flash-n-Launch)",
      "type" : "cortex-debug",
      "device" : "STM32F429II",
      "svdFile" : "${workspaceRoot}/src/scripts/STM32F429.svd",
      "svdPath" : "${workspaceRoot}/src/scripts/STM32F429.svd",
      "servertype" : "openocd",
      "configFiles": [ "interface/stlink.cfg", "target/stm32f4x.cfg" ],
      "openOCDPreConfigLaunchCommands": ["adapter speed 1800"],
      "openOCDLaunchCommands": [
        "adapter speed 1800"
      ],
      "cwd" : "${workspaceFolder}",
      "executable" : "${command:cmake.launchTargetPath}",
      "request" : "launch",
      "runToEntryPoint" : "main",
      "showDevDebugOutput" : "raw",
      "preLaunchTask" : "FW: build",
      "preLaunchCommands": [
          "set remote hardware-breakpoint-limit 6",
          "set remote hardware-watchpoint-limit 4",
          "enable breakpoint",
          "monitor halt",
          "monitor reset init",
          "load",
          "monitor halt",
          "monitor reset init"
      ],
      "preRestartCommands" : [
          "set remote hardware-breakpoint-limit 6",
          "set remote hardware-watchpoint-limit 4",
          "enable breakpoint",
          "monitor halt",
          "monitor reset init"
      ],
      "presentation" : {
          "group": "stm32"
      }
    },
    {
      "name" : "Cortex Debug (Launch)",
      "type" : "cortex-debug",
      "device" : "STM32F429II",
      "svdFile" : "${workspaceRoot}/src/scripts/STM32F429.svd",
      "servertype" : "openocd",
      "configFiles": [ "interface/stlink.cfg", "target/stm32f4x.cfg" ],
      "openOCDPreConfigLaunchCommands": ["adapter speed 1800"],
      "openOCDLaunchCommands": [
        "adapter speed 1800"
      ],
      "cwd" : "${workspaceFolder}",
      "executable" : "${command:cmake.launchTargetPath}",
      "request" : "launch",
      "runToEntryPoint" : "main",
      "showDevDebugOutput" : "raw",
      "preLaunchCommands": [
          "set remote hardware-breakpoint-limit 6",
          "set remote hardware-watchpoint-limit 4",
          "enable breakpoint",
          "monitor reset"
      ],
      "preRestartCommands": [
          "enable breakpoint",
          "monitor reset init"
      ],
      "presentation" : {
          "group": "stm32"
      }
    },
    {
      "name" : "Cortex Debug (Attach, Non-complete)",
      "type" : "cortex-debug",
      "device" : "STM32F429II",
      "svdFile" : "${workspaceRoot}/src/scripts/STM32F429.svd",
      "servertype" : "openocd",
      "configFiles": [ "interface/stlink.cfg", "target/stm32f4x.cfg" ],
      "cwd" : "${workspaceFolder}",
      "executable" : "${command:cmake.launchTargetPath}",
      "request" : "attach",
      "showDevDebugOutput" : "raw",
      "presentation" : {
          "group": "stm32"
      }
    }
  ],
  "version" : "0.2.0"
}
```
[debug_console.txt](https://github.com/user-attachments/files/17046533/debug_console.txt)

**Comment by haneefdm** [comment]
Two things,

The Peripherals window is actually a separate extension. I am assuming that all required extensions have been installed (automatically done if you install with VSCode). If you are getting errors/warnings when you first run the debugger in VSCode (or during VSCode startup), then you have an install problem. Try uninstalling and re-installing..

Are you sure you did not hide the window? In VSCode Panels, you can show/hide many views. Make sure you see the **XPeripherals** . Use the `...` on the right edge of the panel to get a menu of if views

<img width="374" alt="image" src="https://github.com/user-attachments/assets/1f302d93-23b0-45a0-809f-53af4970f744">

<img width="586" alt="image" src="https://github.com/user-attachments/assets/669bb8f7-efbe-42d3-86ef-079083d5e2eb">

**Comment by al-martyn1** [comment]
LiveWatch displayed, but no Peripherals View- ![OnlyLiveWatch](https://github.com/user-attachments/assets/6650858b-f06b-4028-8f17-dfc1d1ef90f6)

No Peripherals View in menu - ![NoPeripheralsViewInMenu](https://github.com/user-attachments/assets/3a73b155-c606-4765-9d1d-92427ae6d735)

I dont undestand which '...' is on second screen - I have no such - 
![Image](https://github.com/user-attachments/assets/79f3e250-3432-436b-ab65-31acc92f8d41)

**Comment by haneefdm** [comment]
The three dots always exist at the top right of the debug section (right above the Variables panel)

How did you install cortexc-debug? If you did it on the command line, then VSCode does not auto install dependencies. Make sure all of these are installed

<img width="770" alt="image" src="https://github.com/user-attachments/assets/d6c5b2e1-5603-4d82-a3b6-b86140065768">

**Comment by haneefdm** [comment]
I want to make sure that the peripheral viewer is actualy running and doing something. Can you send the log of this window? It is is the OUTPUT tab and use the dropdown to select messages from the peripheral viewer

<img width="1061" alt="image" src="https://github.com/user-attachments/assets/77f6e4ea-4fa6-45b0-85c2-29963a201744">

**Comment by al-martyn1** [comment]
> The three dots always exist at the top right of the debug section (right above the Variables panel)

Ok. There is no "Peripherals" item in the "three dots" menu


> How did you install cortexc-debug? If you did it on the command line, then VSCode does not auto install dependencies. Make sure all of these are installed

I installed Cortex-debug via VSCode Extensions (Ctrl+Shift+X). At that time it was a single plugin. Currently it was splitted into five different plugins, and all of them are installed - 
![InstalledPlugins](https://github.com/user-attachments/assets/a888b69c-2ff4-49fd-aae9-f12cf2a37056)

There is no "Peripherals" item in Output dropdown menu: 
![OutputDropdown](https://github.com/user-attachments/assets/747ecec0-c808-4452-bc84-279d9eab2366)


[output.txt](https://github.com/user-attachments/files/17057075/output.txt)

**Comment by al-martyn1** [comment]
It seems I was send wrong log.
Also, I try to find "Peripherals" in the wrong menu. I find another dropdown at right? but there is not "Peripherals" in it too: 
![dropdown](https://github.com/user-attachments/assets/92383b80-e0ff-4b3f-a437-7d2a2ecb12c6)

**Comment by haneefdm** [comment]
To see debug otput in the OUTPUT tab, you have to enable debug-level for both User/Workspace

<img width="878" alt="image" src="https://github.com/user-attachments/assets/4d977597-2d12-4504-9d05-0d95ab5f5ecf">

**Comment by haneefdm** [comment]
Above screenshot is in the VSCode Settings Editor. Search for "Peripheral"

**Comment by haneefdm** [comment]
One simple thing to do is to remove all cortex-debug and mcu-debug extensions and install cortex debug from scratch. It appears that the Peripheral Viewer is not even starting. It will not harm any of your projects but be safe.

**Comment by al-martyn1** [comment]
Right peripherals log - [output.txt](https://github.com/user-attachments/files/17058374/output.txt)

I try to uninstall "debug-tracker-vscode", "MemoryView", "Peripheral Viewer", "RTOS Views" and then "Cortex-Debug".
Then I close VSCode and start it again.
Then, I install "Cortex-Debug" - dependencies are installed automatically.
Then, I close VSCode and start it again.
When I try to start debugging, I see the same picture - there is no "Peripherals" view at all, only "Cortex Live Watch"

**Comment by haneefdm** [comment]
I notice the following.
```
      "svdFile" : "${workspaceRoot}/src/scripts/STM32F429.svd",
      "svdPath" : "${workspaceRoot}/src/scripts/STM32F429.svd",
```
Can you comment out the "svdPath" line, restart VSCode and try to see if starts working, svdPath is used by some other extension and may cause issues

Also, make sure that there are no other extensions handling SVD files like the MS Embedded tools, etc. and if so, temporarily disable them.

**Comment by al-martyn1** [comment]
```
"svdPath" : "${workspaceRoot}/src/scripts/STM32F429.svd",
```
I added this yesterday hoping it would show me the "Peripheral" view )

Your right about side bar - I found "Peripherals" in the "Secondary Side Bar". Thanks a lot! I don't know how it happened and I would never have guessed.

My startup sequece is very complicated cause I configure I before I start using Cortex-Debug plugin. Thanks for the advice, I'll check my launch.json.

**Comment by al-martyn1** [comment]
You should probably add this to the FAQ )

**Comment by talpachen** [comment]
> I may have found your problem....
> 
> https://stackoverflow.com/questions/63327052/the-watch-panel-disappear-when-i-debug-my-code-in-vs-code
> 
> Your missing window is probabkly sitting n the sidebar because you accidentallly did it. You need to drag it back into the Debug Window. It is easy to drag things around to new places and not so easy to undo that.
> 
> I just tried that with the CallStack panel and at first I couldn't tell what had happened. This is a VSCode thing and has nothing to do with us.

Thank you. It works.
