### ISSUE TITLE
The project folder has a Chinese path

### ISSUE THREAD

**Issue by xiaotaomcu** [Marus/cortex-debug#1059]
The project folder has a Chinese path, and Cortex Debug cannot start. Can you fix this problem? Thank you very much

**Comment by haneefdm** [comment]
not enough info, no logs attached.

fyi, we don't deal with pathnames very much directly. https://github.com/microsoft/vscode-cpptools/issues/1998

Just google and you will see that most command line tools don't handle Unicode
