### ISSUE TITLE
STM32F042F6P6 Cant program or debug

### ISSUE THREAD

**Issue by D4NNYH** [Marus/cortex-debug#1064]
**Describe the bug**
Upon starting debug session everything appears to be working however program has not uploaded and is not running, deugger appears to allow pausing the and resuming code but actually is not doing anything.
Uploading the same .elf file using stm32cubeprogrammer (gui version) works and code runs.

**Expected behavior**

Program uploads, debug session begins

**Screenshots**

[comment]: <> If applicable, add screenshots to help explain your problem.

**Environment (please complete the following information):**

[comment]: <> Whenever possible, please make sure you are using the latest versions of VSCode and our extension

 - Cortex-Debug Version (this extension): v1.12.1
 - OS: Windows 11
 - GDB Version: 7.9.0
 - Compiler Toolchain Version: not sure (whatever comes with stm32cubeCLT 1.17.0)

**Please include `launch.json`**

*Note: We are unlikely to look at the issue if you do not supply this*
```
Paste launch.json contents here
```

**Attach text from `Debug Console`**

Cortex-Debug: VSCode debugger extension version 1.12.1 git(652d042). Usage info: https://github.com/Marus/cortex-debug#usage
"configuration": {
    "name": "Build & Debug Microcontroller - ST-Link",
    "cwd": "C:\\Users\\user\\Documents\\VSCode\\STM\\UrbanWatt\\System_1--RxF042F6P6",
    "type": "cortex-debug",
    "executable": "C:/Users/user/Documents/VSCode/STM/UrbanWatt/System_1--RxF042F6P6/build/Debug/System_1--RxF042F6P6.elf",
    "request": "launch",
    "servertype": "stlink",
    "device": "STM32F042F6Px",
    "interface": "swd",
    "serialNumber": "",
    "runToEntryPoint": "main",
    "svdFile": "c:\\ST\\STM32CubeCLT_1.17.0/STMicroelectronics_CMSIS_SVD/STM32F0x2.svd",
    "v1": false,
    "serverpath": "c:\\ST\\STM32CubeCLT_1.17.0/STLink-gdb-server/bin/ST-LINK_gdbserver",
    "stm32cubeprogrammer": "c:\\ST\\STM32CubeCLT_1.17.0/STM32CubeProgrammer/bin",
    "stlinkPath": "c:\\ST\\STM32CubeCLT_1.17.0/STLink-gdb-server/bin/ST-LINK_gdbserver",
    "armToolchainPath": "c:\\ST\\STM32CubeCLT_1.17.0/GNU-tools-for-STM32/bin",
    "gdbPath": "c:\\ST\\STM32CubeCLT_1.17.0/GNU-tools-for-STM32/bin/arm-none-eabi-gdb",
    "serverArgs": [
        "-m",
        "0"
    ],
    "showDevDebugOutput": "raw",
    "__configurationTarget": 6,
    "gdbServerConsolePort": 55878,
    "pvtAvoidPorts": [],
    "chainedConfigurations": {
        "enabled": false
    },
    "debuggerArgs": [],
    "swoConfig": {
        "enabled": false,
        "decoders": [],
        "cpuFrequency": 0,
        "swoFrequency": 0,
        "source": "probe"
    },
    "rttConfig": {
        "enabled": false,
        "decoders": []
    },
    "graphConfig": [],
    "preLaunchCommands": [],
    "postLaunchCommands": [],
    "preAttachCommands": [],
    "postAttachCommands": [],
    "preRestartCommands": [],
    "postRestartCommands": [],
    "preResetCommands": [],
    "postResetCommands": [],
    "toolchainPath": "c:\\ST\\STM32CubeCLT_1.17.0/GNU-tools-for-STM32/bin",
    "toolchainPrefix": "arm-none-eabi",
    "extensionPath": "c:/Users/user/.vscode/extensions/marus25.cortex-debug-1.12.1",
    "registerUseNaturalFormat": true,
    "variableUseNaturalFormat": true,
    "pvtVersion": "1.12.1",
    "__sessionId": "20b7a48d-860a-4e37-862b-9dbb58bbebd7",
    "pvtShowDevDebugOutput": "raw"
}
Reading symbols from c:/ST/STM32CubeCLT_1.17.0/GNU-tools-for-STM32/bin/arm-none-eabi-objdump.exe --syms -C -h -w C:/Users/user/Documents/VSCode/STM/UrbanWatt/System_1--RxF042F6P6/build/Debug/System_1--RxF042F6P6.elf
Reading symbols from c:/st/stm32cubeclt_1.17.0/gnu-tools-for-stm32/bin/arm-none-eabi-nm.exe --defined-only -S -l -C -p C:/Users/user/Documents/VSCode/STM/UrbanWatt/System_1--RxF042F6P6/build/Debug/System_1--RxF042F6P6.elf
Launching GDB: "c:\\ST\\STM32CubeCLT_1.17.0/GNU-tools-for-STM32/bin/arm-none-eabi-gdb" -q --interpreter=mi2
1-gdb-version
Setting GDB-Server CWD: c:\ST\STM32CubeCLT_1.17.0/STLink-gdb-server/bin
Launching gdb-server: "c:\\ST\\STM32CubeCLT_1.17.0/STLink-gdb-server/bin/ST-LINK_gdbserver" -p 50000 -cp "c:\\ST\\STM32CubeCLT_1.17.0/STM32CubeProgrammer/bin" --swd --halt -m 0
    Please check TERMINAL tab (gdb-server) for output from c:\ST\STM32CubeCLT_1.17.0/STLink-gdb-server/bin/ST-LINK_gdbserver
Finished reading symbols from objdump: Time: 52 ms
Finished reading symbols from nm: Time: 64 ms
-> =thread-group-added,id="i1"
-> ~"GNU gdb (GNU Tools for STM32 12.3.rel1.20240926-1715) 13.2.90.20230627-git\n"
-> ~"Copyright (C) 2023 Free Software Foundation, Inc.\n"
-> ~"License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permitted by law."
-> ~"\nType \"show copying\" and \"show warranty\" for details.\n"
-> ~"This GDB was configured as \"--host=x86_64-w64-mingw32 --target=arm-none-eabi\".\n"
-> ~"Type \"show configuration\" for configuration details.\n"
-> ~"For bug reporting instructions, please see:\n"
-> ~"<https://www.gnu.org/software/gdb/bugs/>.\n"
-> ~"Find the GDB manual and other documentation resources online at:\n    <"
-> ~"http://www.gnu.org/software/gdb/documentation/>.\n\n"
-> ~"For help, type \"help\".\n"
-> ~"Type \"apropos word\" to search for commands related to \"word\".\n"
-> 1^done
2-gdb-set mi-async on
-> 2^done
3-interpreter-exec console "set print demangle on"
-> 3^done
4-interpreter-exec console "set print asm-demangle on"
-> =cmd-param-changed,param="print asm-demangle",value="on"
-> 4^done
5-enable-pretty-printing
-> 5^done
6-interpreter-exec console "source c:/Users/user/.vscode/extensions/marus25.cortex-debug-1.12.1/support/gdbsupport.init"
-> 6^done
7-interpreter-exec console "source c:/Users/user/.vscode/extensions/marus25.cortex-debug-1.12.1/support/gdb-swo.init"
-> =cmd-param-changed,param="language",value="c"
-> =cmd-param-changed,param="language",value="auto"
-> 7^done
8-interpreter-exec console "set output-radix 0xa"
-> ~"Output radix now set to decimal 10, hex a, octal 12.\n"
Output radix now set to decimal 10, hex a, octal 12.
-> 8^done
9-interpreter-exec console "set input-radix 0xa"
-> ~"Input radix now set to decimal 10, hex a, octal 12.\n"
Input radix now set to decimal 10, hex a, octal 12.
-> 9^done
10-file-exec-and-symbols "C:/Users/user/Documents/VSCode/STM/UrbanWatt/System_1--RxF042F6P6/build/Debug/System_1--RxF042F6P6.elf"
-> 10^done
11-target-select extended-remote localhost:50000
-> =thread-group-started,id="i1",pid="42000"
-> =thread-created,id="1",group-id="i1"
-> ~"0x1fffcb44 in ?? ()\n"
0x1fffcb44 in ?? ()
-> *stopped,frame={addr="0x1fffcb44",func="??",args=[],arch="armv6s-m"},thread-id="1",stopped-threads="all",core="0"
mi2.status = stopped
Program stopped, probably due to a reset and/or halt issued by debugger
-> 11^connected
12-interpreter-exec console "monitor reset"
-> @"STM32 Successfully completed reset operation (System reset)\n"
STM32 Successfully completed reset operation (System reset)
-> 12^done
13-target-download
-> 13+download,{section=".isr_vector",section-size="192",total-size="810864"}
-> 13+download,{section=".isr_vector",section-sent="192",section-size="192",total-sent="192",total-size="810864"}
-> 13+download,{section=".text",section-size="10988",total-size="810864"}
-> 13+download,{section=".rodata",section-size="112",total-size="810864"}
-> 13+download,{section=".init_array",section-size="4",total-size="810864"}
-> 13+download,{section=".fini_array",section-size="4",total-size="810864"}
-> 13+download,{section=".data",section-size="104",total-size="810864"}
-> 13^done,address="0x080027e4",load-size="11404",transfer-rate="43256",write-rate="1900"
14-interpreter-exec console "monitor reset"
-> @"STM32 Successfully completed reset operation (System reset)\n"
STM32 Successfully completed reset operation (System reset)
-> 14^done
15-interpreter-exec console "monitor halt"
-> @"Trying to halt core...\n"
Trying to halt core...
-> 15^done
16-break-insert "c:\\Users\\user\\Documents\\VSCode\\STM\\UrbanWatt\\System_1--RxF042F6P6\\Core\\Src\\main.c:66"
-> ~"Note: automatically using hardware breakpoints for read-only addresses.\n"
Note: automatically using hardware breakpoints for read-only addresses.
-> 16^done,bkpt={number="1",type="breakpoint",disp="keep",enabled="y",addr="0x080008ec",func="main",file="C:/Users/user/Documents/VSCode/STM/UrbanWatt/System_1--RxF042F6P6/Core/Src/main.c",fullname="C:\\Users\\user\\Documents\\VSCode\\STM\\UrbanWatt\\System_1--RxF042F6P6\\Core\\Src\\main.c",line="78",thread-groups=["i1"],times="0",original-location="c:\\Users\\user\\Documents\\VSCode\\STM\\UrbanWatt\\System_1--RxF042F6P6\\Core\\Src\\main.c:66"}
Returning dummy thread-id to workaround VSCode issue with pause button not working
Returning dummy stack frame to workaround VSCode issue with pause button not working: {"threadId":1,"startFrame":0,"levels":20}
17-break-insert -t --function main
-> 17^done,bkpt={number="2",type="breakpoint",disp="del",enabled="y",addr="0x080008ec",func="main",file="C:/Users/user/Documents/VSCode/STM/UrbanWatt/System_1--RxF042F6P6/Core/Src/main.c",fullname="C:\\Users\\user\\VSCode\\STM\\UrbanWatt\\System_1--RxF042F6P6\\Core\\Src\\main.c",line="78",thread-groups=["i1"],times="0",original-location="-function main"}
18-exec-continue --all
-> 18^running
-> *running,thread-id="all"
mi2.status = running
19-exec-interrupt
-> 19^done
-> ~"\nProgram"

Program
-> ~" received signal SIGINT, Interrupt.\n"
 received signal SIGINT, Interrupt.
-> ~"0x1fffc8bc in ?? ()\n"
0x1fffc8bc in ?? ()
-> *stopped,reason="signal-received",signal-name="SIGINT",signal-meaning="Interrupt",frame={addr="0x1fffc8bc",func="??",args=[],arch="armv6s-m"},thread-id="1",stopped-threads="all",core="0"
mi2.status = stopped
20-break-delete
-> 20^done
21-target-disconnect
-> =thread-exited,id="1",group-id="i1"
-> =thread-group-exited,id="i1"
-> 21^done
-gdb-exit
-> ^exit
GDB session ended. exit-code: 0

**Additional context**

**Comment by haneefdm** [comment]
I don't know what you mean by program not loading. How did you determine that?

```
10-file-exec-and-symbols "C:/Users/user/Documents/VSCode/STM/UrbanWatt/System_1--RxF042F6P6/build/Debug/System_1--RxF042F6P6.elf"
-> 10^done
```

The above says we told gdb what program is being debugged.
```
13-target-download
-> 13+download,{section=".isr_vector",section-size="192",total-size="810864"}
-> 13+download,{section=".isr_vector",section-sent="192",section-size="192",total-sent="192",total-size="810864"}
-> 13+download,{section=".text",section-size="10988",total-size="810864"}
-> 13+download,{section=".rodata",section-size="112",total-size="810864"}
-> 13+download,{section=".init_array",section-size="4",total-size="810864"}
-> 13+download,{section=".fini_array",section-size="4",total-size="810864"}
-> 13+download,{section=".data",section-size="104",total-size="810864"}
-> 13^done,address="0x080027e4",load-size="11404",transfer-rate="43256",write-rate="1900"
14-interpreter-exec console "monitor reset"
-> @"STM32 Successfully completed reset operation (System reset)\n"
STM32 Successfully completed reset operation (System reset)
-> 14^done
```
We asked gdb to download the current program and it seems to have done it properly. This is normal for 99% of the usecases. Those that have multiple cores and or security images, will require customization.

I don't know how you configured the ST tools. ST also has similar debug output, btw

You can look at every line of the debug output and see what is on/wrong,

**Comment by D4NNYH** [comment]
Sorry for any confusion, essentially the program only runs (LEDs flash etc) if i manually flash the code using stm32cubeprogrammer. When doing this via cortex debugger it says this has happened however nothing is functioning, i attempt to pause the operations and add breakpoints but it appears to have no effect (other than showing the pause button is pressed and the program is "paused"). It works fine on other microcontrollers i use, however it seems to have problems only with the f042f6p6, again the chip functions fine when flashing without using the debugger

**Comment by haneefdm** [comment]
You can customize loading your FW using VSCode facilities launch.json, tasks.json (as a predebug action), and there are a ton of ways you can also configure cortex-debug as well

**Comment by D4NNYH** [comment]
I dont suppose youd be able to point me to what in my launch.json is causing the debugger to think it is functioning fine when nothing is actually happening please? (sorry i thought id attached this before but had missed it out)
