### ISSUE TITLE
"cannot read property  getTreeNode of null"

### ISSUE THREAD

**Issue by bjut-MrZhang** [Marus/cortex-debug#107]
"cannot cannot read property  getTreeNode of null"
breakpoint cannot work

**Comment by EEVblog** [comment]
I also have this issue.

**Comment by chriswils** [comment]
I get this error as well, but breakpoints are still working. I don't get any updated state of the Cortex peripherals (provided nrf52.svd for an nRF52840 target), so I was thinking it was related.

**Comment by aibeb** [comment]
The same issue !

**Comment by Marus** [comment]
And yeah - I have to second @rvinci's message - Love your blog @EEVblog - and if you would like to try and sort out the issues you encountered drop feel free to post additional details (like your launch.json and the SVD file being used). I had unfortunately been unable to keep up maintenance on this little side project for a number of months now and am just getting back to it.

**Comment by stefaandesmet2003** [comment]
On my system, this error only occurs when I left the 'Cortex Registers' tree list open when disconnecting or stopping the debug session. This view is hidden when no debug session is active (blue status bar), so I close it before ending the debug session. 
Great extension btw!! Haven't figured out all its features yet, but just figured out that 'attach' also starts an openocd process, but doesn't reflash the target each time I restart a debug session. cool!

**Comment by bigbrett** [comment]
I too have this error.

**Comment by haneefdm** [comment]
I get this message this too. Regardless of JLink or PyOCD or OpenOCD. But not always. I will watch carefully to see what triggers it or how to reproduce it.

**Comment by haneefdm** [comment]
Don't thinks this is happening anymore. There is a bit better error tracking as well for SVDs

Please re-open if you wish
