### ISSUE TITLE
No SVD File Loaded

### ISSUE THREAD

**Issue by adammunich** [Marus/cortex-debug#112]
A "not-loaded" bug seems to appear with this file and the following configuration: https://raw.githubusercontent.com/posborne/cmsis-svd/master/data/STMicro/STM32F405.svd

{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "cortex-debug",
            "request": "launch",
            "servertype": "jlink",
            "cwd": "${workspaceRoot}",
            "executable": "./build/ChibiOS.elf",
            "name": "STM32F405 Cortex-Debug (J-Link)",
            "device": "STM32F405RG",
            "interface": "jtag",
            "svdFile": "./debugging/STM32F405.svd", 
            "showDevDebugOutput": true
        }
    ]
}

**Comment by adammunich** [comment]
I discovered the problem, turns out, the svdFile expects an absolute directory, unlike the executable...

    "version": "0.2.0",
    "configurations": [
        {
            "type": "cortex-debug",
            "request": "launch",
            "servertype": "jlink",
            "cwd": "${workspaceRoot}",
            "executable": "./build/ChibiOS.elf",
            "name": "STM32F405 Cortex-Debug (J-Link)",
            "device": "STM32F405RG",
            "interface": "jtag",
            "svdFile": "${workspaceFolder}/debugging/STM32F405.svd", 
            "showDevDebugOutput": true
        },

**Comment by Marus** [comment]
Good catch - will look into making the svdFile reference work for relative paths as well.

**Comment by Marus** [comment]
Next release (0.2.1) should interpret relative svdFile paths properly - using full paths or ${workspaceFolder} should also still work.
