### ISSUE TITLE
Remove Check to see if gdb exists

### ISSUE THREAD

**Issue by xiaoyongdong** [Marus/cortex-debug#118]
I want to use environment variables to set GDB path.

**Comment by Marus** [comment]
This should be in release 0.2.1

**Comment by xiaoyongdong** [comment]
new issue:
![image](https://user-images.githubusercontent.com/3884211/51446591-39272780-1d4f-11e9-9d3d-8bc04e001c07.png)

**Comment by Marus** [comment]
Should be another update (v0.2.2) very shortly - noticed that I wasn't checking if an SVD file had been supplied before trying to normalize the path. You can also specify the svdFile setting to anything to work around that right at the moment.

**Comment by xiaoyongdong** [comment]
@Marus It is working in latest 0.2.3
