### ISSUE TITLE
arm-none-eabi-gdb fails to be started

### ISSUE THREAD

**Issue by rpbissonnette** [Marus/cortex-debug#121]

**Comment by rpbissonnette** [comment]
Yet another "Failed to launch OpenOCD GDB Server: Timeout".

This is almost surely an operator error (I am brand new at VS Code and am unable to read the source JS) so I beg your forgiveness in advance...

I was able to capture the OpenOCD log by trickery - but I can not see how to open any log/console on the VS side, perhaps there is a big helpful message I just can't find.

I am trying to do local debug on a Particle.io Photon.  OpenOCD  and arm-gdb talk to it fine it seems, but running strace while arm-none-eabi-objdump is found and executed, arm-none-eabi-gdb never shows up.  It isn't even searched for.

This is a newish OpenSuSe Leap installation, and here is what the OpenOCD log reports seeing through the Programers Shield:

Info : auto-selecting first available session transport "jtag". To override use 'transport select <transport>'.
adapter speed: 1000 kHz
adapter_nsrst_delay: 100
jtag_ntrst_delay: 100
none separate
cortex_m reset_config sysresetreq
Info : clock speed 1000 kHz
Info : JTAG tap: stm32f2x.cpu tap/device found: 0x4ba00477 (mfg: 0x23b (ARM Ltd.), part: 0xba00, ver: 0x4)
Info : JTAG tap: stm32f2x.bs tap/device found: 0x06411041 (mfg: 0x020 (STMicroelectronics), part: 0x6411, ver: 0x0)
Info : stm32f2x.cpu: hardware has 6 breakpoints, 4 watchpoints

(Particle Programmer Shield for Photon)

I hope I have not sown confusion, but I freely admit, I am confused.

Thanks!

**Comment by rpbissonnette** [comment]
Ooops, I failed to show the Launch.json surely the most important bit:

{
    "version": "0.2.0",
    "configurations": [{
        "type": "cortex-debug",
        "request": "launch",
        "servertype": "openocd",
        "armToolchainPath": "/home/rpbiss/.platformio/packages/toolchain-gccarmnoneeabi/bin/",
        "cwd": "${workspaceRoot}",
        "executable": "./target/VSagain.elf",
        "name": "Debug (OpenOCD)",
        "device": "STM32F205RG",
        "configFiles": ["./particle-ftdi.cfg", "./stm32f2x.cfg"],
        "interface": "jtag",
        "showDevDebugOutput": true,
        // "preLaunchCommands": [],
        "rtos": "FreeRTOS",
        "runToMain": true,
    }]
}

**Comment by Marus** [comment]
It could be some incompatibility with the platformio toolchains possibly (don't know if they have any modifications/wrappers around things that might cause issues with the way I launch things) - have you tried with an official arm tool from arm-none-eabi-gcc ubuntu?

**Comment by rpbissonnette** [comment]
Some success to report in case anyone's search hits this thread.

Comedy (tragedy) of errors.

0: Unlike ST-Link etc. the Particle Programmer's shield requires TWO USB cable connections, and the Photon has to be manually put into the flashing yellow DFU mode before attempting to debug with VS Code and the great cortex extension Marcus made.

My Guess is that program loading over the slow serial Jtag/SWD connection is significantly than using a fully functioning onboard boot loader, and the Photon 2-part support firmware is large enough for load times to matter.  

But ST-Link is just a lot more convenient and I hope someone smarter than me will figure out how to do a no-hands, no-button-push dance, single cable debug.

1. Changing from the Platformio gnu-arm support to the Official arm didn't help.
Likely as not Platformio works fine, just didn't try going back to check.

2. Even though it was on the system wide search path, this line in the launch.json seems to have failed.
"armToolchainPath": "${command:extension.getDebuggerCompilerDir}",
hard coding in  "armToolchainPath": "/opt/cross-arm/bin/",
was still necessary.  Perhaps new versions of the extension will work smoother.

3. FINALLY I get to step one and a real debugger again.

**Comment by minkir014** [comment]
I think you must use ordinary arm tool because platformio has a different protocol which needs their extension and your issue is solved now. But if you used ordinary tool. I think there won't be an issue.

**Comment by minkir014** [comment]
One thing I would say before looking into your problem with the extension. Your problem was solved in platformio extension.
