### ISSUE TITLE
cortex-debug being used with Particle Workbench

### ISSUE THREAD

**Issue by beriberikix** [Marus/cortex-debug#122]
https://community.particle.io/t/particle-workbench-now-available-on-visual-studio-code-marketplace/47432

This is less of an issue and more of a Thank You! [Particle Workbench](https://www.particle.io/workbench/), Particle's IDE based on Visual Studio Code, uses `cortex-debug` as the basis of our pre-configured debugging setup.

Thanks for all the hard work!

**Comment by Marus** [comment]
Thanks for letting me know.
