### ISSUE TITLE
Disassembly View fails

### ISSUE THREAD

**Issue by murdock-grewar** [Marus/cortex-debug#123]
With the following setup, the disassembly view fails to open completely:
Extensions:
 - ARM 0.3.0
 - C/C++ 0.21.0
 - Cortex-Debug 0.2.3
 - PlatformIO IDE 1.6.0
 - YAML 0.2.1

If I downgrade Cortex-Debug to version 0.1.21, this issue partially resolves itself, allowing me to open disassembly views (during debugging only). However, it will *immediately* switch back to the source code every time I try to focus on the disassembly view. *Sometimes* it will work if the current position of the debugger is inside the function I am trying to disassemble.

Additionally, still in version 0.1.21, there is nothing under the "Disassembly" header on the left:
![image](https://user-images.githubusercontent.com/45347321/52235627-cc985500-2918-11e9-95de-802bb502418a.png)

**Comment by john5f35** [comment]
Hi Murdock, this is actually not a problem with Cortex Debug, but the PlatformIO IDE. Cortext Debug only uses "Cortext Peripherals" and "Cortext Registers" views. 

PlatformIO incorporated a lot of code from Cortext Debug into their unified debugger in PlatformIO Plus (costs some money). They integrated the disassembly function through this disassembly view.
The problem is also that they have set it in a way that it **always** appears, which is a bit annoying.

You can "disable" it by right clicking on the disassembly view fold bar, and un-tick it in the dropdown menu. The same goes for "memory", "peripherals", "registers".

**Comment by Marus** [comment]
Unfortunately you'll need to speak talk with PlatformIO to address the version of the cortex-debug system that they've integrated into their platform; @ivankravets is the lead on that project you can find the appropriate repos to post issues to under his GitHub.

**Comment by ivankravets** [comment]
PlatformIO IDE Debugging extension is based on @WebFreak001 https://github.com/WebFreak001/code-debug. Actually, this extension "core-debug" is also based on it. We applied some patches from this repository, including Peripheral view. So, huge thanks to @Marus and @WebFreak001.

As result, there is no configuration for debugging probes, no SWO Decoding, no "native" features, and other things. We wanted to use this extension but @Marus recommended us to stay with own extension where we will provide support for all other architectures, not only ARM. See https://github.com/Marus/cortex-debug/issues/13

Our front-end supports everything that is supported by our back-end ([PIO Unified Debugger](https://docs.platformio.org/en/latest/plus/debugging.html)): ARM, Espressif, MSP430, RISC-V, and AVR is coming soon. The configuration is very simple:

```json

{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "platformio-debug",
            "request": "launch",
            "name": "PIO Debug",
            "executable": "IS_FILLED_AUTOMATICALLY_BY_OUR_EXTENSION",
            "toolchainBinDir": "IS_FILLED_AUTOMATICALLY_BY_OUR_EXTENSION",
            "preLaunchTask": {
                "type": "PlatformIO",
                "task": "Pre-Debug"
            },
            "internalConsoleOptions": "openOnSessionStart"
        }
    ]
}
```

The whole configuration is done using [platformio.ini -> debugging](https://docs.platformio.org/en/latest/projectconf/section_env_debug.html). It means that you can simultaniously use any supported IDE with this 1-Click configuration: Eclipse, VSCode, Sublime Text, Atom, etc.

> PlatformIO Plus (costs some money)

@john5f35 this is a part of our back-end and does not releate to any IDE (back-end). We have high-level debugging API and our extensions use it. People support us with PIO Plus to keep PlatformIO Project alive and independent. If someone can't pay (sudents, universities, makes, etc), we give them free access to all our PIO Plus tools (unified debugger, unit testing engine, PIO Remote) wihtout any fees. Please mail us at contact@pioplus.com

---------

Having free  + open source debugging and unit testing in PlatformIO Core is our main goal and we work on it. You can check my latest podcast with Embedded.fm => https://www.embedded.fm/episodes/274

I hope we will have great news for our community in the next 1-2months. Stay tunes with us:
- https://twitter.com/PlatformIO_Org
- https://www.linkedin.com/company/platformio/

**Comment by murdock-grewar** [comment]
I'm unclear on what is being said here. The command palette command `Cortex-Debug: View Disassembly (Function)` doesn't work. That is the issue. Shouldn't this work as long as Cortex-Debug is installed, or has this feature been removed in later versions of Cortex-Debug?

**Comment by john5f35** [comment]
@murdock-grewar The problem was that both extensions register disassembly view provider under `"disassembly"` name in VSCode. There is a race condition there. If PlatformIO IDE overrode the registration, yet the debugger was Cortex Debug, then the command will fail because there is no debug session with PlatformIO.

**Comment by Marus** [comment]
Ah - @john5f35 's comment clarifies a lot there; you can get conflicts with different plugins, that's simply going to be the nature of plugins if they are trying to do the same thing. Will look at renaming the provider to remove the conflict with PlatformIO - but not something I normally test against (Generally just have a few Git related plugins and the C/C++ support one).
