### ISSUE TITLE
No SVD File Loaded

### ISSUE THREAD

**Issue by y2sh** [Marus/cortex-debug#126]
Hi, great extension.
I have this message under 'CORTEX PERIPHERALS' , I am attaching the SVD file.
I have tried some path options - none work...
thanks.

{
            "type": "cortex-debug",
            "request": "launch",
            "servertype": "openocd",
            "cwd": "${workspaceRoot}", 
            "executable": "./build/fw.elf",
            "name": "Debug (OpenOCD)",
            "device": "SAMV71",
            "configFiles": [
                "interface/cmsis-dap.cfg",
                "target/atsamv.cfg"
            ],
            "armToolchainPath": "C:/ARM Embedded GCC/8.2.1-1.2-20190119-1237/bin",
            "showDevDebugOutput": true,
            "searchDir": ["C:/openocd-20190210/OpenOCD-20190210-0.10.0/share/openocd/scripts"],
            //"svdFile": "C:/Program Files (x86)/Atmel/Studio/7.0/packs/atmel/SAMV71_DFP/2.3.136/samv71b/svd/ATSAMV71J21B.svd"
            "svdFile": "${workspaceRoot}/ATSAMV71J21B.svd"
        }

[ATSAMV71J21B.zip](https://github.com/Marus/cortex-debug/files/2865313/ATSAMV71J21B.zip)

**Comment by thirtytwobits** [comment]
Seeing the same issue on my mac using this extension.
