### ISSUE TITLE
Cannot start JLink Server debugging

### ISSUE THREAD

**Issue by sidprice** [Marus/cortex-debug#153]
HI, I am just trying to get cortex-debug working with JLink Server and cannot get it to start. Here is my launch task:

        {
            "name": "Debug BMP Native ",
            "type": "cortex-debug",
            "request": "launch",
            "servertype": "jlink",
            "executable": "./blackmagic",
            "showDevDebugOutput": true,
            "interface": "swd",
            "device": "STM32F411RE"
        }

When I try to run my code I see this dialog:

![cortext-debug](https://user-images.githubusercontent.com/12300040/55923024-f1cb6d00-5bc0-11e9-82c9-0060cca7cd7e.PNG)

The path to the JLink Server is:

    "cortex-debug.JLinkGDBServerPath": "C:\\Program Files (x86)\\SEGGER\\JLink_V620i\\JLinkGDBServerCL.exe"

Seems I must be forgetting something, any help much appreciated.

**Comment by elsonwei** [comment]
Can you execute arm-none-eabi-gdb directly in the terminal?
If not, you need to set "cortex-debug.armToolchainPath"

**Comment by sidprice** [comment]
The path is setup in Windows and this is the output (edited):

PS C:\DataRoot\Projects\blackmagic> arm-none-eabi-gdb --version
GNU gdb (GNU Tools for Arm Embedded Processors 7-2018-q2-update) 8.1.0.20180315-git
Copyright (C) 2018 Free Software Foundation, Inc.

**Comment by elsonwei** [comment]
Please add `"cwd": "${workspaceRoot}"`

**Comment by sidprice** [comment]
Getting closer, now with this launch task:

        {
            "name": "Debug BMP Native ",
            "type": "cortex-debug",
            "request": "launch",
            "cwd": "${workspaceroot}/src",
            "servertype": "jlink",
            "executable": "blackmagic",
            "showDevDebugOutput": true,
            "interface": "swd",
            "device": "STM32F411RE",
            "preLaunchTask": "Make BMP Native"
        }

I get this error from VSCode when I attempt to run the code:

![vscode](https://user-images.githubusercontent.com/12300040/56056277-ed19cc80-5d18-11e9-9b5a-92d43dcc297a.PNG)

**Comment by sidprice** [comment]
Do you have any suggestions, I really would like to be using your plugin :o(
