### ISSUE TITLE
Add PR and Issues IDs hyperlinks to CHANGELOG

### ISSUE THREAD

**Issue by julian-poidevin** [Marus/cortex-debug#165]
To ease readability, hyperlinks may be added to the [CHANGELOG](https://github.com/Marus/cortex-debug/blob/master/CHANGELOG.md) to refer to related PR and Issues.
Right now the issues numbers are non-clickable: 
![image](https://user-images.githubusercontent.com/8756421/57604299-16ba5380-7564-11e9-9f27-61ae4f187d07.png)

Here's a example on how I would like the [CHANGELOG](https://github.com/Marus/cortex-debug/blob/master/CHANGELOG.md) to be : 

> # V0.2.4
> 
> * Updated some embedded SVD files [!138](https://github.com/Marus/cortex-debug/pull/138)  (Thanks https://github.com/clementperon for your PR)
> * Fixed parsing of some SVD files [!141](https://github.com/Marus/cortex-debug/pull/141) (Issue [#126](https://github.com/Marus/cortex-debug/issues/126) - Thanks https://github.com/mryndzionek for your PR)
> * Fixed issues with race condition on start up and improved OpenOCD support [!151](https://github.com/Marus/cortex-debug/pull/151); Should fix issues [#147](https://github.com/Marus/cortex-debug/pull/147), [#149](https://github.com/Marus/cortex-debug/pull/149) and [#150](https://github.com/Marus/cortex-debug/pull/150). A huge thanks to https://github.com/haneefdm for this PR, and his ongoing support on the project.
> * Ability to specify port ranges used [!146](https://github.com/Marus/cortex-debug/pull/146) (Thanks https://github.com/blckmn for your PR)

**Comment by Marus** [comment]
Good point - will try to keep this in mind for the future - and update the existing ones when I have time.
