### ISSUE TITLE
STM32MP157C: Resets whole board instead of just the CM4 core

### ISSUE THREAD

**Issue by UnicycleBloke** [Marus/cortex-debug#188]
I am trying to get Cortex-Debug working with the STM32MP157C-DK2 dev board. This has two cores: an A7 running Linux and an M4 running my firmware. I'm able to debug through a rather tedious chain of operations:

- copy the firmware to the Linux file system
- start/restart the firmware with SysFS
- start openocd on the PC (Linux)
- start gdb on the PC
- (gdb) target remote localhost:3333
- (gdb) monitor soft_reset_halt

I've been trying to set the openocd onwards parts of this up to launch from within VSCode, but it just resets the entire board. Followinghttps://marcelball.ca/projects/cortex-debug/cortex-debug-launch-configurations/, I think I got the incantations right up to the point where gdb connects with the server, but don't see a way to feed in the soft reset. Also, the toolchain prefix is not "arm-none-eabi-", but "arm-something_else-eabi-". Is the dependency hard-coded in Cortex-Debug? I added a soft-link to fix a file-not-found.

I'd be grateful if you could let me know how to do this. Using bare GDB is not so productive as a decent debugger.

Thanks.

**Comment by haneefdm** [comment]
The documentation is a bit outdated. You may want to visit the [ChangeLog](https://github.com/Marus/cortex-debug/blob/master/CHANGELOG.md) See the part for V0.2.7. There are a  bunch of `overrideXXX` settings. Hopefully, you won't need that and instead preXXX or postXXX settings are enough. In VACode, the package.json as yu are typing, the Intellisense gives you quite a few options (all officially supported I think). If your prefix is different use the `toolchainPrefix` setting. If you set it to `"XXX"`, then we look for `XXX-gdb` or `XXX-objdump` )of course with `.exe` appended on Windows.

Finally, use the setting `showDevDebugOutput` to see gobs of chatter between gdb and this extension. Focus on the start of the session. Once you get started properly, it is smooth sailing I think
