### ISSUE TITLE
Single Stepping does not work after assembly code

### ISSUE THREAD

**Issue by Misfittech** [Marus/cortex-debug#203]
In cortex-debug 0.3.1 if I stop the code in a library call (Assembly code) and then run to a break point in my C/C++ code the single stepping in C stops working. 
I can not find a way to view the disassembly of the C with cortex-debug but guess that it switched to instruction stepping in the assembly code and did not return to C stepping in the C/C++ code.

**Comment by haneefdm** [comment]
Could you please check it out with the newest V0.3.6 release? I can re-open if you can provide more details

**Comment by Misfittech** [comment]
I have went back to using Eclipse as it is more stable. So I do not have a
project configured for Cortex-debug to test at the moment.
