### ISSUE TITLE
Enhance memory window...

### ISSUE THREAD

**Issue by forehead2k** [Marus/cortex-debug#204]
It would be a GREAT usability improvement if the memory window supported expressions (or at least a symbol) in addition to bare addresses. Having to round trip through a map file or nm output is... tedious.

**Comment by haneefdm** [comment]
Normally, to get an address, I use the watch window and then copy the address value from there.

But between compilations, this constant address can change and one can easily miss that. GDB accepts an expression for the address but not for length/size, which should be good enough.

I looked at the [DAP protocol](https://microsoft.github.io/debug-adapter-protocol/specification#Requests_ReadMemory) and a `memoryReference` is a `string` which technically can be an expression. CortexDebug does not use this spec now for mem. reads, but wanted to be guided by this spec.

I can look at implementing this -- for the address only.

**Comment by haneefdm** [comment]
I have a prototype working. Actually seems pretty useful and very little overhead or changes to the extension. If no objections, I can do a PR next week. Here is an example with a silly expression
![image](https://user-images.githubusercontent.com/41269583/65375290-98279e00-dc48-11e9-995a-140dfc8c9a3c.png)

**Comment by haneefdm** [comment]
Probably not very useful (with threads or lower down the stack frames) but you can also view memory contents relative to a gdb recognized CPU register...

![image](https://user-images.githubusercontent.com/41269583/65375894-e770cd00-dc4e-11e9-8f7d-e918b5e0a2d7.png)

**Comment by haneefdm** [comment]
Released in V 0.3.3
