### ISSUE TITLE
Feature Request: would it be possible to get hex + binary overview of variable during debug and mouse hover? 

### ISSUE THREAD

**Issue by eimvs** [Marus/cortex-debug#212]
![image](https://user-images.githubusercontent.com/48095507/66698104-c1859800-ece3-11e9-9c93-9a6f3151e346.png)
I.e to show 128=0b1000 0000 | 0x80 instead of only 128

**Comment by haneefdm** [comment]
This is not possible. It is VSCode functionality and it has to support such a feature. You can try submitting a feature request with them. Unless you/anyone has other ideas, please close this issue.
