### ISSUE TITLE
SVD File loading error for STM8S103

### ISSUE THREAD

**Issue by arive298** [Marus/cortex-debug#219]
I'm creating an SVD File for the STM8S103 and I tried loading it to the debugger, but it does not work and all I get is `No SVD File Loaded` with the path I specified to the SVD file. 

I tried debugging the extension using the `extension + Debug Server` option with JSON setting `debugServer = 4711` in my project as specified in this issue https://github.com/Marus/cortex-debug/issues/179, and the extension setup runs perfect . I put a couple of breakpoints in the function call `getSVDFile` of extention.ts file, and in the function `debugSessionStarted` of the peripherals.ts file, and then run the debugger in my project but none of those breakpoints are reached.

Is there any suggestion on how can I debug this issue, or is there a better way of debugging an error in the SVD file using the extension? I will really appreciate any help.
 
Here is the SVD file I created in case you want to take a look.
[stm8s103.svd.zip](https://github.com/Marus/cortex-debug/files/3805673/stm8s103.svd.zip)

**Comment by haneefdm** [comment]
If you are creating a new SVD file, you may want to validate it first.

https://www.keil.com/pack/doc/CMSIS/SVD/html/svd_SVDConv_pg.html
https://www.keil.com/pack/doc/CMSIS/SVD/html/svd_validate_file_pg.html

**Comment by arive298** [comment]
Thanks
