### ISSUE TITLE
Specify debugServerPath in launch.json

### ISSUE THREAD

**Issue by RolfNoot** [Marus/cortex-debug#223]
Hi,

Currently we need to specify the path of the openOCD debugger in VS code settings.json. 

VS code settings doesn't support platform dependent variables like:
"windows": { 
                "cortex-debug.openocdPath": "${workspaceRoot}/tools_2.0/windows/openocd/openocd.exe"
            },
            "linux": { 
                "cortex-debug.openocdPath": "${workspaceRoot}/tools_2.0/linux/openocd/openocd"
            },
            "osx": {
                "cortex-debug.openocdPath": "${workspaceRoot}/tools_2.0/osx/openocd/openocd.exe"
            },

I like to see a way to have the debugServer path specified in the launch.json config.

**Comment by haneefdm** [comment]
You can already do that. The setting is called `"serverpath"`

You can also set it your global settings.json as that will always be machine specific. Then you don't have to set it for every project you create/edit and you can change all your projects from a central place. Whatever works for you :-)

> Depending on your platform, the user settings file is located here:
Windows %APPDATA%\Code\User\settings. json.
Mac $HOME/Library/Application Support/Code/User/settings. json.
Linux $HOME/. config/Code/User/settings. json.
