### ISSUE TITLE
No SVD File Loaded

### ISSUE THREAD

**Issue by dzarda** [Marus/cortex-debug#232]
The SVD view shows the "No SVD File Loaded" message. This appears to be a recurring issue judging by the recently closed issues with the same problem. Tried relative and absolute paths in the SVD path, tried forward slashes:

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "cortex-debug",
            "request": "launch",
            "servertype": "openocd",
            "svdFile": "C:/Users/Dzarda/Documents/src/lol/stm32l0x3.svd",
            "cwd": "${workspaceRoot}",
            "executable": "./target/thumbv6m-none-eabi/debug/lol",
            "name": "Debug (OpenOCD)",
            "device": "STM32L053",
            "configFiles": [
                "interface/stlink.cfg",
                "target/stm32l0.cfg",
            ]
        }
    ]
}

```

Happens in a Rust project.

Using [SVD](https://stm32.agg.io/rs/stm32l0x3.svd.patched) from this project: https://github.com/stm32-rs/stm32-rs

**Comment by haneefdm** [comment]
Maybe I can help. But a bit more context, please?

What recurring issue? What do you see? Assuming an issue with SVD, but what are you observing?

**Comment by dzarda** [comment]
Please excuse me, updated the description. Not sure about reproducability.

**Comment by haneefdm** [comment]
Hi @dzarda, I doubt this is a rust specific issue. Cortex-Debug doesn't even know what rust is. I could not figure out **exactly** which SVD file is an issue. Sometimes, this can happen if the SVD is un-parseable or there is a bug in the SVD parser. Please point to the SVD file if you can.

**Comment by dzarda** [comment]
SVD link is in the description, also here: https://stm32.agg.io/rs/stm32l0x3.svd.patched

**Comment by haneefdm** [comment]
Sorry, I did not notice the SVD link earlier. I can now duplicate the problem. There was a problem with the DMA1 peripheral (around line 756) and resulted in the SVD file parsing getting aborted.

Not sure why and investigating. Thanks.

**Comment by haneefdm** [comment]
Okay, I found and fixed the issue. It had to do with a `derivedFrom` attribute on enum values. It was not supported/expected by Cortex-Debug. However, even the current spec is unclear as to how it **should** be interpreted.

https://www.keil.com/pack/doc/CMSIS/SVD/html/elem_registers.html#elem_enumeratedValues

It appears that the references are global in scope and not referenced by its scope. ie, one enum-values can refer to totally another peripheral's register's field's, enum-values, and if simple names are used, the resolution is unclear. I have ** an implementation** that works according to how I interpret the spec., but others might disagree. Easily changed if I am corrected.

I will do a PR shortly. Don't think it has a chance of breaking anything.

**Comment by dzarda** [comment]
Can this be merged @haneefdm ?

**Comment by haneefdm** [comment]
Yes, I am closing this now. Thanks for the reminder.
