### ISSUE TITLE
Support for Keil ULINK debug probes

### ISSUE THREAD

**Issue by escherstair** [Marus/cortex-debug#250]
I see it supports J-Link, but does cortex-debug support [Keil ULINK debug probes](http://www2.keil.com/mdk5/ulink)?
I'm interested in ULINKpro

Thanks.

**Comment by escherstair** [comment]
Maybe it's supported through OpenOCD?

**Comment by haneefdm** [comment]
It may work through OpenOCD but more importantly, your executable has to work with gdb. For Cortex-Debug to work with any probe, we have to have two things

1. A gdb server that understands the probe
2. An executable that can be debugged by gdb
