### ISSUE TITLE
configFiles with environment variable not supported

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [Marus/cortex-debug#255]
Hi, my launch.json is like this
```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "openocd_debug",
      "cwd": "${workspaceRoot}",
      "executable": "${workspaceRoot}/rt-thread.elf",
      "request": "launch",
      "type": "cortex-debug",
      "servertype": "openocd",
      "device": "stm32f411ce",
      "gdbpath": "/usr/bin/gdb-multiarch",
      "configFiles": [
        "/home/`whoami`/dev/embedded/stm32/openocd/stm32f4x/jlink_board.cfg"
      ],
      // "preLaunchTask": "build",
      "runToMain": true
    }
  ]
}
```

for the configFiles section, i need to input the absolute path, can i use ~ or $HOME or other variable instead of absolute path?
great thanks for this amazing plugin, i can debug happiliy under linux.

thank you very much!!!!!!!!!!

**Comment by haneefdm** [comment]
I don't believe those strings are evaluated like on a shell command line. `~` may not work either as that is shell specific.

But, VSCode, lets you use things like `${workspaceRoot}` for predefined VSCode variables or `${env:HOME}` for any environment variables. The following link may be helpful

https://code.visualstudio.com/docs/editor/debugging

**Comment by ziyouchutuwenwu** [comment]
> I don't believe those strings are evaluated like on a shell command line. `~` may not work either as that is shell specific.
> 
> But, VSCode, lets you use things like `${workspaceRoot}` for predefined VSCode variables or `${env:HOME}` for any environment variables. The following link may be helpful
> 
> https://code.visualstudio.com/docs/editor/debugging

thank you very much! ${env:HOME} works for me~
