### ISSUE TITLE
Cant' use new pyOCD server because of default arguments

### ISSUE THREAD

**Issue by parfnick** [Marus/cortex-debug#269]
pyocd-gdbserver.exe is deprecated(but can be used) now. To run new(pyocd.exe) tool, we must use first argument - "gbd"(for example "pyocd.exe gdb ..."). Plugin(cortex-debug) uses default(see. debugadapter.js) arguments("--persist" etc) when launchs tool. So, if I want to use new version in Visual studio Code, and try to set argument "gdb" in settings, plugin places it after default arguments, and server not running.
PS: Any programmer can fix problem, if set first default argument "gdb" in "debugadapter.js" file, but it is the the "hacker method":)

**Comment by haneefdm** [comment]
We know about this. `pyocd gdbserver` is the same as the `pyocd-gdbserver`. I contributed to `pyocd` as well, so I know that they are the same.

Changing the exe name will break things if you set the executable path in your VSCode settings. Yes `--persist` is not needed. I was waiting for `pyocd-gdbserver` to be truly removed by the `pyocd` gang. We will change in a future release perhaps even before they remove it.
