### ISSUE TITLE
Dual core port issue

### ISSUE THREAD

**Issue by michaelmoon67** [Marus/cortex-debug#271]
In reference to https://github.com/Marus/cortex-debug/issues/152 which deals with debugging multiple cores. 
In that issue post and in release v0.3.5, there are two new arguments in the launch.json called "targetProcessor" and "numberOfProcessors". The logic seemed to be that you choose the target processor and the openocd port initialization changes with it. However the openocd gdb port remains 50000 no matter what targetProcessor I choose. So when I choose targetProcessor = 1, gdb looks for port 50001, when openocd opens port 50000. I can't find any documentation around how to do dual core debugging with Cortex-debug.

**Comment by haneefdm** [comment]
That is the design of openocd/pyocd and Cortex-Debug. 50000 is just the starting port for core#0 and incremented for others. What matters is what port gdb uses to connect to openocd. Look at the output of openocd like in #152. You will see that 50000 was given to core#0 and 50001 was for core#1

- numberOfProcessors -- how many TCP ports to reserve
- targetProcessor - what is the offset from the first core that gdb should use.

In the output of openocd, you will see something like the following if a dual-core chip.
```
Info : Listening on port 50000 for gdb connections
Info : Listening on port 50001 for gdb connections
```

It also depends on how your chip vendor configured the multiple cores in their config files. Some vendors never even expose the second (maintenance) core so openocd doesn't even know about the second core. Or, they can expose them as separate debug targets.

You cannot do dual-core debugging with one instance of VSCode (yet). You can only debug one core at a time in each instance of VSCode. With 0.3.5+, you can choose which core you want to debug. Before, it was always core#0. You can do dual-core debugging with two instances of VSCode as explained in #152. First VSCode should use the `"severType":  "openocd"` and the second one should use `"serverType":  "external"` or both can be external which was always possible even before 0.3.5.

Note that most implementations of Cortex-M processors do not do symmetric multiprocessing. Each processor runs a separate program while sharing some system resources.
