### ISSUE TITLE
Parsing issue of SVD file

### ISSUE THREAD

**Issue by josko7452** [Marus/cortex-debug#273]
Hi I have trouble getting SVD file loaded from:
https://github.com/m-labs/dslite2svd/blob/master/svd/tm4c123x.xml

I think it will be likely related to #232 or it is a different parsing error.

**Comment by haneefdm** [comment]
Could you post the error(s) you are seeing?

**Comment by josko7452** [comment]
It's just No SVD File Loaded <PATH>
Where <PATH> is correct path to my file (i.e. E:\WORK\Data\tm4c123x.svd)

**Comment by haneefdm** [comment]
Found the issue, fix is coming. We were not expecting peripherals without an `addressBlock`, and "_INTERRUPTS" was one such peripheral.

**Comment by haneefdm** [comment]
Could you please try the following pre-release

https://github.com/haneefdm/cortex-debug/releases/tag/v0.3.7-pre3

Use the VSIX manual installation method to install the extension

**Comment by josko7452** [comment]
@haneefdm It works on the file I've linked above.
