### ISSUE TITLE
file path in debug console not right. 'cwd' not help. 

### ISSUE THREAD

**Issue by qingyecai** [Marus/cortex-debug#275]
Hello everyone , in my setting
![image](https://user-images.githubusercontent.com/19278194/79550511-017e6b00-80cb-11ea-9f1f-8c4d2f0f0467.png)
When i start debug, in debug consle print wrong file path.
![image](https://user-images.githubusercontent.com/19278194/79550735-57eba980-80cb-11ea-8f22-156d429e62d1.png)
I press 'ctrl' and click the file path.vscode tips me:
![image](https://user-images.githubusercontent.com/19278194/79551468-48b92b80-80cc-11ea-9e42-16bf8b2c90ad.png)
This is my project path:```D:\aCorporation\Commnet\gitlab\SmartGateway```
This is my elf path:```D:\aCorporation\Commnet\gitlab\SmartGateway\build\stm32\SmartGateway.elf```
This is my code info:
```
版本: 1.44.1 (user setup)
提交: a9f8623ec050e5f0b44cc8ce8204a1455884749f
日期: 2020-04-11T01:48:12.622Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```
I try to set the vaule 'cwd' in lauch.json, but it can't help.
Can anybody help me fix it out?
Thanks.
Best Regards.

**Comment by haneefdm** [comment]
I don't think I understand the problem. gdb displays path names that are relative to how the source files are compiled. Ideally. It will resolve them if it can relative to the 'cwd' but if they are different from compilation directory vs workspace dir, then you may have problems. I have a feeling, your `cwd` should be set to `D:\aCorporation\Commnet\gitlab\SmartGateway` and not where the elf file lives.

Also, when you click on the file name, that is handled by VSCode and not this extension.

**Comment by qingyecai** [comment]
@haneefdm 
I have try  ```cwd:D:\aCorporation\Commnet\gitlab\SmartGateway``` but it's not help .
You mean I shoud  check my ```Cmakelist.txt```? or the ```Build``` task?
Thank you for your help.
Best Regards.

**Comment by qingyecai** [comment]
I have change ```"command": "cmake -G Ninja \"${workspaceFolder}\" -DCMAKE_BUILD_TYPE=Debug" ``` to ```"command": "cmake -G \"MSYS Makefiles\" \"${workspaceFolder}\" -DCMAKE_BUILD_TYPE=Debug",```
everything is ok!
