### ISSUE TITLE
Webpage with usage info is down

### ISSUE THREAD

**Issue by trondhe** [Marus/cortex-debug#277]
Hey.
Just wanted to point out that https://marcelball.ca/projects/cortex-debug/ is down, if not already known.

Was looking for info on how to use cortex debug with remote gdb server, but that was a bit difficult!

**Comment by rpatrik96** [comment]
Same for me, I could not access the webpage, although I was trying several times over more than one week.

**Comment by haneefdm** [comment]
I don't know why it is down (I don't own it) but you can use the Wayback machine

https://web.archive.org/web/20190701000000*/https://marcelball.ca/projects/cortex-debug/
