### ISSUE TITLE
FreeRTOS Debugging Issue on JLink GDB Server

### ISSUE THREAD

**Issue by gadak** [Marus/cortex-debug#279]
Hey!

I am using following - 
CPU-IMX7D
OS-FreeRTOS

When I keep a breakpoint in my task or even if I don't keep one, the debug status doesn't change after pressing run. It always remains in paused state and '[Switching to Thread 539100480]' is printed in debug output. 
Projects without RTOS are debugging properly. but have issue with RTOS. Any thing that I can do to get over this issue? 

 with following launch.json
`
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "J-Link Debug rpmsg_gpt_freertos.elf",
            "request": "launch",
            "type": "cortex-debug",
            "servertype": "jlink",
            "device": "MCIMX7D5_M4",
            "cwd": "${workspaceRoot}",
            "executable": "Debug/rpmsg_gpt_freertos.elf",
            "runToMain": true,
//            "rtos": "/opt/SEGGER/JLink_V670g/GDBServer/RTOSPlugin_FreeRTOS.so",
            "rtos": "FreeRTOS",
            "postLaunchCommands": [
                "flush regs",
                "load"
            ],
            "postRestartCommands": [
                "flush regs",
                "load"
            ],
            "armToolchainPath": "/home/kashyap/tdx-freertos/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux/gcc-arm-none-eabi-9-2019-q4-major/bin",
            "gdbTarget": "/opt/SEGGER/JLink_V670g/JLinkGDBServer"
        }
    ]
}
`
Output- 
`SEGGER J-Link GDB Server V6.70g Command Line Version
JLinkARM.dll V6.70g (DLL compiled Apr 23 2020 09:14:02)

Command line: -if swd -port 50000 -swoport 50001 -telnetport 50002 -device MCIMX7D5_M4 -rtos GDBServer/RTOSPlugin_FreeRTOS
-----GDB Server start settings-----
GDBInit file:                  none
GDB Server Listening port:     50000
SWO raw output listening port: 50001
Terminal I/O port:             50002
Accept remote connection:      yes
Generate logfile:              off
Verify download:               off
Init regs on start:            off
Silent mode:                   off
Single run mode:               off
Target connection timeout:     0 ms
------J-Link related settings------
J-Link Host interface:         USB
J-Link script:                 none
J-Link settings file:          none
------Target related settings------
Target device:                 MCIMX7D5_M4
Target interface:              SWD
Target interface speed:        4000kHz
Target endian:                 little
Connecting to J-Link...
J-Link is connected.
Firmware: J-Link ARM-OB STM32 compiled Aug 22 2012 19:52:04
Hardware: V7.00
Feature(s): RDI,FlashDL,FlashBP,JFlash,GDBFull
Checking target voltage...
Target voltage: 3.30 V
Listening on TCP/IP port 50000
Connecting to target...
Connected to target
Waiting for GDB connection...Connected to 127.0.0.1
Reading all registers
Read 4 bytes @ address 0x00910622 (Data = 0xBF00DF00)
Loading RTOS plugin: /opt/SEGGER/JLink_V670g/GDBServer/RTOSPlugin_FreeRTOS...
Loading RTOS plugin: /opt/SEGGER/JLink_V670g/GDBServer/RTOSPlugin_FreeRTOS.so...
RTOS plugin (API v1.0) loaded successfully
RTOS plugin: Loaded
Received symbol: pxCurrentTCB (0x20225150)
Received symbol: pxReadyTasksLists (0x20225154)
Received symbol: xDelayedTaskList1 (0x202251B8)
Received symbol: xDelayedTaskList2 (0x202251CC)
Received symbol: pxDelayedTaskList (0x202251E0)
Received symbol: pxOverflowDelayedTaskList (0x202251E4)
Received symbol: xPendingReadyList (0x202251E8)
Received symbol: xTasksWaitingTermination (0x00000000)
Received symbol: xSuspendedTaskList (0x202251FC)
Received symbol: uxCurrentNumberOfTasks (0x20225210)
Received symbol: uxTopUsedPriority (0x00000000)
Received symbol: uxTopReadyPriority (0x20225218)
Received symbol: vPortEnableVFP (0x009108D0)
Received symbol: FreeRTOSDebugConfig (0x00000000)
All mandatory symbols successfully loaded.
Received monitor command: halt
Halting target CPU...
...Target halted (PC = 0x00910622)
Received monitor command: reset
Resetting target
Downloading 576 bytes @ address 0x00000000
Downloading 16128 bytes @ address 0x00910000
Downloading 7784 bytes @ address 0x00913F00
Downloading 8 bytes @ address 0x00915D68
Downloading 4 bytes @ address 0x00915D70
Downloading 4 bytes @ address 0x00915D74
Downloading 276 bytes @ address 0x20220000
Writing register (PC = 0x  9100b4)
Received monitor command: reset
Resetting target
Reading all registers
Read register 0 (4 bytes) from DLL: 00002420
Read register 1 (4 bytes) from DLL: 0000F000
Read register 2 (4 bytes) from DLL: 34EF00E0
Read register 3 (4 bytes) from DLL: 000000C0
Read register 4 (4 bytes) from DLL: 00000000
Read register 5 (4 bytes) from DLL: 00000000
Read register 6 (4 bytes) from DLL: 00000000
Read register 7 (4 bytes) from DLL: A0FF2320
Read register 8 (4 bytes) from DLL: 00000000
Read register 9 (4 bytes) from DLL: 00000000
Read register 10 (4 bytes) from DLL: 00002320
Read register 11 (4 bytes) from DLL: 00000000
Read register 12 (4 bytes) from DLL: 00000000
Read register 13 (4 bytes) from DLL: 00002420
Read register 14 (4 bytes) from DLL: 17079100
Read register 15 (4 bytes) from DLL: 22069100
Read register 16 (4 bytes) from DLL: 03000041
Downloading 576 bytes @ address 0x00000000
Downloading 16128 bytes @ address 0x00910000
Downloading 7784 bytes @ address 0x00913F00
Downloading 8 bytes @ address 0x00915D68
Downloading 4 bytes @ address 0x00915D70
Downloading 4 bytes @ address 0x00915D74
Downloading 276 bytes @ address 0x20220000
Writing register (PC = 0x  9100b4)
Reading 64 bytes @ address 0x00914080
Read 2 bytes @ address 0x0091408A (Data = 0xF7FF)
Reading all registers
Read register 0 (4 bytes) from DLL: 00002420
Read register 1 (4 bytes) from DLL: 0000F000
Read register 2 (4 bytes) from DLL: 34EF00E0
Read register 3 (4 bytes) from DLL: 000000C0
Read register 4 (4 bytes) from DLL: 00000000
Read register 5 (4 bytes) from DLL: 00000000
Read register 6 (4 bytes) from DLL: 00000000
Read register 7 (4 bytes) from DLL: A0FF2320
Read register 8 (4 bytes) from DLL: 00000000
Read register 9 (4 bytes) from DLL: 00000000
Read register 10 (4 bytes) from DLL: 00002320
Read register 11 (4 bytes) from DLL: 00000000
Read register 12 (4 bytes) from DLL: 00000000
Read register 13 (4 bytes) from DLL: 00002420
Read register 14 (4 bytes) from DLL: 17079100
Read register 15 (4 bytes) from DLL: B4009100
Read register 16 (4 bytes) from DLL: 03000041
Read 4 bytes @ address 0x009100B4 (Data = 0xF8DFB672)
Read 2 bytes @ address 0x009100B4 (Data = 0xB672)
Read 4 bytes @ address 0x009100B4 (Data = 0xF8DFB672)
Read 2 bytes @ address 0x009100B4 (Data = 0xB672)
Read 4 bytes @ address 0x009100B4 (Data = 0xF8DFB672)
Read 2 bytes @ address 0x009100B4 (Data = 0xB672)
Read 4 bytes @ address 0x009100B4 (Data = 0xF8DFB672)
Read 2 bytes @ address 0x009100B4 (Data = 0xB672)
Read 4 bytes @ address 0x009100B4 (Data = 0xF8DFB672)
Read 2 bytes @ address 0x009100B4 (Data = 0xB672)
Setting breakpoint @ address 0x0091408A, Size = 2, BPHandle = 0x0001
Starting target CPU...
...Breakpoint reached @ address 0x0091408A
Reading all registers
Read register 0 (4 bytes) from DLL: 00000000
Read register 1 (4 bytes) from DLL: 00000000
Read register 2 (4 bytes) from DLL: C8522220
Read register 3 (4 bytes) from DLL: 25009100
Read register 4 (4 bytes) from DLL: 00000000
Read register 5 (4 bytes) from DLL: 00000000
Read register 6 (4 bytes) from DLL: 00000000
Read register 7 (4 bytes) from DLL: F8FF2320
Read register 8 (4 bytes) from DLL: 00000000
Read register 9 (4 bytes) from DLL: 00000000
Read register 10 (4 bytes) from DLL: 00002320
Read register 11 (4 bytes) from DLL: 00000000
Read register 12 (4 bytes) from DLL: 00000000
Read register 13 (4 bytes) from DLL: E8FF2320
Read register 14 (4 bytes) from DLL: 8F009100
Read register 15 (4 bytes) from DLL: 8A409100
Read register 16 (4 bytes) from DLL: 03000061
Removing breakpoint @ address 0x0091408A, Size = 2
Gtk-Message: 21:14:47.526: Failed to load module "canberra-gtk-module"
`
Debug Console Output- 
`Please check OUTPUT tab (Adapter Output) for output from JLinkGDBServer
Launching server: "JLinkGDBServer" "-if" "swd" "-port" "50000" "-swoport" "50001" "-telnetport" "50002" "-device" "MCIMX7D5_M4" "-rtos" "GDBServer/RTOSPlugin_FreeRTOS"
Launching GDB: "/home/kashyap/tdx-freertos/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux/gcc-arm-none-eabi-9-2019-q4-major/bin/arm-none-eabi-gdb" "-q" "--interpreter=mi2"
Reading symbols from /home/kashyap/tdx-freertos/eclipse-workspace/rpmsg_gpt_freertos/Debug/rpmsg_gpt_freertos.elf...
0x00910622 in prvPortStartFirstTask () at ../sources/rtos/FreeRTOS/Source/portable/GCC/ARM_CM4F/port.c:290
290		__asm volatile(
Not implemented stop reason (assuming exception): undefined
Resetting target
Resetting target
Register cache flushed.
Loading section .interrupts, size 0x240 lma 0x0
Loading section .text, size 0x5d68 lma 0x910000
Loading section .ARM, size 0x8 lma 0x915d68
Loading section .init_array, size 0x4 lma 0x915d70
Loading section .fini_array, size 0x4 lma 0x915d74
Loading section .data, size 0x114 lma 0x20220000
Start address 0x9100b4, load size 24780
Transfer rate: 84 KB/sec, 3540 bytes/write.
[New Remote target]
[New Remote target]
[Switching to Thread 539100480]`

**Comment by haneefdm** [comment]
Does doing a continue followed by a pause work?

I never used `"postLaunchCommands"` like that. Why was that needed? Especially the `load`. Wouldn't that re-load the executable and destroy your reset state and the current breakpoint? A load was already done for you following a reset.

**Comment by haneefdm** [comment]
Also isn't `flushregs` one word rather than `flush regs`. And in `postRestartCommands` doing a 'load' is not expected and not sure what that would do.

**Comment by haneefdm** [comment]
When you do a load, normally pretty much all your execution context is lost because JLink or OpenOCD has to load a temporary program into SRAM to do the programming of the device, so you are destroying all your currents RTOS-threads/tasks/PC/stack/etc.

**Comment by gadak** [comment]
> Does doing a continue followed by a pause work?
No
> I never used `"postLaunchCommands"` like that. Why was that needed? Especially the `load`. Wouldn't that re-load the executable and destroy your reset state and the current breakpoint? A load was already done for you following a reset.
I actually don't know what it does and it was there in the default script. So I didn't make any changes.

**Comment by haneefdm** [comment]
Please point me to a real issue. I really don't understand or help me duplicate it.

You have to understand what is in your launch.json. Please talk to whoever gave you that file. I am closing the issue for now.
