### ISSUE TITLE
graphConfig

### ISSUE THREAD

**Issue by marvelou-s** [Marus/cortex-debug#283]
The goal is to get separate runtime graphs during debug. How could I attach data from different ITM channels? I found the only one example posted last year (#139), but it isn't clear and maybe not actual already. I didn't find any documentation in the same time.

Looking for any suggestions. Thank you!

**Comment by PhilippHaefele** [comment]
@marvelou-s I think https://github.com/Marus/cortex-debug/wiki/SWO-Output#vscode-cortex-debug-configuration documents what you wanted to do. The only thing to mention is that port = ITMChannel.

To have multiple graphs just add another entry to the "graphConfig" array (not tested, but as it is an array it‘s the obvious thing to go).

If you have any further questions just state that here so we can extend the documentation.

@haneefdm Please close the issue. Thanks

**Comment by haneefdm** [comment]
Thanks @PhilippHaefele
