### ISSUE TITLE
Workflow conversion from Mcuxpresso to Vscode + arm compiler + cortex-debug

### ISSUE THREAD

**Issue by victorcanoz** [Marus/cortex-debug#293]
Hi,

I've successfully configured cortex-debug (nice work by the way!) and now I would also like to compile directly from VS code before starting the debugger.

Below is my launch configuration
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "cortex-debug",
            "request": "launch",
            "name": "Cortex Debug",
            "cwd": "${workspaceRoot}",
            "executable": "Debug/ferlim-detecteur-foulee.axf",
            "serverpath": "C:/Program Files (x86)/SEGGER/JLink/JLinkGDBServerCL.exe",
            "servertype": "jlink",
            "device": "LPC55S69",
            "interface": "swd", // or "jtag" - but usually "swd"
            "serialNumber": "", //if you have more than one J-Link probe add the serial number here 
            "runToMain": true,
        }
    ]
  }
```
Has anyone written a small how to ?
I would like to use the makefile generated by Mcuxpresso, but so far it does not work correctly.

Thanks

**Comment by haneefdm** [comment]
This is actually covered by the basic VSCode docs.
https://code.visualstudio.com/docs/editor/debugging

If you want to force a build before debugging, use `preLaunchTask` in `launch.json` and you have to create a `task.json` for your build tasks. You can run make or whatever else command you want
https://code.visualstudio.com/docs/editor/tasks

Hopefully, you installed the cpptols extension from MS. A generic simple example can be found here
https://github.com/microsoft/vscode-cpptools/tree/master/Code%20Samples/Fib

I have attached one of my own `tasks.json`...pay attention to the `problemMatcher`
[tasks.json.zip](https://github.com/Marus/cortex-debug/files/4635595/tasks.json.zip)
