### ISSUE TITLE
'cortex peripherals' window doesn't show up for me

### ISSUE THREAD

**Issue by nihalpasham** [Marus/cortex-debug#296]
I've placed the official `svd file` in the root folder of my project.  My `launch.json` is as follows

``` json
"version": "0.2.0",
     "configurations": [
           {
             "type": "cortex-debug",
             "request": "attach",
             "servertype": "openocd",
             "cwd": "${workspaceRoot}",
             "executable": "./target/thumbv7em-none-eabihf/debug/test-boot",
             "preLaunchTask": "boot build",
             "name": "Debug attach (OpenOCD)",
             "device": "nRF52840_xxAA",
             "configFiles": [
                 "interface/cmsis-dap.cfg", 
                 "target/nrf52.cfg"
             ],
             "svdFile": "${workspaceRoot}/nrf52840.svd",
         },
```
However, the cortex-peripheral window does not show up. Am I missing something?

**Details**
MCU - nrf52840-mdk (From makerdiary)
Screenshot -
![image](https://user-images.githubusercontent.com/20253082/82722406-178fd480-9ce4-11ea-8786-136ed19692a6.png)

SVD file location screenshot -
![image](https://user-images.githubusercontent.com/20253082/82722258-9dab1b80-9ce2-11ea-8bed-fd85af06dd9b.png)

**Comment by haneefdm** [comment]
Hmmm, you should see the `PERIPHERALS` section even if there is no svd file. I notice that this is an 'attach` session type. Does this also happen for a `launch` session type?

Could you also give us the version info for VSCode using 'About Visual Studio Code'

**Comment by nihalpasham** [comment]
Yes, its the same for a `launch` type session as well. 

![image](https://user-images.githubusercontent.com/20253082/82737625-e9e07500-9d4f-11ea-9730-d0cfee01c0c7.png)

**VsCode version info:**
```
Version: 1.45.1 (system setup)
Commit: 5763d909d5f12fe19f215cbfdd29a91c0fa9208a
Date: 2020-05-14T08:27:35.169Z
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```
In addition to the above issue, I noticed the `variables` window tends to be a bit glitchy i.e. it sometimes populates `locals` with variable-information of a previous function call and in some cases, it doesn't load anything (gives me a constant `loading-type circular animation` ).

**Comment by nihalpasham** [comment]
Hi @haneefdm - just checking if there's an update. Also, was wondering - could I be missing some setting in my installation?

**Comment by haneefdm** [comment]
I will look at it over this weekend. In the meantime, can you try the following?

https://github.com/haneefdm/cortex-debug/releases/tag/v0.3.7-pre2

You have to download the vsix file and use VSCode to Install the extension. Do NOT double click on it.

**Comment by nihalpasham** [comment]
I think I stumbled upon the answer (and its deceptively hilarious). 
1. Right click the 'cortex-registers' tab  and select the option to show cortex-peripherals. 
2. Screenshot attached.

![2020-06-08](https://user-images.githubusercontent.com/20253082/84009797-6ea6d200-a991-11ea-8c3e-bb8a7e2d1ae2.png)

**Comment by haneefdm** [comment]
I wonder how the Peripherals Window even got turned off. I didn't even down about the list of windows you can show hide.

About the variables window, we are tracking this in #295 or it could be a separate isssue
