### ISSUE TITLE
RTOS Support

### ISSUE THREAD

**Issue by razed11** [Marus/cortex-debug#30]
I'm not sure I understand this comment in the marketplace overview:

```
RTOS Support (J-Link and OpenOCD - RTOS supported depends on GDB server support)
```

To me RTOS support is the ability to see a list of tasks or the state of a mailbox etc. In particular it is nice to be able to see the call stack of any task and jump to it to examine its state. So not really a GDB thing but knowing how to find and decode the state of things on the target.

**Comment by Marus** [comment]
In general for multithreaded debugging front ends rely on the threading support within GDB. This is not to say you couldn’t in theory implement RTOS support at a higher level and interpret the in memory structures and stack directly in the front-end tools, this just isn’t how things are typically implemented. Most front-ends, the cortex debug extension included, wrap around the support in GDB. 

When it comes to threading support in GDB for RTOSs this support is provided by the GDB server - either built into the server as in OpenOCD (and enabled by a configuration command) or via plugins for the GDB server like J-Link (it is shipped with two plugins, FreeRTOS and Segger’s own embOS - but in theory additional ones can be written).

Why this is part of the GDB server and not as plugins/part of GDB itself I’m unsure - seems to me like it would have made more sense for it to be GDB plugins - but I’m sure there is some architecture reason why it is done at the server level.
