### ISSUE TITLE
STM32 watch variables at runtime

### ISSUE THREAD

**Issue by sindrevr** [Marus/cortex-debug#301]
Hi,

Is it possible to watch variables changing at runtime, or only at breakpoints when stopped?
Have  tried both ST-Link-V2-1 and Segger EDU debugger.

BR,
Sindre

**Comment by haneefdm** [comment]
Sorry, Nope. While SWD actually allows that we need GDB to do that.

I think you should use trace (ETM or SWO) to watch stuff in realtime.
