### ISSUE TITLE
Truncated call stack

### ISSUE THREAD

**Issue by bugadani** [Marus/cortex-debug#306]
Hi!

I'm debugging a Rust application running on an nRF52 (cortex-m4-r0p1) using a j-link probe and j-link server.

Most of the time the debugging experience is fine. However, my callstack seems to be truncated to 20 or so elements, even when `backtrace` in debug console lists 51.

**Comment by haneefdm** [comment]
Getting 20 at a time is the default in VSCode. There should be a UI element to get more.

Can you attach a screenshot if the call-stack window at the bottom?

**Comment by bugadani** [comment]
![callstack](https://user-images.githubusercontent.com/977627/85126124-1f805d00-b22d-11ea-981c-333e0c95eabc.png)
![backtrace](https://user-images.githubusercontent.com/977627/85126125-20b18a00-b22d-11ea-9ea0-2185d3f82144.png)

Like this? Definitely nothing to get more

**Comment by haneefdm** [comment]
VSCode initially had a hardcoded limit of 20 frames. After many complaints, looks like they fixed it. However, we were not aware they fixed it and we have to tell VSCode that "we can get more frames if it wants". You will now see the following in the Call Stack Window if there are more frames available

![image](https://user-images.githubusercontent.com/41269583/85133294-49b32a00-b1ef-11ea-838c-3e83a103d953.png)

The way VSCode UI was designed, it will only load 20 additional frames. Not in our control.

I prepared you a preview release so you can verify with Rust. Especially for accuracy.

https://github.com/haneefdm/cortex-debug/releases/tag/v0.3.7-pre4
Download the VSIX file and Install the extension manually. Instructions below
https://stackoverflow.com/questions/42017617/how-to-install-vs-code-extension-manually

**Comment by bugadani** [comment]
Wow that was fast, thank you! The preview works perfectly.

**Comment by haneefdm** [comment]
I am hoping to make a release this weekend. Enjoy
