### ISSUE TITLE
Debug command entry

### ISSUE THREAD

**Issue by coherent-lyn** [Marus/cortex-debug#307]
I have just started using this extension for debugging a Rust application with a C library.

The user manual refers to Cortex-Debug functions such as "View Memory" and "View Disassemby".

How are these commands entered?

**Comment by haneefdm** [comment]
Start a debug session and then you can use the [Command Palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette) and start typing 'cortex-debug' and you will see all the supported commands
