### ISSUE TITLE
After starting debug session, vscode defaults to "TERMINAL" tab instead of "DEBUG CONSOLE"

### ISSUE THREAD

**Issue by Teslafly** [Marus/cortex-debug#316]
After pressing f5 to compile and start debugging, the active tab in the "problems/output/terminal/debug console" area is "terminal" with the output of gcc. If the program compiles successfully I would like it to automatically switch over to the "debug console" tab. When you are in a quick "change something, f5, debug" loop, it becomes a pain to click over to the debug console every time when it should recognize that's where I want to be since the code is uploaded and I am halted at main.

Even an option to do so in launch.json such as:
`"console": "internalConsole"`
would be nice if  there is a reason to not have this behavior default.
https://stackoverflow.com/questions/49572658/vs-code-starts-debugging-in-integrated-terminal-instead-of-debug-console

**Comment by haneefdm** [comment]
This is completely out of our control. We don't do a build or know its status. It is done by VSCode and finally, we only respond to a request to start debugging and even then we have a tiny bit of control. It is all up to VSCode

For me, it always switches to Debug Console already. I wonder if something changed in core VSCode

**Comment by haneefdm** [comment]
I will look into VSCode API to see if there is a way to force a switch to "Debug Console".

I believe this area is going through some overhaul. Now you can drag other stuff (left side panel items) into this panel. Waiting for things to settle down.
![image](https://user-images.githubusercontent.com/41269583/88123993-e6673f80-cb80-11ea-8804-120cb878099b.png)
