### ISSUE TITLE
Function breakpoints aren't visible in code editor

### ISSUE THREAD

**Issue by Kozak24** [Marus/cortex-debug#320]
Function breakpoints aren't visible in code editor:
![Capture](https://user-images.githubusercontent.com/32338092/88710523-7546ff80-d11f-11ea-9bf5-fe56c8f5a09c.PNG)

In some other IDEs like Eclipse we can see function breakpoints in code editor.
Is it possible to implement this?

Please, note, it may lead to some overlapping. For e.g. if user set line breakpoint at the same line and function breakpoint. Anyway, i think it won't lead to unexpected behavior.

Thanks,
Oleh

**Comment by haneefdm** [comment]
We are sorry, it appears it is a VSCode limitation. You are not supposed to see any indicators while not in a debug session. But even during a debug session, they are not shown. We are passing all the info needed to VSCode.

If you know of any other debugger in VSCode showing function bkpts in the editor gutter, please let us know.

This issue can be raised with VSCode repo and if you do, please let us know the Issue# so we can follow it.
