### ISSUE TITLE
Unable to read memory using pyocd when step-debug

### ISSUE THREAD

**Issue by heartacker** [Marus/cortex-debug#324]
```
Unable to read memory: Unable to read memory. (from data-read-memory-bytes "0x40018000" 92)
```
Each step operation prompts  one error
![image](https://user-images.githubusercontent.com/1876302/89371891-34e71300-d717-11ea-92f3-cc8fd5bcf968.png)

**Comment by haneefdm** [comment]
You have not provided enough info to debug the problem. If you are using an SVD file, we have to read memory-mapped registers for your peripherals. Perhaps your pyocd is misconfigured.

See https://github.com/Marus/cortex-debug/issues/210

I can re-open if that is not the case
