### ISSUE TITLE
Cortex core peripherals not visible

### ISSUE THREAD

**Issue by AdrianEggenberger** [Marus/cortex-debug#326]
I'm using the cortex-debug in version 0.3.7 in combination with an Silicon Labs chip from the EFR32 family.

The debugging can be started correctly and I see all the chip specific peripherals in the "CORTEX PERIPHERALS" section. What I am missing is the Cortex specific peripherals as SYSTICK or even more important the NVIC. Where should we see these peripherals?

**Comment by haneefdm** [comment]
If they are not listed in the SVD file, then they won't be visible?

We don't make any assumptions as to which peripherals exist. You may want to contact Silicon Labs. Also search the svd file to see where it could be. They may have re-named those things
