### ISSUE TITLE
ubuntu 20.04 ships only gdb-multiarch

### ISSUE THREAD

**Issue by WoodyAtHome** [Marus/cortex-debug#337]
Hi,

I'm using ubuntu 20.04. It ships binutils-arm-none-eabi (contains arm-none-eabi-objdump) but no arm-none-eabi-gdb.
There is only a gdb-multiarch package. The gdb-multiarch debugger works fine at commandline together with openocd.

Is it possible to use gdb-multiarch together with cortex-debug or even support it in future?

**Comment by haneefdm** [comment]
We may but don't have the time/resources to experiment.

For now, you can use a symlink(s) an any other Linux trick

**Comment by Marus** [comment]
@WoodyAtHome - just as an FYI - one of the recent updates added the ability to set the GDB path including the executable name, so with that you should be able to use gdb-multiarch

**Comment by WoodyAtHome** [comment]
Thx
