### ISSUE TITLE
VARIABLES view missing types?

### ISSUE THREAD

**Issue by korken89** [Marus/cortex-debug#34]
Hi!
I cannot find a way to see the type of the variables in the `VARIABLES` view.
I'm not sure if I'm missing how to turn it on? Knowing the type helps a lot when debugging code to know if it's a pointer, or reference, etc.

I can see it when hovering, but I'd like it to always be visible, like an extra column or in parentheses or similar.

BR Emil

**Comment by Marus** [comment]
I too would like to have that information visible, unfortunately that is not how the visual studio code variables view functions - I can only provide it the info, but do not have any control over the actual presentation of the view.

I think this likely stems from the fact that a lot of the people that use (and develop) VS Code do a lot of JavaScript type code which is lax in its typing (although with Microsoft's push towards TypeScript I would think putting the types more prominent would be good).

So as much as I would like to fix it - I unfortunately cannot at the moment. I will make the suggestion in the VS Code issues though - maybe at some point they will change/make it more configurable.
