### ISSUE TITLE
option to show output from load command

### ISSUE THREAD

**Issue by JojoS62** [Marus/cortex-debug#341]
is there an option to make the output from target load (sections, transfer speed) visible? The load is exectuted somewhere after launch, but this information is not shown. When I execute 'load' again, I can see the output, but I'm also performing a 2nd download.

**Comment by haneefdm** [comment]
Yes there is. You can see it in the Terminal window and it is called `gdb-server`. Also in 'OUTPUT' window under the section 'Adapter Output'
