### ISSUE TITLE
Attaching to existing openocd session

### ISSUE THREAD

**Issue by ubidefeo** [Marus/cortex-debug#343]
hi 
I'm looking for a way to connect to an `openocd` session initiated manually.
I bumped into issue #36 while searching for a duplicate but the issue was about something else (kinda).

I have a series of scripts that launch `openocd` and I'd like to have a configuration `launch.json` that allows me to skip launching the server.
Any hints?

thank you
ubi

**Comment by Marus** [comment]
There is a pre-existing “external” type which is intended for use with externally launched/managed GDB servers. I wouldn’t be able to tell you an exact configuration- but should be possible to do what you want using `“servertype”: “external”`
