### ISSUE TITLE
Debug a STM32L432 using J-Link with a rest vector NOT at 0x08000000

### ISSUE THREAD

**Issue by gmgunderground** [Marus/cortex-debug#349]
Hi, I can't understand the problem, if I link my application at 0x08000000 all is working fine, but if I  link my application at 0x08004000 at 1st step the debug doesn't work. Can someone point me in the right direction? The debug window set the cursor in the right place, PC from regs seams to be right, but executing
  ldr   sp, =_estack    /* Set stack pointer */
generates a wrong PC.
What is the mistake?

Best regards

**Comment by RisinT96** [comment]
The flash base is at `0x08000000`, usually that's where the vector table should be placed, the core then finds the reset handler from this table.
If you link your program to a different location, something's gotta tell the core where the vector table is.

Since you've got not bootloader, nothing does that.

**Comment by gmgunderground** [comment]
Yes at 0x08000000 there is a bootloader, and the application vector table
is at 0x08004000, but doesn't work. Have I to set something to J-Link?

Il lun 19 ott 2020, 18:58 Tal Risin <notifications@github.com> ha scritto:

**Comment by gmgunderground** [comment]
I have find the problem, for some reasons what Visual Studio Code displays is not right
In the following image Visual Studio Code displays the right PC value bat is not the value of R15 register
![Image1](https://user-images.githubusercontent.com/3244031/96517556-6d53b300-1269-11eb-8ba3-7b395e39c9a5.png)
If I check with J-Link tools R15 has a different value! 
![Image2](https://user-images.githubusercontent.com/3244031/96517551-6cbb1c80-1269-11eb-8722-c3eca16def12.png)
If I change the value of R15 from J-Link tool and I come back to visual studio, I can debug correctly.
How can I solve the issue?

**Comment by RisinT96** [comment]
I'm having no problem debugging code that runs on top of a custom bootloader.

Are you sure your bootloader updates the Vector Table Offset Register (VTOR)  to the correct address of the program you're trying to debug?

Judging by the value of the PC, your microcontroller entered lockup mode, which means you got a HardFault and another fault after that.
That would make sense if the cpu was looking for the vector table at the wrong place, it would then try to handle interrupts with some gibberish.
