### ISSUE TITLE
How to set debug configuration selection via API

### ISSUE THREAD

**Issue by RolfNoot** [Marus/cortex-debug#356]
I am using the command `vscode.commands.executeCommand('workbench.action.debug.run')` to start the debug session. Is there a method to select the debug configuration via API?

I tried `vscode.commands.executeCommand('workbench.action.debug.selectandstart')` but this shows the popup for selecting. I like to have it set in code.

-Rolf

**Comment by RolfNoot** [comment]
Any news on this?

**Comment by Marus** [comment]
This doesn’t seem like a question related to this extension. I’d suggest looking directly related to VSCode itself
