### ISSUE TITLE
how to runtomain when pressed reset command

### ISSUE THREAD

**Issue by wyl2008056** [Marus/cortex-debug#366]
how to runtomain when pressed reset command

**Comment by KrestenHelstrup** [comment]
Hi @wyl2008056 
I also had issues with runToMain, so instead I use postLaunchCommands and PostRestartCommands. See attached part of my launch file.

            "postLaunchCommands": [
                "set mem inaccessible-by-default off",
                "monitor clrbp",
                "monitor reset",
                "break main",
                "continue"
            ],
            "postRestartCommands": [
                "break main",
                "continue"
            ]

Br

**Comment by wyl2008056** [comment]
Hi，@KrestenHelstrup
thank you !!! 
it working for me.

**Comment by KrestenHelstrup** [comment]
@Marus - Is this expected behavior or is it a bug in runToMain ?

**Comment by TorBlackbeard** [comment]
"postRestartCommands": [
            "break main",
            "continue"
        ]
Did the trick for me!

Run-to-main works fine for me, so I didn't take the other bits from @KrestenHelstrup's solution.

Just to add my comment on the "Restart" button":

When breaked somewhere in the code, and I press "Restart", the GUI just blinks one time, and the same line is highlighted, suggesting that it did not restart. 
But the it did! 
Proof is, that after pressing "Step over" once, the gui now updates, and highlights the second line i main().

But the above fix does the trick. 

Only annoyance left is: if launch has a "preLaunchTask" (to build the code), that will be executed as well. This can be annoying, if my build is slow. I just want to restart debugging the exact same elf file again.

**Comment by KrestenHelstrup** [comment]
Sounds like a mistake if restart is running preLaunchTask again.

**Comment by haneefdm** [comment]
This behavior was intentional according to @Marus because processors can very limited breakpoints (as low as 2). Instead of using `runToMain` you can always set a breakpoint in main yourself.

**Comment by tpilt** [comment]
Thanks @KrestenHelstrup , and sorry : moved that part of the question to a new ticket:
https://github.com/Marus/cortex-debug/issues/403
