### ISSUE TITLE
couldn't bind gdb to socket on port 3333: No error

### ISSUE THREAD

**Issue by Khhs167** [Marus/cortex-debug#373]
was trying out a tutorial, and when i was to run my program, i got the error: `couldn't bind gdb to socket on port 3333: No error`
My command: `openocd -f interface/stlink-v2.cfg -f target/stm32f4x.cfg`

I tried with gdb on and off

**Comment by Khhs167** [comment]
Is this the wrong place to ask, btw?

**Comment by haneefdm** [comment]
Minimum you have to post is the last of your son so we can see what you're trying to do

**Comment by haneefdm** [comment]
I meant launch.json

**Comment by Khhs167** [comment]
I killed O2flasher.exe (or something like that) and it fixed it.
