### ISSUE TITLE
How to change JLink Speed

### ISSUE THREAD

**Issue by GBIRNE** [Marus/cortex-debug#394]
It is possible to change Jlink speed? 

I have tried to change it by "serverArgs":
...
            "servertype": "jlink",
            "interface": "jtag",
            "device": "at91SAM7S64",
            "runToMain": true,
            "serverArgs":[
...
                "-speed 2000",
... 
              ], 

But it looks JTAG speed is remaining unchanged:

------Target related settings------
...
Target interface:              JTAG
Target interface speed:    4000kHz
...

**Comment by Marus** [comment]
Your serverArgs should likely be:

```
"serverArgs": [
    "-speed",
    "2000"
]
```

While logically those are one item - in terms of command line arguments they are actually two separate arguments where order matters.

Pretty sure this will fix your issue @GBIRNE  - so I'm going to close this, but please re-open if it does not.
