### ISSUE TITLE
Need required settings for hex format view in watch and variables section

### ISSUE THREAD

**Issue by v-rakkun** [Marus/cortex-debug#409]
Hello Team,

I using cortex-debug extension to debug RT6xx series processor. It is working fine for debugging. In watch able to see the varibales in hex format by adding ,x to the variable name. Instead of adding it to every variable, is there any global setting to see variables and watch window values in HEX format by default ?

Thank you
Rakesh K

**Comment by Marus** [comment]
No - for watch variables they are displayed in the GDB default format for the type of data; there is currently no global setting to override this.

**Comment by bhargavshah1988** [comment]
@Marus what are your thoughts to add a configuration for this ?

**Comment by FabianoGK** [comment]
You could add `set output-radix 16` to the `postLaunchCommands`.

**Comment by v-rakkun** [comment]
Thank you @FabianoGK.

Post launch command(set output-radix 16) is working as expected.
