### ISSUE TITLE
Adding more tag on description.

### ISSUE THREAD

**Issue by kbumsik** [Marus/cortex-debug#41]
Hello,
Firstly thank you very much for this awesome extension. It does exactly what I need. I would like to share my experience and simeple suggestions here.

When tried searching extensions for embbeded system on VS code for the first time, I could not find this extension. This is because I my search words was "openocd" and "jlink" and this extension did not appear on the search result. I missed this extension for months.

So why not make this extension more searchable, e.g. adding `openocd`, `jlink`, `stlink`, and etc tags in the extension description?

Thank you.

**Comment by Marus** [comment]
Thanks for the suggestion. I’ll update to have more complete tags on the next release.

**Comment by Marus** [comment]
Unfortunately I cannot actually add any more. The VSCode extension manifest limits me to 5 explicit keywords - so I can't add one for each of the GDB servers used.
