### ISSUE TITLE
Support for 'Jump to Cursor' command

### ISSUE THREAD

**Issue by FabianoGK** [Marus/cortex-debug#418]
Visual Studio Code has a debug command _Jump to Cursor_, which lets you move program execution to a new location without executing any of the code in between. If _Jump to Cursor_ is supported by a debugger, the new command appears in the editor context menu and Command Palette while debugging.

This feature was added to Jan Jurzitza's (WebFreak) code-debug extension by WebFreak001/code-debug#177.

I created a PR #417 with the backported changes.

**Comment by zrno** [comment]
Can this be closed now? It is mentioned as implemented in the latest release notes for 4.0.0 ?

**Comment by haneefdm** [comment]
Oh yes. Thanks. Yes, it is in 0.4.0
