### ISSUE TITLE
Always make an error in the clock setting function

### ISSUE THREAD

**Issue by yueduz** [Marus/cortex-debug#433]
![2021-05-03 09-25-48 的屏幕截图](https://user-images.githubusercontent.com/1448159/116834637-95957480-abf1-11eb-9a0d-2fa11437e226.png)
I'm developing stm32h750. The same code uses stm32cubeide and debugs normally. When using Cortex Debug to debug, he made an error during the clock setting process. The location of the error is not fixed, but they are all in the clock setting function, and occasionally can run normally. I noticed that downloading using Cortex Debug is slower than stm32cubeide. 
![2021-05-03 09-26-46 的屏幕截图](https://user-images.githubusercontent.com/1448159/116834670-bb227e00-abf1-11eb-85ac-8f7abe334c00.png)
When I use a lower cpu frequency to run it, the chance of error is lower.

**Comment by haneefdm** [comment]
As an experiment, you can comment out the SVD file in launch.json to see if it improves.

Cortex-Debug does not download the program to the device. that is done by gdb and the gdb-server (link). If JLink used a slow interface clock, then it would be slower. You can check the 'Output' Window and select 'Debug Adapter'. I am sorry, I don't how that translates to your language

**Comment by yueduz** [comment]
Now I don't use svd files, and reducing the frequency doesn't work anymore.

**Comment by yueduz** [comment]
![2021-05-08 17-45-43 的屏幕截图](https://user-images.githubusercontent.com/1448159/117534808-91b88680-b025-11eb-9f45-2f61304dfd76.png)
I want to change Single run mode for a try, but how do I configure Single run mode in cortex-debug?

**Comment by haneefdm** [comment]
In `launch.json`, try `"serverArgs"` you can pass any command-line argument you want.

In this case, we request the server to exit if we started it. Is that not happening? It doesn't matter what single-run mode is, we use the same policy across all gdb servers. JLink is just one of them.

**Comment by yueduz** [comment]
I don't quite understand what you mean, I use Google Translate to translate our conversation. I used the "serverArgs" parameter and did not add it to the start command of jlink gdbserver, it seems to be added to the gdb client.

On the other hand, I manually run JLinkGDBServerExe. After a failure, I selected the option of image marking, and he succeeded. How can I add this option to cortex-debug?
![2021-05-09 10-08-36 的屏幕截图](https://user-images.githubusercontent.com/1448159/117558341-316e2700-b0af-11eb-899e-a7256539a723.png)

**Comment by yueduz** [comment]
> I don't quite understand what you mean, I use Google Translate to translate our conversation. I used the "serverArgs" parameter and did not add it to the start command of jlink gdbserver, it seems to be added to the gdb client.
> 
> On the other hand, I manually run JLinkGDBServerExe. After a failure, I selected the option of image marking, and he succeeded. How can I add this option to cortex-debug?
> ![2021-05-09 10-08-36 的屏幕截图](https://user-images.githubusercontent.com/1448159/117558341-316e2700-b0af-11eb-899e-a7256539a723.png)

I was wrong, the parameters were passed in, but an error was reported in the clock function

**Comment by yueduz** [comment]
![2021-05-09 10-53-30 的屏幕截图](https://user-images.githubusercontent.com/1448159/117559090-ef47e400-b0b4-11eb-8e86-d923633e2ca3.png)
I found another difference, cortex-debug starts "jlinkGdbServer" Target connection timeout is always 0 ms

**Comment by haneefdm** [comment]
If you want a timeout, then add `"-timeout", "5000"` to your `"serverArgs"`.

That is a loooong time btw. I can't help you with your clock function. There are too many things that can be going on and none of them are probably related to Cortex-Debug.

Since there are many command-line options to the Jlink gdb-server ... see Section 4.5 below

https://www.segger.com/downloads/jlink/UM08001

**Comment by yueduz** [comment]
I'm very sorry that I opened this question again. Because I think I found the real reason. After carefully comparing the output of stm32cubeIDE, I found that commenting out lines 42 and 45 of jlink.ts, I was able to get my board to work normally.
![2021-06-16 19-45-38 的屏幕截图](https://user-images.githubusercontent.com/1448159/122213774-e4664780-cedb-11eb-93a7-5e8eaaa58e31.png)

**Comment by yueduz** [comment]
![2021-06-16 22-31-58 的屏幕截图](https://user-images.githubusercontent.com/1448159/122238488-c0623080-cef2-11eb-9014-f9a25a4df0e6.png)
I use the overrideLaunchCommands configuration item, but he pops up an error as shown in the figure

**Comment by yueduz** [comment]
```
            "overrideLaunchCommands": [
                "monitor reset",
                "-target-download",
                "-enable-pretty-printing"
            ]
```
I finally found a way to configure
