### ISSUE TITLE
Cortex registers view shows decimal instead Hex

### ISSUE THREAD

**Issue by Delsian** [Marus/cortex-debug#440]
During debug "Cortex peripherals" shows numbers in HEX, but "Cortex registers" in Decimal.
I see no sense to show decimals for registers, probably better to set display format to Hex

[image](https://user-images.githubusercontent.com/2592414/120633601-00e19900-c473-11eb-9fb2-86624ece0289.png)

**Comment by lagerholm** [comment]
See #364.

**Comment by Delsian** [comment]
@lagerholm Thank you, right now it was resolved by adding
```
            "postAttachCommands": [
                "set output-radix 16"
            ],
```
into launch.json file. But it's a tricky workaround, I prefer to see this in the base installation.

**Comment by haneefdm** [comment]
See most recent release V0.4.2. You have support from the GUI to do this, is persistent and switchable at runtime. You can also do it as a User setting and override per workspace.
