### ISSUE TITLE
Peripheral view spuriously expanded

### ISSUE THREAD

**Issue by dzarda** [Marus/cortex-debug#448]
When starting a debug session, some sections in the peripheral view get expanded. They were collapsed before:

![obrazek](https://user-images.githubusercontent.com/3955056/123652273-718a9400-d82c-11eb-9471-59b269447154.png)

This is a significant time waste.

I had expanded these sections before and it seems like the previous opened state is somehow remembered and applied on every subsequent start. Only specific sections in the SVD are expanded.

**Comment by dzarda** [comment]
Ideally the peripheral view should stay the same between debug sessions.

**Comment by dzarda** [comment]
(And I hope it's not PlatformIO screwing with me again 😊)

**Comment by haneefdm** [comment]
@dzarda I doubt PlatformIO has anything to do with it :-)

Cortex-Debug remembers the state for peripherals window in the file `.vscode/.cortex-debug.peripherals.state.json`. Perhaps we are not updating the file correctly. This file is read after the SVD file is loaded successfully and saved at the end of a debug session.

Can you check the file contents to see what is going on?

There is one caveat that I can think of with multi-root workspaces that may be preventing it from working properly if you have multiple `.vscode` directories and Cortex-Debug is reading from one place but writing to another.

**Comment by dzarda** [comment]
No such file is present

**Comment by dzarda** [comment]
Oh it appears I'm not using this extension, but had it installed. It's platformio fault again. closing
