### ISSUE TITLE
VSIX install fails for Visual Studio Professional 2017

### ISSUE THREAD

**Issue by apena1970** [Marus/cortex-debug#46]
I have Visual Studio Professional 2017 and the VSIX installer fails. 
Log shows:

VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.

The complete log for the installer is also included.
Is this an issue with the installer or no support for this version of Visual Studio?

[VSIXInstaller_743f9e52-273e-4354-a212-7ad2c26bd984.log](https://github.com/Marus/cortex-debug/files/1921634/VSIXInstaller_743f9e52-273e-4354-a212-7ad2c26bd984.log)

**Comment by Samonitari** [comment]
It is a plugin for VS Code, which is a completely different application that the old, Visual Studio

**Comment by Marus** [comment]
As @Samonitari pointed out - this is not an extension for Visual Studio - but an extension for Visual Studio Code.
