### ISSUE TITLE
Pasting into RTT does not process characters

### ISSUE THREAD

**Issue by JoelSchofield** [Marus/cortex-debug#463]
Firstly I'd like to note how amazing having RTT support is, and means I can finally move completely to vscode for my embedded development, thanks so much for the great work!

I've noticed when pasting text into the terminal that the text is not added into the line buffer (I'm in 'cooked' mode).
I had a go with a debug session and you can see here that the message gets through to the `handleInput` func, however is then dropped as it does not meet the default cases requirement of a length of 1.
<img width="690" alt="Screen Shot 2021-08-12 at 11 18 12 am" src="https://user-images.githubusercontent.com/3232207/129124223-6ab8759d-2282-4872-82dc-cc071de628c9.png">

Im not sure if pasting is handled differently depending on the OS, but if it helps im on MacOS 11.4 with vscode 1.59.0.

**Comment by haneefdm** [comment]
Thanks for reporting this. Haha, the terminal API is supposed to be a keystroke at a time but it is giving it to me bulk when it is a paste. Let me see how I can handle it.  I just didn't think of it.

I can probably just remove the `(chr.length === 1) condition. I am not sure what I will get in every case from the keyboard. I think the rest of the code in that block should just work.

There is also an issue of non-acsii chars that I might get. Generally UTF-8. This is the part I have to think about. Does your FW handle utf8? I had some support for that but I removed it just before the release

**Comment by JoelSchofield** [comment]
I was testing removing the character length check and had an issue when moving the cursor back and then pasting, as `ACTIONS.cursorBack` was not accounting for the extra characters.
I've been playing around and found this seems to working so far:

```typescript
default:
    if (!this.handleSpecialChar(chr)) {
        this.curLine = PtyTerminal.insertCharsAt(this.curLine, chr, this.cursorPos-1);
        this.writeEmitter.fire(ACTIONS.killLineForward());
        const tail = this.curLine.slice(this.cursorPos-1);
        this.writeEmitter.fire(tail);
        if ((tail.length - chr.length) > 0) {
            this.writeEmitter.fire(ACTIONS.cursorBack(tail.length-chr.length));
        }
        this.cursorPos += chr.length;
    }
    break
```

This is my first time looking at typescript so apologies if theres issues. I check if `tail.length - chr.length > 0` as it seems calling `ACTIONS.cursorBack(0)` will still move the cursor back.

Nah I dont support UTF-8 currently, its just a simple CLI to help with development/commissioning.

Thanks again!

**Comment by haneefdm** [comment]
Thanks. Needs a bit more thought. I could support encoding properly but I doubt any FW can (or wants to) handed that. Could be, just support 7-bit ASCII. The question is what to do when the char is not 7-bit ASCII. Alternatively, I can convert everything into a set of bytes and that is what is passed back to the FW. I am afraid of what would happen if a user enters a char with an umlaut or a Chinese char. Line editing however could always be utf16 for instance. utf16 is the javascript default.

Sorry, thinking out loud.

**Comment by haneefdm** [comment]
I found a few other issues. Like multi-line paste and a few other things related to input handling. Stay tuned. I am working on a branch that I can push a bit later.

**Comment by haneefdm** [comment]
I pushed some fixes. It was a bit tricky. to paste in the middle of a line and do a multi-line paste

It is on a branch `origin/issue463` if you want to try it out.

**Comment by JoelSchofield** [comment]
Thanks Haneef, I've been using the branch for a few hours now without any issues. I'll keep at it and let you know if anything comes up!

**Comment by haneefdm** [comment]
A fix has been released and is now in the wild
