### ISSUE TITLE
SWO window prints date-time and newlines.

### ISSUE THREAD

**Issue by SteveFrenchBOSS** [Marus/cortex-debug#497]
Can't turn this feature off.

**Comment by haneefdm** [comment]
Thanks, I have been meaning to make it an option for a while. And, by default, it is false. You can try it out here...

https://github.com/Marus/cortex-debug/releases/tag/V0.4.7-pre3

But, there are other changes and you can revert back if you need to

**Comment by haneefdm** [comment]
Please close this issue if you like what you see.

**Comment by SteveFrenchBOSS** [comment]
Awesome.
