### ISSUE TITLE
Error GDB Server: Timeout on v0.4.4 to v0.4.5 for JLink debugging

### ISSUE THREAD

**Issue by cwillforeal** [Marus/cortex-debug#500]
I recently updated my cortex-debug version and had the error "Failed to launch undefined GDB Server: Timeout".  I traced the issue  starting at v0.4.5.  Here are my launch.json settings:
```
"configurations": [
        {
            "name": "Cortex Debug",
            "cwd": "${workspaceRoot}",
            "executable": "./BUILD/test.elf",
            "request": "launch",
            "type": "cortex-debug",
            "servertype": "jlink",
            "device": "RSL10",
            "interface": "swd",
            "svdFile": "../../rsl10.svd",
            "preLaunchTask": "${defaultBuildTask}"
        }
    ]
```
I have the JLink server and arm gdb path set in settings.json and confirmed they're correct.
The only thing that breaks the project is updating from 0.4.4 to 0.4.5.

**Comment by haneefdm** [comment]
Make sure you are using the right version of JLinkGDBServer.

https://github.com/Marus/cortex-debug/wiki/J-Link-Specific-Configuration

**Comment by haneefdm** [comment]
Please reopen if this is still an issue

**Comment by cwillforeal** [comment]
My issue was solved by specifying JLinkGDBServerExeCL.  Seems like the only version worked with the non CL jlink server but CL is required now.  Hope that helps!
