### ISSUE TITLE
SVD Viewer appears not to respect <readaction> SVD attributes

### ISSUE THREAD

**Issue by sephamorr** [Marus/cortex-debug#509]
The `<readaction>` SVD attribute (https://arm-software.github.io/CMSIS_5/SVD/html/elem_registers.html), specifies side effects for reading a register, specifying that "Debuggers are not expected to read this register location unless explicitly instructed by the user.".

For example, reading the `RXDR` register in STM32 SPI peripheral (RM0433 as an example) removes this value from the RX FIFO, changing the program execution that depends on reading that data. This register should be marked `<readaction>modifyExternal</readaction>` in the SVD, but this property is not respected by cortex-debug even when present.

Other debuggers I have used will require a separate double-click on a `<readaction>` tagged register.
I'm taking a look to see where might be the right place to implement this, but I am not familiar with TypeScript and this codebase, so help would be appreciated.

(Note that there's a small chance that I've misdiagnosed my issue, but I'm pretty certain this is why my microcontroller code is failing.)

**Comment by haneefdm** [comment]
Closing this in favor of #804
