### ISSUE TITLE
Improve Handling of Watch Variables

### ISSUE THREAD

**Issue by evanperrygrove-sibelinc** [Marus/cortex-debug#512]
Cortex-debug is _so close_ to entirely replacing Segger Ozone in my day-to-day workflow, but there are a few details missing from its watch variables.

### 1. Immediate retrieval of watch values

If you add a new watch in Cortex-Debug while the CPU is running, you get "not available:"
![image](https://user-images.githubusercontent.com/75807880/137929326-059bec7c-7f8c-4c3e-a226-90a265eb88f2.png)
...the value will update once you pause the CPU.

In Ozone, you immediately get the actual value, even when the CPU is running:
![image](https://user-images.githubusercontent.com/75807880/137930049-26094ff4-d30a-4bea-a8fe-6b62c5920a45.png)
...this is very important when you can't/don't want to pause the CPU.

### 2. Watch value auto-refresh

In Ozone, I can set a watch to update automatically. When I right-click on a watch in Ozone, I can choose from refresh rates of 1Hz, 2Hz, or 5Hz. It's very useful when debugging FIFOs and state machines, among other things. Cortex-Debug doesn't have this feature.

IIRC I haven't seen these capabilities in any of the OEM-provided IDEs I've used (STM32CubeIDE/Infineon DAvE/Microchip Studio/etc), but it has been years since I've used any of those tools (thanks in part to Cortex-Debug 👍)

Can these features be implemented in Cortex-Debug?

**Comment by haneefdm** [comment]
Changed my mind:
I will investigate both invasive and non-invasive methods.

I keep a TODO list https://github.com/Marus/cortex-debug/edit/master/TODO.md and I just added this to it. It is my personal backlog.

**Comment by PhilippHaefele** [comment]
Found older issue #406 with the same topic

**Comment by kisielk** [comment]
STM32CubeIDE has live watch when using GDB, even with OpenOCD. Not sure if there is a way to see how they have implemented it.

**Comment by pwnorbitals** [comment]
https://app.bountysource.com/issues/110784470-improve-handling-of-watch-variables

**Comment by haneefdm** [comment]
Closing this. See

https://github.com/Marus/cortex-debug/issues/810
