### ISSUE TITLE
Registers that need specific read sizes are garbled

### ISSUE THREAD

**Issue by doug-a-brunner** [Marus/cortex-debug#516]
I'm working with a Renesas RA2E1 MCU, and it seems to be unusually picky about how its registers are accessed. Unfortunately, this causes problems attempting to use the Cortex Peripherals view: bytes get swapped around between adjacent registers.

As an example, the WDT peripheral's address space begins at 0x40044200, with a one-byte register (WDTRR) at 0x40044200 (expected value 0xFF) and a two-byte register (WDTCR) at 0x40044202 (expected value 0x3342). The registers can only be read correctly when accessed with the right width:
```
x/2xw 0x40044200 <-- WDTCR and WDTRR swapped halfword-wise
0x40044200:	0xffff3342	0x00008080

x/4xh 0x40044200 <-- WDTCR OK, WDTRR got extra ones added
0x40044200:	0xffff	0x3342	0x0000	0x8080

x/8xb 0x40044200 <-- WDTCR incorrectly shows zeroes, WDTRR OK
0x40044200:	0xff	0x00	0x00	0x00	0x00	0x00	0x80	0x00
```
When using `print` to read the registers, GDB performs operations with matching width, and returns the expected result:
```
print/x R_WDT->WDTRR
$3 = 0xff
print/x R_WDT->WDTCR
$4 = 0x3342
```

I'm not sure how this can be fixed at a lower level; we can't simply force all operations to be broken down into bytes, since as you can see, WDTCR returns zeroes if you access it byte-wise, and we can't use word accesses, since byte order gets flipped around. GDB and Segger don't know about the register layout, so they can't break down the `-data-read-memory-bytes` into the necessary operations for all the different registers in the system.

Is there any way to get cortex-debug to access registers using only the matching width (byte, halfword, or word) as described in the SVD, instead of reading large blocks as it does normally?

**Comment by haneefdm** [comment]
No response, so closing issue

**Comment by doug-a-brunner** [comment]
@haneefdm, sorry, I missed the previous message. I'd very much like to try out your build if that is still possible.

**Comment by doug-a-brunner** [comment]
@haneefdm, just to make sure I don't drop the ball on this again, where should I look for the alpha test version? I don't see a branch or tag for this in the repo.

**Comment by haneefdm** [comment]
Sorry, busy weekend. I will create a build tonight and place it in the Releases section

https://github.com/Marus/cortex-debug/releases

It will be named `0.4.8-pre4`. I will post something here when I am done.

**Comment by haneefdm** [comment]
The release is available now at https://github.com/Marus/cortex-debug/releases

Note that there are many other changes in this pre-release. Another thing of note is that while the memory read requests are broken up into individual registers when the `"svdAddrGapThreshold": -1`, it will still be a memory read issued to gdb. There is no other mechanism to read memory from gdb. Here is a sample.
```
41-data-read-memory-bytes "0xa0001000" 4
42-data-read-memory-bytes "0xa0001004" 4
43-data-read-memory-bytes "0xa0001008" 4
44-data-read-memory-bytes "0xa000100c" 4
45-data-read-memory-bytes "0xa0001010" 4
46-data-read-memory-bytes "0xa0001014" 4
47-data-read-memory-bytes "0xa0001018" 4
48-data-read-memory-bytes "0xa000101c" 4
-> 41^done,memory=[{begin="0xa0001000",offset="0x00000000",end="0xa0001004",contents="00000000"}]
-> 42^done,memory=[{begin="0xa0001004",offset="0x00000000",end="0xa0001008",contents="00000000"}]
-> 43^done,memory=[{begin="0xa0001008",offset="0x00000000",end="0xa000100c",contents="00000000"}]
-> 44^done,memory=[{begin="0xa000100c",offset="0x00000000",end="0xa0001010",contents="00000000"}]
-> 45^done,memory=[{begin="0xa0001010",offset="0x00000000",end="0xa0001014",contents="00000000"}]
-> 46^done,memory=[{begin="0xa0001014",offset="0x00000000",end="0xa0001018",contents="00000000"}]
-> 47^done,memory=[{begin="0xa0001018",offset="0x00000000",end="0xa000101c",contents="00000000"}]
-> 48^done,memory=[{begin="0xa000101c",offset="0x00000000",end="0xa0001020",contents="00000000"}]

```
Please let me know if this was helpful.

**Comment by doug-a-brunner** [comment]
@haneefdm, this is working great so far. Thanks very much for the build! I'll continue using it and report any problems that I notice.

**Comment by haneefdm** [comment]
I had less than 10% hope that it would work, but I am glad it works for you.
