### ISSUE TITLE
Blackmagic Probe: not called "detach" or "quit" on Stop.

### ISSUE THREAD

**Issue by DrZlo13** [Marus/cortex-debug#517]
Calling these functions is very important, since only then the debug register and breakpoints are cleared.

**Comment by DrZlo13** [comment]
Hello, have you receive BMP? If so, can you test you test the behavior I'm talking about when you hit stop after attach and attach afterwards?

**Comment by haneefdm** [comment]
I have received it but I don't know how to use it. All I got is two Nucleo boards F429ZI & H745ZI-Q, these don't even have a 10-pin connector it seems.

I also have a [PSoC™ 6 WiFi-BT Pioneer Kit](https://www.infineon.com/cms/en/product/evaluation-boards/cy8ckit-062-wifi-bt/?utm_source=cypress&utm_medium=referral&utm_campaign=202110_globe_en_all_integration-dev_kit)  which doesn't seem to be supported. It does have a 10-pin connector. Do you have support for this device?

**Comment by haneefdm** [comment]
This is very old and I am closing it. If it is still a problem, please file a new issue. Currentluy, we do support detach and it is regardless of the gdb-server. It is up to the server to do the right thing. Some do, and some dont.
