### ISSUE TITLE
Dependency vulnerability report

### ISSUE THREAD

**Issue by masonzaizhe2** [Marus/cortex-debug#519]
Hi,
This is just a concern about the results I get from the dependency check scan. It returns a list of 7 vulnerable dependencies found in the latest version of cortex-debug. Could you please confirm if you are using these dependencies in your code and update them for security purpose? The scanning result is attached below.
Thanks
[cortex-debug_dependency-check_2021-11-01.zip](https://github.com/Marus/cortex-debug/files/7456089/cortex-debug_dependency-check_2021-11-01.zip)

**Comment by haneefdm** [comment]
Thanks. Dependencies have been updated and pushed.
```
 % npm install          

up to date, audited 411 packages in 836ms

38 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
