### ISSUE TITLE
Unexpected behavior with the "conditional expression breakpoints" in the Cortex-Debug extension

### ISSUE THREAD

**Issue by klazklaz77** [Marus/cortex-debug#524]
Hi, everyone, when I tested the application in the VS Code IDE I find unexpected behavior with conditional expression breakpoints in the Cortex-Debug VS Code Extension.
Steps to reproduce:
1. Set conditional expression breakpoint with some mistake in the expression (ex. ">2$");
2. Remove or disable the breakpoint.
3. Perform "Continue" a few times;

Expected result:
- Debugger doesn't stop in code at all;
Actual result:
- Debugger stops on the breakpoint;

OS: Windows 10;

Versions:
- VSCode 1.62.0;
- C/C++ 1.7.1;
- Cortex-Debug VS Code Extension 0.4.7;

Attachments:
- Step 1

![Step 1](https://user-images.githubusercontent.com/54813908/141098575-d3b6b5a0-84e9-4655-9754-e1f3f859ea11.jpg)
- Step 2

![Step 2](https://user-images.githubusercontent.com/54813908/141098615-bcc41e1d-1ae9-46a9-ae5f-7df6abf9322f.jpg)
- Step 3

![Step 3](https://user-images.githubusercontent.com/54813908/141098636-51eef786-08ab-4283-bed3-61619dd2eecf.jpg)

Regards, Vitalii Loik.

**Comment by haneefdm** [comment]
Thanks for reporting this. Able to reproduce this and fix on the way

**Comment by haneefdm** [comment]
This will be fixed in the next release. A pre-release is available here 

https://github.com/Marus/cortex-debug/releases/tag/v0.4.8-pre5

Re-open if needed
