### ISSUE TITLE
Unexpected behavior with breakpoints in the Cortex-Debug extension

### ISSUE THREAD

**Issue by klazklaz77** [Marus/cortex-debug#525]
Hello, everyone!
I would like to report about unexpected behavior with breakpoints in the Cortex-Debug extension for VS Code IDE.

Step to reproduce:

1.  Click launch the application and wait before the board will be launched.
![image](https://user-images.githubusercontent.com/54813908/141116175-89ba94e8-efb5-4f6c-8630-b6b0ced2013b.png)

2.  Set a breakpoint on the non-command line in the program code (for example lines 158-160 on screenshot 2).
![image](https://user-images.githubusercontent.com/54813908/141116688-c2e45cfa-1683-493b-9cdb-5f825b9a757f.png)

3. Repeat step 2 in the same line, breakpoints will be put on the next program command line, and in the "breakpoints panel" will be 2 breakpoints per 1 line.
![image](https://user-images.githubusercontent.com/54813908/141117344-96f68cae-b2d8-441f-a914-adcba68357c6.png)

4. Click on the breakpoint one time. Breakpoints will disappear from the "breakpoints panel" and code editor.
![image](https://user-images.githubusercontent.com/54813908/141117999-4b8fa9c0-e0cb-4c49-a44f-213fd67d95d5.png)

5. Perform "Continue" a few times.
![image](https://user-images.githubusercontent.com/54813908/141118098-c9d357e1-8dac-4614-bdc8-c0d9770be14c.png)

Expected result:

- Debugger doesn't stop in code at all;

Actual result:

- Debugger stops on the (invisible) breakpoint;

For example, I attached the video:

https://user-images.githubusercontent.com/54813908/141118713-64485fd7-03a1-40d9-8e27-e6ccb0b163cd.mp4

Regards, Vitalii Loik.

**Comment by haneefdm** [comment]
Thanks for reporting this.  The video was helpful and I will try to reproduce this.

Did you notice anything in the `Breakpoints` window? Things appearing, disappearing, greying out, etc? There is also stuff displayed on hover.

Basically, gdb created a breakpoint on line 164 when you asked for line 159 where there is no code after gdb compiled your C file. If gdb cannot find code at the specific line you ask for, it sets the breakpoint at the next available line. But then you set a breakpoint at that same line and VSCode notifies us and we notify gdb and I cannot tell what happened after that. It was a duplicate breakpoint but not sure how it got handled.

You can enable `"showDevDebugOutput": true` in your launch.json and see what is happening for each action you do. In the Debug Console, you can also enter regular gdb commands. After the entire video, if you do a `info breakpoints`, I bet you saw a breakpoint -- although neither VSCode or Cortex-Debug know about it.

**Comment by klazklaz77** [comment]
Hi, after I set the breakpoint at the line (ex. 159) first time in the breakpoints panel I see one active breakpoint at the next available line (164). It is expected. 

![image](https://user-images.githubusercontent.com/54813908/141300494-954c276f-52cc-42dc-a21a-4252a556c3a9.png)

If I set the breakpoint at the same line one more time, I see in the breakpoints panel one more active breakpoint with the same number.

![image](https://user-images.githubusercontent.com/54813908/141300742-d9aa36c7-982e-4205-a3e7-5b5417ed1b51.png)


If I want to remove the breakpoints I see the two line breakpoints in the menu:

![image](https://user-images.githubusercontent.com/54813908/141300927-ec9cfd8e-39cb-4c96-8140-7e88e1c8e3ac.png)

If I do this, breakpoints will be successfully removed from the pannel and code:

![image](https://user-images.githubusercontent.com/54813908/141301124-aee2c83e-e474-4917-90b7-e235067d3787.png)

And debugger doesn't stop in the code at all.

The same situation will be If I remove the breakpoints from the breakpoints panel (remove all breakpoints or one by one):

![image](https://user-images.githubusercontent.com/54813908/141301493-92b2c82f-75b7-45ad-93b7-9eb07f1a5a25.png)

But If I click on the breakpoints in the code editor - they will disappear from the code editor and breakpoints panel, but the debugger stops at this code line:

![image](https://user-images.githubusercontent.com/54813908/141301846-0c09dfc0-f4b4-4004-9e20-fcde123454b8.png)

![image](https://user-images.githubusercontent.com/54813908/141302041-c6e8b184-7a09-45b7-becf-3779d84e4444.png)

One more situation: 
I can set the two breakpoints per one line (steps 1-3 in the bug report) and set one more breakpoint in the line where is 
program code (ex.167).

![image](https://user-images.githubusercontent.com/54813908/141303038-2fd0ab42-3a4a-4627-b00e-68c1f565e11f.png)

In this case, a number of the second breakpoint will be changed to the last used breakpoint number  (ex. 167):

![image](https://user-images.githubusercontent.com/54813908/141303297-16543e7b-92d4-4e0b-886e-908865a22b7d.png)

I hope that this info can help you and Cortex-Debug team!

**Comment by haneefdm** [comment]
This was actually a bug in VSCode in breakpoint processing and duplicates. Complicated to explain but VSCode was calling the adapter to adjust breakpoints before the previous request for the same was even finished. We have to create a workaround.

This will be fixed in the next release. A pre-release is available here 

https://github.com/Marus/cortex-debug/releases/tag/v0.4.8-pre5

Re-open if needed
