### ISSUE TITLE
Can I open debugger on a running system?

### ISSUE THREAD

**Issue by jimsyt** [Marus/cortex-debug#526]
I'd like to open the debugger and load several symbol files without downloading an image to the uC. Is that possible?

**Comment by haneefdm** [comment]
Yes, you can use `overrideLaunchCommands` to add as many gdb commands (`symbol-file` for example) as you want.

When you use this, the debugger also will not load anything into the uC. You can chose do do your own or do whatever.

Use the `showDevDebugOutput` to see what the debugger currently does in the Debug Console and grab what you want from there. A reset and halt is expect at the end of the process.
