### ISSUE TITLE
Using hardware breakpoints from GUI

### ISSUE THREAD

**Issue by Uknius** [Marus/cortex-debug#527]
Recently I started using an embedded platform that doesn't support software breakpoints.

As I understand I can set only software breakpoints from the vscode GUI. 
Is there any possibility to force GUI to use hardware breakpoints?

EDIT: I am using openOCD with FlashPRO5.

**Comment by haneefdm** [comment]
You can set whatever breakpoints you want. Neither VSCode nor this extension knows how to handle them. They will be handled by gdb which in turn gives it to OpenOCD. OpenOCD only supports HW bkpts AFAIK and that is what you are getting. We have no capability for force SW or HW breakpoints. It is up to the gdb and OpenOCD -- and depends on where the address is FLASH or SRAM.

See the Debug Console for info on what you see when you set a bkpt.

Note that we are a front-end to GDB. Anything we do translates into something for gdb.

**Comment by Uknius** [comment]
Debug console if I place a breakpoint before starting to debug:
![image](https://user-images.githubusercontent.com/94105717/141324771-a0448b4e-12e8-4577-a888-6d05ea6a0690.png)
![image](https://user-images.githubusercontent.com/94105717/141325268-0b95af21-6eb2-4512-9570-ceb598fddd7b.png)

It looks like it correctly places the breakpoint but it won't break.

The only way I got it working is by setting `hbreak main.c:35` by hand in the debug console.
![image](https://user-images.githubusercontent.com/94105717/141325675-5e51caca-5fe1-44c8-820a-b298f2432ec0.png)

**Comment by Uknius** [comment]
It look like to this: https://github.com/microsoft/vscode-cpptools/issues/4745

**Comment by haneefdm** [comment]
Note: MS Cpptools and this extension has almost nothing in common. We are both clients of VSCode infrastructure, use gdb and obey the rules set forth by VSCode, so we may look similar. Under the hood and features wise we are very different, focusing only on Embedded stuff.
