### ISSUE TITLE
serverArgs parameter passes with quotation marks

### ISSUE THREAD

**Issue by Uknius** [Marus/cortex-debug#528]
It looks like serverArgs passes arguments to the gdb-server command line with quotation marks. It leads to an unrecognized command:

![image](https://user-images.githubusercontent.com/94105717/141274894-0a19ec62-3869-4db9-90da-4c6dd51cdc83.png)

**Comment by Uknius** [comment]
For my scenario, you can replace 
serverArgs: ["--command..."] with: "openOCDPreConfigLaunchCommands" and it works, but serverArgs still not working as expected.

**Comment by haneefdm** [comment]
`serverArgs` are command line args -- unix style. So, `"--command"` and `"set DEVICE TEST"` are separate args. You can see that in the Debug Console.
```JSON
    "serverArgs": [ "--command", "set DEVICE TEST"],
```
`openOCDPreConfigLaunchCommands` is an array of commands handled by us (not bash or cmd.exe) and we automatically prepend a `-c` to each element (as separate unix-style args. Again, you can see how things are translated in the DebugConsole
