### ISSUE TITLE
openOCD does not start from launch

### ISSUE THREAD

**Issue by jancoow** [Marus/cortex-debug#531]
I'm unable to get the cortex-debug to actually start openOCD.
It does say `Please check TERMINAL tab (gdb-server) for output from /usr/local/bin/openocd` but this terminal tab never appears. 

My config:

```
        {
            "name": "Cortex-m debugger",
            "type": "cortex-debug",
            "rtos": "FreeRTOS",
            "servertype": "openocd",
            "serverpath": "/usr/local/bin/openocd",
            "configFiles": ["/home/janco/openocd.cfg"],
            "executable": "${workspaceRoot}/build/projectEbikeMonitor1.elf",
            "request": "launch",
            "device": "ATSAMR34J18B",
            "showDevDebugOutput": true
        },
```

**Comment by haneefdm** [comment]
You will see the exact command used by Cortex-Debug in the Debug Console. Are you able to run this command from a shell/command-line?

The gdb-server Terminal doesn't show until the first server actually starts. I assume you saw no other error message?

**Comment by haneefdm** [comment]
Closing due to no response
