### ISSUE TITLE
Debugger shows disassembly instead of source code

### ISSUE THREAD

**Issue by ben-sharpe** [Marus/cortex-debug#537]
I'm currently writing a program in C++ for the Raspberry Pi Pico and I'm using openocd and cortex debug in VSCode. I'm setting breakpoints in the source code but they do not get hit, only the corresponding disassembly code. I read in the description for Cortex Debug that disassembly would be shown if the corresponding source file can't be found so I'm assuming that's my issue, but I'm not sure how to fix the problem.

I've been stuck trying to fix this issue for a few days now and haven't made any progress, I appreciate any help or suggestions.

These are the config files and folder structure, also this is the YouTube video I followed to set everything up if that helps:
[https://youtu.be/0i2gLeBal9Y](url)

launch.json:
`{
    "version": "0.2.0",
    "configurations": [
        
        {
            "name": "Pico Debug",
            "cwd": "${workspaceRoot}",
            "executable": "${command:cmake.launchTargetPath}",
            "request": "launch",
            "type": "cortex-debug",
            "servertype": "openocd",
            "gdbPath" : "arm-none-eabi-gdb",
            "device": "RP2040",
            "configFiles": [
                "interface/picoprobe.cfg",
                "target/rp2040.cfg"
            ],
            "svdFile": "C:/Pico/pico-sdk/src/rp2040/hardware_regs/rp2040.svd",
            "runToMain": true,
            "postRestartCommands": [
                "break main",
                "continue"
            ],
            "searchDir": ["C:/Pico/openocd/tcl"],
            "showDevDebugOutput": true
        }
    ]
}
`

CMakeLists.txt:
`cmake_minimum_required(VERSION 3.12)

include(C:/pico/pico-sdk/external/pico_sdk_import.cmake)

project("ledproject" C CXX ASM)
set(CMAKE_C_STANDARD 11)
set(CMAKE_CXX_STANDARD 17)

set(CMAKE_CXX_FLAGS_DEBUG "-O0")
set(CMAKE_CXX_FLAGS_RELEASE "-O3")

pico_sdk_init()

add_executable(${PROJECT_NAME} "main.cpp")

pico_add_extra_outputs(${PROJECT_NAME})

target_link_libraries(${PROJECT_NAME} "pico_stdlib")

pico_enable_stdio_usb(${PROJECT_NAME} 0)
pico_enable_stdio_uart(${PROJECT_NAME} 1)`

![image](https://user-images.githubusercontent.com/60745452/142946979-b606e913-4df4-48a9-91c7-0c2cf71e59b8.png)

**Comment by haneefdm** [comment]
Maybe you are missing `-g` for gcc without which no debugging information is saved. `-O0` may not be enough.

https://gcc.gnu.org/onlinedocs/gcc-3.4.0/gcc/Debugging-Options.html#Debugging%20Options

Reopen if you are still having issues.
