### ISSUE TITLE
SVD does not load since V0.4.8

### ISSUE THREAD

**Issue by ThomasPtO** [Marus/cortex-debug#538]
Cortex Peripherals box says: "Unable to load SVD file: ./path-to-svd/LPC55S06.xml"

Same launch.json works when switching back to version V0.4.7.

Problem occures also with V0.4.10.

Running Win10 with WSL2 + debian + docker container.

Regards,
Thomas

**Comment by jmbrederveld** [comment]
Same here, specifically for the plugin in combination with the STM32F0 platform. I seem to have no issues with the latest version with the STM32F4 platform.

**Comment by haneefdm** [comment]
Could you please attach a compressed version of the SVD file? It could mean a parsing issue or even a crash. Were there any popups?

**Comment by ThomasPtO** [comment]
No popups on my side. Just the the message in the box, where the registers normally show up.

[LPC55S06.zip](https://github.com/Marus/cortex-debug/files/7642367/LPC55S06.zip)

**Comment by haneefdm** [comment]
We found and fixed the problem. Some code meant for debugging was left in the release which caused this problem. Will be fixed in the next release. Already pushed the changes to master

**Comment by haneefdm** [comment]
@ThomasPtO @jmbrederveld I just published a pre-release if you want to try out the fix. See

https://github.com/Marus/cortex-debug/releases/tag/v0.4.11-pre1

There are other unrelated changes but they could affect you.

**Comment by sjuut** [comment]
I can confirm this release solves the issue. Thank you very much!

**Comment by haneefdm** [comment]
We are moving to a new versioning system that supports pre-releases. You have to update to the latest V1.63.0+ of VSCode. In the extensions area, you should now see a green dot
![image](https://user-images.githubusercontent.com/41269583/145592651-983cbc92-aca0-4d68-ae2b-2e7ce6cf9eeb.png)
You will also see the following for install options.
![image](https://user-images.githubusercontent.com/41269583/145592807-27e18c08-13cd-4a71-b7e1-8d6cffc27241.png)
