### ISSUE TITLE
Breakpoint at main

### ISSUE THREAD

**Issue by microwavesafe** [Marus/cortex-debug#54]
I'm not sure if it's common to all projects (this is the first I have tried), but on starting the debug session, the program counter is set to my reset handler, which runs the init functions before main.

On other debuggers (Ozone / Eclipse) it would set a break point at main as this is normally where you want to start debugging. Obviously you can set a break point there, but I thought it was a good feature to have.

**Comment by Marus** [comment]
The default behaviour is for it to stop at the reset handler; there is an optional runToMain setting which will during launch set a temporary breakpoint at main and run until it hits that.
