### ISSUE TITLE
Possibility to load hex and elf

### ISSUE THREAD

**Issue by hilpara** [Marus/cortex-debug#541]
If not already possible, it would be nice to be able to load hex file and elf file separately when debugging. After compiling  I create a new an hex file where I have added CRC with srec_cat because bootloader will need it. If I only load hex file, I don't get symbols and if I load elf I don't have the CRC.

**Comment by haneefdm** [comment]
You can do this by giving gdb a different file to program.
```JSON
            "preLaunchCommands": [
                "exec-file ./build/hello.hex",
            ],
```

**Comment by haneefdm** [comment]
This is done using the config. option `loadFiles`
