### ISSUE TITLE
Zephyr task(thread) priority number not show right

### ISSUE THREAD

**Issue by rokobert** [Marus/cortex-debug#544]
In Zephyr RTOS thread priority number is singned integer. But in call stack debug window this number is show as unsigned integer.
For example: If thread priority is -1, in call stack debug windows is 255.

**Comment by haneefdm** [comment]
I don't know which gdb server you are using. (OpenOCD, JLink, STLink, etc.). It is that program's responsibility to report Thread IDs. As far as I know, that is not the same as Thread Priority and no one reports that. You may have to look at kernel thread data structures for thread priority which in some OSes are dynamic (ie change at run time)

Anyways, gdb-server reports to gdb, and gdb reports to Cortex-Debug. All of this is unmodified.
