### ISSUE TITLE
How to change the name of the gdb executable file, for example, I want to use xt-gdb（xtensa cpu）？

### ISSUE THREAD

**Issue by hongshui3000** [Marus/cortex-debug#552]
How to change the name of the gdb executable file, for example, I want to use xt-gdb（xtensa cpu）？

**Comment by haneefdm** [comment]
You may want to read this file...

https://github.com/Marus/cortex-debug/blob/master/debug_attributes.md

**Comment by PhilippHaefele** [comment]
`toolchainPrefix` is most likely the thing you are searching for.

**Comment by hongshui3000** [comment]
thanks
