### ISSUE TITLE
How to change openocd port

### ISSUE THREAD

**Issue by Blackrose** [Marus/cortex-debug#553]
Hi, I use openocd + gdb to debug stm32mp1 platform. The chip has two cores, one is a7 and another  one is cm4.So the openocd has two gdb port.But the cortex-debug use 50000 for gdb_port and 50001 for tcl_port. In actually, the 50000 for a7 and 50001 for cm4. So, how can i change/config the ports of cortex-debug on default config?

**Comment by haneefdm** [comment]
You can tell Cortex-Debug how many processors and which processor you want to connect to. Look for `numberOfProcessors` and `targetProcessor` and all the ports OpenOCD uses are adjusted.

https://github.com/Marus/cortex-debug/blob/master/debug_attributes.md
