### ISSUE TITLE
Setting break point while target running

### ISSUE THREAD

**Issue by microwavesafe** [Marus/cortex-debug#56]
I am not sure if this is a limitation of VS Code (I haven't really used it for debugging before). But setting break points while the target is running brings up a circle outline that says "unverified breakpoint" and this then does not trigger. It also doesn't become a proper break point when the target is paused either.

The hardware is capable of setting break points on a running target and I am used to setting them in other debuggers.

**Comment by Marus** [comment]
Can you try running with the "showDevDebugOutput" set to true and send me the debug log - want to see if that gives any hints as to why the breakpoint setting is failing - as there are a few reasons why that may not be happening (e.g reached the max breakpoints the hardware probe can handle, not generating a location for the breakpoint correctly) - just want to see exactly what it is sending / receiving to/from the GDB server in your case.

**Comment by microwavesafe** [comment]
Here is the log. I have manually edited the full path names, so if any look funny, it's my fault. I removed all except the main break point.

[Debug_log.txt](https://github.com/Marus/cortex-debug/files/1968153/Debug_log.txt)

I tried again with Ozone, to be sure the hardware can do this and it correctly sets break points while the target is running.

**Comment by Marus** [comment]
Have a fix ready for this (technically it will actually transparently interrupt the core, set breakpoints and restart the core); will go out in the next update.

**Comment by microwavesafe** [comment]
This seems to be working. I did see an issue once where the pause button changed to a greyed out play button, when I added a break point and didn't go back. Although I can't replicate it.

**Comment by Marus** [comment]
Odd - if you can recreate that let me know. It's something I will keep my eye on as well.
