### ISSUE TITLE
Can't restart a target if using stlink server type

### ISSUE THREAD

**Issue by mpekurin** [Marus/cortex-debug#567]
Cortex-Debug v0.4.10
ST-LINK_gdbserver v6.0.0

Raw output in the debug console:
```
interpreter-exec console "monitor reset halt"
@"Unknown reset option\n"
```

**Comment by haneefdm** [comment]
Could you try the pre-release. I don't think the 'reset' is a problem although, you won't see that anymore. A restart was working fine for me even with that issue. And it also exists on a Launch.

You can get the pre-release from VSCode itself (marketplace).

![image](https://user-images.githubusercontent.com/41269583/149206050-88cd6b53-bb9f-4cfb-853b-fbc155364c1a.png)

If the problem still persists (or not), please report back.

**Comment by mpekurin** [comment]
@haneefdm yep, it works fine in the pre-release.
