### ISSUE TITLE
Interrupt button not response before doing manually interrupt in GDB and continue.

### ISSUE THREAD

**Issue by Oyami-Srk** [Marus/cortex-debug#596]
Somehow, my configuration broke the ability to use the interrupt button on debug panel.

But it will return to normal after I continue the interrupted status ( via `interrupt` command in debug console or `runToEntryPoint` to interrupt at the beginning ).

Here is my `launch.json`:
```json
{
    "configurations": [
        {
            "name": "Debug",
            "cwd": "${workspaceRoot}",
            "executable": "./build/firmware.elf",
            "request": "launch",
            "type": "cortex-debug",
            "servertype": "jlink",
            "interface": "swd",
            // "runToEntryPoint": "main",
            "device": "STM32F429BI",
            "rtos": "FreeRTOS",
            "serverArgs": ["-nogui", "-speed 9600"],
            "rttConfig": {
                "enabled": true,
                "address": "auto",
                "decoders": [
                    {
                        "port": 0,
                        "type": "console"
                    }
                ]
            },
            "preLaunchTask": "Build Cmake",
        }
    ]
}
```

**Comment by haneefdm** [comment]
Thank you for reporting this. This issue has been elusive and it appears that it is actually a VSCode issue. Nevertheless, we were testing a workaround that was added to this extension. From our [ChangeLog](https://github.com/Marus/cortex-debug/blob/master/CHANGELOG.md)

> * Bugfix: Issue #596 If neither `breakAfterReset` or `runToEntryPoint` were used, the pause button failed to work. The program would run but the debug buttons didn't do anything. We don't know which version of VSCode broke this but we created a workaround that is being tested

You can try the pre-release (v1.3.4) if you wish while we finish testing other parts for a final release. We pushed it out to the VSCode Marketplace and it should be available shortly. You should see it in the Extensions panel in VSCode.

Please provide feedback if you are willing to try the pre-release
