### ISSUE TITLE
Support cJTAG interface

### ISSUE THREAD

**Issue by albertskog** [Marus/cortex-debug#601]
J-Link supports the cJTAG interface (`JLinkGDBServerCLExe -if cjtag `), but cortex-debug ~does not accept~ warns about this value for `interface` in `launch.json`.

Happy to provide a PR if I could get a hint where to look.

**Comment by haneefdm** [comment]
It is already supported. See `interface`

https://github.com/Marus/cortex-debug/blob/master/debug_attributes.md

**Comment by albertskog** [comment]
My bad, a separate configuration error on my part made me think this was a bigger problem. Yes, it does work, but with yellow squiggles and a warning. Hovering over `cjtag` shows a popup saying "Value is not accepted. Valid values: "swd", "jtag"."

![image](https://user-images.githubusercontent.com/706444/155581173-27bd33f6-8fe9-4b7a-b0b2-e8d8cca51980.png)

![image](https://user-images.githubusercontent.com/706444/155581531-72cb4407-0a63-495f-b544-a967c46663f1.png)

![image](https://user-images.githubusercontent.com/706444/155581668-e0b90f0e-571e-4ec1-bb8f-8d2d89685410.png)

**Comment by haneefdm** [comment]
I can add `cjtag` in the next release. Wondering if this goes beyond JLink. We have half a dozen other probes/gdb-servers to check. Even for JLink, trouble is that it is not documented (not in Wiki or in Manual).
<img width="679" alt="image" src="https://user-images.githubusercontent.com/41269583/155585775-66254b45-654a-45c7-86b6-45e0d146960a.png">

For jlink it is simple to just pass it along but for others, there is some logic to convert to appropriate command-line options or other methods.

**Comment by albertskog** [comment]
Yes, it took me a while to figure out how to enable it! I have been going through today's browser history trying to figure out how I found it, only thing I can think of is that there is a drop-down menu for target interface in the GUI version, `JLinkGDBServerExe`. Could not make a screenshot while the menu was open, but the available options are:
* JTAG
* cJTAG
* SWD
* FINE
* ICSP

![image](https://user-images.githubusercontent.com/706444/155606005-ce6acc75-467d-48ea-8cc0-c3e66db82b83.png)

**Comment by albertskog** [comment]
I had a look at a couple of the other servers. If you want to trust their documentation is more up to date, I found this: 
## OpenOCD
https://openocd.org/doc-release/html/Debug-Adapter-Configuration.html#Transport-Configuration
Not sure are all relevant for debugging, but supports JTAG, SWD, SPI and SWIM

## PyOCD
https://pyocd.io/docs/options.html 

dap_protocol | str | 'default' | Wire protocol, either 'swd', 'jtag', or 'default'.
-- | -- | -- | --
