### ISSUE TITLE
target-async, an alias for mi-async, is deprecated

### ISSUE THREAD

**Issue by GitMensch** [Marus/cortex-debug#609]
When using GDB 11+ the user is prompted with a deprecation message:

~~~
Warning: 'set target-async', an alias for the command 'set mi-async', is deprecated.
Use 'set mi-async'.
~~~

It may be reasonable to either query the GDB version or execute this depending on a launch configuration option.

`set mi-async` is a GDB 7.8 feature (Released Jul 2014), which also comes with `-gdb-set mi-async` option.

README.MD "Requirements" doesn't specify a minimal GDB version this extension currently needs, not sure if older than GDB 7.8 is supported - if not it can be directly changed.

**Comment by haneefdm** [comment]
Good to know it was Jul 2014 when the new method was introduced.

Yes, older gdb's are still supported and used actively, unfortunately. I had migrated to newer way and had to revert back. Also, somewhere in gdb docs, I had read that this must be done before any other commands are issued.

Regardless, I have my own warning and change scheduled for July 2022
https://github.com/Marus/cortex-debug/blob/b8cb820f1b4bf010fbaf0743f24c38c809fbe490/src/backend/mi2/mi2.ts#L130

At this point, the minimum version will be documented and I can then delete some version-specific code as well.
