### ISSUE TITLE
No git tag for v1.2.2

### ISSUE THREAD

**Issue by michaeljones** [Marus/cortex-debug#615]
I hope you don't mind the issue. It is pretty minor but there is no git tag for v1.2.2 as far as I can tell and that is the currently released non-pre-release version. I guess it is from this commit: a720ebd55b742b289c5c33714c4610041bcd94c9 but it would be good to have a tag if you have a minute.

I'm getting some error in the extension (probably due to a configuration mistake on my part) and was hoping to debug it against a local checkout and wanted to match the tag.

**Comment by haneefdm** [comment]
sorry, I will try my best to tag every release
