### ISSUE TITLE
Feature request: wildcard executable path 

### ISSUE THREAD

**Issue by Felix1165** [Marus/cortex-debug#626]
Hi,

i have a project, where the output binary file must include the version number. 
With that, i have to edit the launch.json file for every version so the debugger knows where the executable file is.

Is there a way to have a wildcard for the path like "executable":"${workspaceRoot}/build/ProjectName_V*.elf" ?

Thanks in advance
Felix

**Comment by haneefdm** [comment]
Sorry, but there are many ways of accomplishing this without adding this to our extension and then deal with conflicts (multiple matches) and there is nothing worse than debugging the wrong exe. VSCode already has a few facilities that apply to lanch.json. Better yet, your build script could also generate the launch.json for you. You can create your own extension in the extreme.
