### ISSUE TITLE
`.cortex-debug` in `$HOME`

### ISSUE THREAD

**Issue by bartekpacia** [Marus/cortex-debug#637]
Is there some env variable that I can set to prevent `cortex-debug` from putting its config file in my `~`?

**Comment by haneefdm** [comment]
Absolutely it should not be doing anything in your home dir. What is the
name and contents of this file?

**Comment by bartekpacia** [comment]
```
$ cat ~/.cortex-debug
{"uuid":"e9e592ca-abe8-460a-a134-8c88a9e6c290"}
```

**Comment by haneefdm** [comment]
I never knew such a thing existed. You can disable this in the settings apparently

<img width="1029" alt="image" src="https://user-images.githubusercontent.com/41269583/163755468-a91a92f4-4943-4514-99ee-e1d0b78cfe94.png">
