### ISSUE TITLE
No horizontal scrolling in disassembly view

### ISSUE THREAD

**Issue by rododo-meow** [Marus/cortex-debug#638]
When the disassembled instruction is too long to be shown in one line (e.g. a branch instruction with a very long symbol name), the line is neither wrapped or horizontal scrollable.

**Comment by PhilippHaefele** [comment]
Hi @rododo-meow,

as the "new" disassembly view is supplied by VSCode, this extension is not able to change anything.

The VSCode guys already tried to fix this, but didn't found a working solution yet.

For more infos see following issue and stuff linked in to this issue:
https://github.com/microsoft/vscode/issues/130438

Best regards

Philipp

**Comment by haneefdm** [comment]
Yup, not much we can do here...
