### ISSUE TITLE
Simultaneous Disassembly and Source

### ISSUE THREAD

**Issue by stevenj** [Marus/cortex-debug#65]
If the Source window is open AND the disassembly window is open in a split view, it would be nice if they should both update when the source is stepped.  Currently it only updates one or the other.

**Comment by Marus** [comment]
I don't think this would be possible with the current VS Code debug protocol. With the protocol I don't explicitly make particular views active or control them myself, instead I tell VS Code what line the program is on, and it is responsible for displaying that section of code. Unfortunately this doesn't allow me to specify two simultaneous locations within the code, as under normal circumstances a single program location is not at two locations at once.

If something changes with the protocol in the future I will certainly look into this.

**Comment by stevenj** [comment]
No problem.  An interleaved assembly/source view would make this unnecessary anyway.  Off Topic, but, I would help out, but i am not sure how to develop and test vscode plugins from source.
