### ISSUE TITLE
[Rust] cannot set breakpoints

### ISSUE THREAD

**Issue by linfan68** [Marus/cortex-debug#665]
### setup
- Rust (from here: https://github.com/rust-embedded/cortex-m-quickstart)
- pyOCD as GDB server
- HC32L190 chip (Cortex-M0+)
- Cortex-Debug v1.5.1(pre-release)
 
### launch config: 
``` json
{
    "type": "cortex-debug",
    "request": "launch",
    "name": "Debug (pyOCD)",
    "servertype": "pyocd",
    "cwd": "${workspaceRoot}",
    "preLaunchTask": "Cargo Build (debug)",
    "runToEntryPoint": "main",
    "executable": "./target/thumbv6m-none-eabi/debug/hc32-test",
    "targetId": "HC32L190JCTA",
    "cmsisPack": "C:\\HW\\dk-hw\\src2\\soc\\hc32\\hc32l19x_ddl_Rev1.0.3\\HDSC.HC32L19X.1.0.0.pack",
    "showDevDebugOutput": "both"
}
```

### Problem
The setup was **working seamlessly for a while**. I can step through, set/remove breakpoints, view variables, and even with the SVD file I can view the peripheral registers.
But after some point (a few stop/start debug session) things stopped working:
- I can still start debug session, the code loaded to flash correctly.
- but execution does not stop on main, or any breakpoints.
- the code is not running, but the debug bar showing "running" state, with the pause button. And the pause button is not working.
- Setting breakpoints does not work at all. 

But at that moment, the GDB session is good. I can send GDB commands from the DEBUG CONSOLE.
`i b` returns "no breakpoints"
if I set breakpoint using the DEBUG CONSOLE `b main.rs:52`, breakpoints can be set successfully. and if I `c` on gdb, it actually breaks there, the UI shows current line and everything works well (stepping, call stack, watch values).

It seems like the plug-in does not recognized 'adding breakpoint', when toggling breakpoints, the DEBUG CONSOLE does not show any commands or output. Also, the peripherals window stopped working.

Also, another thing worth notice may be, I was using the "release" version of the plug-in, and it also worked for a short while. Then I switched to the pre-release version(1.5.1) and it also worked a few times.... But now switching plug-in version, reload vs code does not help at all.

**Comment by haneefdm** [comment]
* Can you try our latest pre-release. You can enable this in the Extensions panel in VSCode. You can always switch back
* Looks like you already enabled "showDevDebugOutput". Can you provide the stuff in the Debug Console? Setting it to "raw" will be more compact compared to "both". It is possible that VSCode (who manages the breakpoints) is not even sending us a request. If this  is the case, set "showDevDebugOutput" to "vscode" -- it will be super verbose.

**Comment by haneefdm** [comment]
No response? I will close the issue shortly
