### ISSUE TITLE
Can not load SVD file when start debugging

### ISSUE THREAD

**Issue by manadc0** [Marus/cortex-debug#681]
Hello,
The CORTEX PERIPHERALS tab usually can not show the list of register for MCU. I dont know why because sometime I can see it but almost SVD (xml) can not load
![image](https://user-images.githubusercontent.com/34482006/174464959-2bc1939e-b19d-432b-a8ca-46c6f2dc69a9.png)

My launch.json and xml
`
{
    "version": "0.2.0",

    "configurations": [
            {
            "cwd": "${workspaceRoot}",
            "executable": "./armgcc/debug/gpio_led_output.elf",
            "name": "Debug JLink",
            "request": "launch",
            "type": "cortex-debug",
            "serverpath": "C:/Program Files/SEGGER/JLink/JLinkGDBServerCL.exe",
            "servertype": "jlink",
            "armToolchainPath": "C:/Compiler/gcc-arm-none-eabi-10.3-2021.10-win32/bin",
            "runToMain": true,
            "svdFile": "./MK64F12.xml",
            "device": "MK64FN1M0VLL12",
            "interface": "swd",
        }
    ]
}
`
[MK64F12.zip](https://github.com/Marus/cortex-debug/files/8934726/MK64F12.zip)

**Comment by haneefdm** [comment]
Please try version 1.5.x (available in VSCode as a pre-release in the extensions section).

**Comment by manadc0** [comment]
> Please try version 1.5.x (available in VSCode as a pre-release in the extensions section).

Yeah, It was fixed with pre-release. Thank you!
