### ISSUE TITLE
cortex-debug won't start with VS Code 1.68.1 on Ubuntu 22.04

### ISSUE THREAD

**Issue by SrivamsiMalladi** [Marus/cortex-debug#682]
I am unable to use cortex-debug in VS Code. When I try to launch the debugger, it starts and stops shortly with the following output in 'Debug Console' of VS Code.

```
Reading symbols from /usr/bin/arm-none-eabi-objdump --syms -C -h -w /home/iotdev/work/temp_proj/build/temp_proj.elf
Reading symbols from /usr/bin/arm-none-eabi-nm --defined-only -S -l -C -p /home/iotdev/work/temp_proj/build/temp_proj.elf
Launching GDB: /usr/bin/arm-none-eabi-gdb -q --interpreter=mi2 /home/iotdev/work/temp_proj/build/temp_proj.elf
1-gdb-set target-async on
```
I am very new to cortex-debug. I am not sure if there is a separate file for debug log.

**Environment:**
Cortex-Debug v1.4.4
VSCode Version 1.68.1
Ubuntu 22.04 LTS
SEGGER Jlink Pro

**Comment by haneefdm** [comment]
You have a bad gdb install. Try running gdb from command-line

**Comment by cpoole** [comment]
Older arm toolchains rely on lib-curses 5. 22.04 has upgraded so the .so is missing

```
sudo add-apt-repository universe
sudo apt-get install libncurses5
```
