### ISSUE TITLE
SVD Loading Does not work from 1.4.2+

### ISSUE THREAD

**Issue by bssc2g** [Marus/cortex-debug#683]
Environment:
- Using VSCode 1.68.1 (latest as of writing)
- Cortex-debug versions 1.4.2 and later exhibit this bug
- Target device NRF52840

Description:
Prior to 1.4.2, SVD files are loaded as expected, and the peripherals are listed in the peripheral pane. As of 1.4.2 and later, 
SVD files do not get loaded properly, and the peripheral list is not shown. Instead, the peripheral pane has the message
"SVD: No active debug sessions or no SVD files specified"

In all test cases, the same launch.json configuration is used, and the svd file is specified using the "svdFile" entry in the configuration. In my case, this references a local svd file. 

Steps to reproduce: 
Use cortex-debug 1.4.2 or later, and latest VSCode (1.68.1)
Create a debug configuration and specify the svd file manually. Launch debug session and observe that the peripheral pane does not populate.

**Comment by haneefdm** [comment]
1.5.X pre-release hopefully fixes the issue. Please try that, It is available from the VSCode Extensions, but you have to enable pre-releases, which btw, will help everyone in our community.

Closing this issue unless the latest pre-release doesn't fix it.
