### ISSUE TITLE
Run the main function directly by set the pc register to the main function addr

### ISSUE THREAD

**Issue by XinyuKhan** [Marus/cortex-debug#696]
I don't know if this feature is supported. Sometimes I need the debugger to bypass the bootloader and run the main function directly but not just wait the breakpoint, because the downloading operation usually broken the check mechanism in the bootloader or the bootloader may just not exist.

**Comment by haneefdm** [comment]
Yes, people do that. But you better know your processor, the gdb-server (JLink, openocd, etc.), etc.

There are all kinds of `override...`s available in launch.json.

See https://github.com/Marus/cortex-debug/blob/master/debug_attributes.md

**Comment by XinyuKhan** [comment]
Thx for the rely. I'll do more research

**Comment by XinyuKhan** [comment]
> Yes, people do that. But you better know your processor, the gdb-server (JLink, openocd, etc.), etc.
> 
> There are all kinds of `override...`s available in launch.json.
> 
> See https://github.com/Marus/cortex-debug/blob/master/debug_attributes.md

I can set PC reg by override the pre launch command, but as know I have to set the main address to the command manually, Is there any way that can automatically get the address of the main entry and set it to the pc reg? If there is not, It's possible to and such feature in the future? The stm32cubeide support this feature accroding its log.
<img width="380" alt="企业微信截图_3b6d1359-308b-4027-a9a3-094bc43819fc" src="https://user-images.githubusercontent.com/39960727/178418995-f0888b86-d59b-46f9-a10e-034b0f764133.png">

**Comment by haneefdm** [comment]
> is there any way that can automatically get the address of the main entry

Probably. You also have to be a gdb expert. Try one of the following
```
set $pc = main
set $pc = &main
```
in your overrideLaunchCommands. Don't do it in 'preLaunc..."

Note that for most ARM processors, you also have to set $sp and $lr, or your stack will be bogus. $lr should be -1

It will help if you read our Wiki https://github.com/Marus/cortex-debug/wiki/Cortex-Debug:-Under-the-hood to see in detail our startup sequence.

**Comment by selectstriker2** [comment]
Rather than jumping straight to `main`, you might be better off jumping to your reset vector, which should be the first address in the image, something like `__reset_handler`. That will set up your stack pointer(s) and link register, initialize .bss region to 0, copy any read only data to RAM, etc. before entering `main()`

**Comment by XinyuKhan** [comment]
> > is there any way that can automatically get the address of the main entry
> 
> Probably. You also have to be a gdb expert. Try one of the following
> 
> ```
> set $pc = main
> set $pc = &main
> ```
> 
> in your overrideLaunchCommands. Don't do it in 'preLaunc..."
> 
> Note that for most ARM processors, you also have to set $sp and $lr, or your stack will be bogus. $lr should be -1
> 
> It will help if you read our Wiki https://github.com/Marus/cortex-debug/wiki/Cortex-Debug:-Under-the-hood to see in detail our startup sequence.

Great! I will try your sugestion latter. Thank you so mush for your reply!
