### ISSUE TITLE
Debugginng with two elf files

### ISSUE THREAD

**Issue by vitoller** [Marus/cortex-debug#698]
Hello,

I am facing the problem, that I would like to load two elf files (bootloader and application).

Whowever, I can not get to use loadFiles (or symbolFiles) to work. At the moment I suspect, that it has to do with the path substitution on Windows

- VS Code on Windows
- Cortex-Debug v1.5.1-pre5

launch.json - extract:
>  "loadFiles": [
>      "some/path/A/B\\C"
>  ],

console output:

> Failed to launch GDB: C:/sw/<snip>**buildsomepathABC**: No such file or directory. (from file-exec-file "C:/sw<snip>\build\some\path\A\B\C")

**Note:** see how the "\\" disapear from the path. 

I tried everything I could think of, but could not get it to work. How do I load "loadFiles"?

Thank you

**Comment by haneefdm** [comment]
Thank you for reporting this. Will try to fix ASAP. Yes, GDB does not like `\` and we should have translated the slashes.

**Comment by PhilippHaefele** [comment]
I have already fixed that locally (at least for executable) and it seems to be an issue with the replace function not replacing the first "/". Needed to do it via a split and recombine the result with "\".
Should i do a MR tomorrow?

**Comment by haneefdm** [comment]
No. We should use replace properly. It should have been str.replace(/\\/g,, '/'); -- or, javascript will only replace the first occurrence.

I already made the edits. It was in other places too.

**Comment by haneefdm** [comment]
Could you try the latest pre-release?
<img width="524" alt="image" src="https://user-images.githubusercontent.com/41269583/180616423-560e397d-9250-44a5-a7ac-ce057f3a355a.png">

**Comment by haneefdm** [comment]
Please report back if you are still seeing issues

**Comment by vitoller** [comment]
Thank you, it does work now.

I could not find it in the documentation, and it would have helped me.
Here the section for "loadFiles" and "symbolFiles" I use in "**launch.json**"

```
            "loadFiles": [
                "${workspaceRoot}/project/Firmware.elf",
                "${workspaceRoot}/project/Bootloader.elf"
            ],
            "symbolFiles": [
                {
                        "file": "${workspaceRoot}/project/Bootloader.elf"
                }, {
                        "file": "${workspaceRoot}/project/Firmware.elf"
                }
            ],
```
