### ISSUE TITLE
FreeRTOS: no strack trace for (some) sleeping tasks

### ISSUE THREAD

**Issue by diggit** [Marus/cortex-debug#724]
Hi,
RTOS panel works and displays stack usage of tasks and other stats.

![image](https://user-images.githubusercontent.com/512025/186651808-2964a5c6-3f38-45c7-a581-1388a0bae14c.png)

Unfortunately paused(blocked) tasks mostly shows just empty call stack.

![image](https://user-images.githubusercontent.com/512025/186651539-5849c38b-386b-4aab-8dd7-24adb7086e56.png)

AN task is definitely started and now it's blocked on something (most probably sleep).

I am using static initialization of tasks (task stacks are statically allocated).

My setup:
- Host OS: Windows 10
- Cortex debug: 1.60
- Jlink :7.64
- gdb: from Arm arm-none-eabi toolchain 11.2.1 for Windows
- FreeRTOS: 10.4.6

**Comment by haneefdm** [comment]
The best you can do is to look in the gdb-server TERMINAL window for information. You can enable JLink debug options (command-line option perhaps to enable logging or verbose output) I don't think the gdb server gives the entire stack info. Just the stack pointers and names and the active thread. GDB can figure out from there based on the registers saved for each stack-pointers for the non-active threads. It then follows the link register until it goes to the end of each thread. Which registers are saved is ABI dependent and ARM has one that everyone has to follow.

It is possible it is the RTOS that is terminating the stack. Could these tasks be pre-empted/blocked in an ISR?

The stack is terminated by setting the LR to -1 (0xffffffff). LR is one of the saved registers. The PC shown for all the threads with no stack info seems to be @ 0x0 which should not be possible but that is what the gdb-server is reporting. Note that this is the saved PC for non-active stacks.

I don't know if this is helpful.
