### ISSUE TITLE
Can’t get variables values in Rust

### ISSUE THREAD

**Issue by pwnorbitals** [Marus/cortex-debug#727]
The "variables" and "watch" panels are always empty when trying to debug Rust code, I can’t get them to work... Adding watch values always result in a `not available` value

**Comment by haneefdm** [comment]
Are you compiling/debugging with optimizations turned off and symbols saved? If not, you will see nothing. By default gcc does not for C/CPP programs unless you use the -g flag and hopefully -O0 or -Og. Maybe something similar for Rust.

Btw, the watch window is always empty until you add something to it but no symbols means you cannot add anything. We get the local variables from gdb. If gdb does not see any variables, then there are likely no symbols in your executable. You use a tool like `nm` to check (we also use the same tool).

**Comment by haneefdm** [comment]
<img width="740" alt="image" src="https://user-images.githubusercontent.com/41269583/186918950-f2654b85-72b0-4afb-9dee-c7a930ba09e4.png">

https://doc.rust-lang.org/rustc/codegen-options/index.html#debuginfo

<img width="715" alt="image" src="https://user-images.githubusercontent.com/41269583/186919104-f6f055fe-9780-45da-9fcb-ff24956f9f3f.png">

https://doc.rust-lang.org/rustc/codegen-options/index.html#opt-level

Use opt-level=0 and dbginfo=2 and make sure you do use such flags while linking as well. A lot of people forget you have to do that during the linking step as well.
