### ISSUE TITLE
Toggle Activate Breakpoint does not enable all breakpoints for multi-core debugging in some cases

### ISSUE THREAD

**Issue by comeback0** [Marus/cortex-debug#730]
Breakpoints of the random core don't work correctly after Deactivate/Activate in the VSCode IDE

Assume we start multi-core debug session and set two breakpoint on each core. When both cores are halted, you can easily disable/enable breakpoints (with using **Toggle Activate Breakpoint** button) on both cores without breaking anything. Once someone is trying to enable breakpoints set on both cores which are running, some breakpoint(s) remain grayed-out.

GDB communication shows that VSCode/Cortex-Debug resume cores before all breakpoints are actually being set.
Here is GDB shrank [log](https://github.com/Marus/cortex-debug/files/9446103/vscode_breakpoints.txt) showing what happens when **Toggle Activate Breakpoint** button is pressed on running cores:
_56-exec-interrupt
57-break-insert
58-exec-continue --all
59-break-insert_

**Comment by haneefdm** [comment]
First, I apologize. Submitted late Aug and I and seeing this just now.

There have been some fixes in this area (messing with breakpoints while running) over the past few months. Can you confirm that this is still happening?

There may also be a UI issue in VSCode where if you have a shared file and the setting of the breakpoint succeeds in one and failed in another. I don't think VSCode is sophisticated enough to know the difference.
