### ISSUE TITLE
configuration: bad type for SymboleFiles?

### ISSUE THREAD

**Issue by Lefix2** [Marus/cortex-debug#733]
https://github.com/Marus/cortex-debug/blob/50cb7c48e778219d499f739a77ec7cbf20d78a44/src/common.ts#L256

I'm not quite sure of this report.
Since i'm trying to debug an application split into multiple elf files, i tried to use "symbolFiles" instead of "executable".
But when specifying path to my elf files, i'm getting the error "Incorrect type. Expected "object".

Should this line be:
```symbolFiles: string[];```
instead?

**Comment by haneefdm** [comment]
You are not using IntelliSense properly. An object means you put stuff inside `{}`. JSON format. You start typing and you will get help. Just type one double quote and you will get a completion that is appropriate for where your cursor is.

I wish. No, it is not a simple array of strings. Lot more to it. See package.json and the definition of SymbolFile

```typescript
export interface SymbolFile {
    file: string;
    offset?: number;
    textaddress?: number;
    sections: ElfSection[];
    sectionMap: {[name: string]: ElfSection};
}
```

[If you look in package.json](https://github.com/Marus/cortex-debug/blob/1fdef12b6cd84d50a10cfaf2e727be8548ae7388/package.json#L706), you will see the same structure duplicated. Only `file` is required. But others have other needs. For relocating functions/data

Before you do anything, I suggest you find out how it can be done via gdb. Then worry about automating it. If you miss step 1, then it is all for nothing.

Please close this, if you have what you need.

**Comment by Lefix2** [comment]
Oh i was looking for the type description but couldn't find the file you mentioned, thanks for the explanation.

**Comment by haneefdm** [comment]
In VSCode, you can right-click and ask to go to definition. Rabbit hole for sure :-) Kinda hard to do on the Web.

**Comment by Lefix2** [comment]
I was on github web view, I've just downloaded the project and reading a bit more of it! Thank for the tips
