### ISSUE TITLE
Once you disassemble once, the disassembly is queued in subsequent debug sessions until vscode restart

### ISSUE THREAD

**Issue by bssc2g** [Marus/cortex-debug#746]
If you start a debug session, then use "Open Disassembly View", it works as expected. However, if you terminate and restart the debug session, it seems that the backend still requests disassembly from gdb, even if you close the disassembly view. This can really slow down the startup of a debug session, since you have to load all the symbols and then do the disassembly before the UI becomes responsive. 

I've only been able to fix this by restarting vscode. Perhaps some sort of setting/gdb command cache?

**Comment by haneefdm** [comment]
Lifecycle management is done by VSCode. Everytime you terminate a session, VSCode terminates our process and starts a new one for a new session and there is no state/memory of the previous sessions.

I remember if you manually remove the disassembly view, VSCode stops making disassembly requests but it takes a while -- one or two restarts without the disassembly window visible. I can't remember now.

You can see the transactions if you set `"showDevDebugOutput": "vscode"`. We do not make a request from gdb unless we get a request from the frontend VSCod3.

You should report this to VSCode proper
