### ISSUE TITLE
Add armToolchainPath entry for launch configuration to documentation

### ISSUE THREAD

**Issue by twoodrow** [Marus/cortex-debug#76]
Hey there,

I encountered undocumented errors when attempting to debug. Eventually, I encountered "armToolchainPath" entry in launch configuration which fixed my issue.

Is there a place I can add this to the documentation? Are pull requests welcome?

Thanks!

**Comment by PhilippHaefele** [comment]
I think the new main page in the wiki (thanks to @haneefdm & @duaneellissd) does explain that very well now.

see https://github.com/Marus/cortex-debug/wiki

@haneefdm Please close this issue
