### ISSUE TITLE
Unspecified Cortex-A support

### ISSUE THREAD

**Issue by joleeee** [Marus/cortex-debug#760]
The name is cortex-debug, but in the description it's stated it's for "Cortex-M Microcontrollers". What's the incompatibilities with Cortex-A, or -R? Seems to work for me :) Would be nice with some clarification in the README perhaps?

**Comment by haneefdm** [comment]
There may not be any issues other than 64-bit value printing here and there. Registers are okay, I think. We never tested our extension with an A class. R devices should work. The reason the README is empty is that we never tried it and I don't own any suitable HW.

People are even using this extension with RISC-V, Xtensa, etc.

Try it and submit any serious issues. We will either fix it or add it to the README.

There is one issue with 64-bit addresses. In disassembly, we print addresses and they are 32-bit.
