### ISSUE TITLE
Cortex Peripherals pane unreliable if gaps in register layout

### ISSUE THREAD

**Issue by Norm369** [Marus/cortex-debug#764]
Using Cortex-debug 1.6.4 (on iMX RT1172) I notice that if you try to display some peripheral registers and there is a gap in the registers (eg. in the example no register at 0x40070008) then gdb server reports a warning trying to read that memory and the peripherals pane shows all subsequent registers to be zeroed. In my example I read the ERQ register explicitly in the Watch pane and its value is 0x10001, yet in the peripherals pane it shows up as 0. This happens on lots of other peripherals too.
![VSCodePeriphViewProb](https://user-images.githubusercontent.com/116049979/197686039-5d7b46c8-07c0-4658-bed8-388dc620a09d.jpg)

**Comment by haneefdm** [comment]
This only happens for some chips. We read in bulk including small gaps. Reading one reg at a time is slow as molasses. You can use `svdAddrGapThreshold` and see if that helps. Most devices allow the entire address range specified by the peripheral itself. This should really be addressed by NXP if they want a good experience for their customers.

https://github.com/Marus/cortex-debug/blob/master/debug_attributes.md

Btw, there is now another SVD viewer that works with our debugger.

https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-embedded-tools
