### ISSUE TITLE
Cannot find pico-debug on Ubuntu, but it works on windows (pyocd 0.34.2)

### ISSUE THREAD

**Issue by Krensi** [Marus/cortex-debug#770]
Hi pyOCD team! 

I try to connect pyOCD to the raspberry pi pico-debug DAP adapter (https://github.com/majbthrd/pico-debug). When running  `pyocd list` the debug probe shows up on Windows. However, it does not show up running the same command on Ubuntu. 

I added the vendor/product ID to udev rules by copying the files as recommended. Afterwards I added the vendor/product ID of pico-debug to the CMSIS-DAP rules file.
Do you know what I am doing wrong, or has anybody else the same issue?

**Comment by haneefdm** [comment]
Sorry, this is not the pyOCD team. That would be https://github.com/pyocd/pyOCD

Please close this issue
