### ISSUE TITLE
Unable to parse SVD 

### ISSUE THREAD

**Issue by Gau54454d50** [Marus/cortex-debug#771]
"device":stm32g071"
Unable to parse SVD file /home/name/gpioproj/ON_OFF/STM32G071.svd: Error: Attribute without value Line: 15 Column: 76 Char: >
Cortext peripheral is giving me this error.
I am using SVD file file from [https://github.com/posborne/cmsis-svd/tree/master/data/STMicro](https://github.com/Marus/cortex-debug-db-stm32f4/issues/url)

**Comment by haneefdm** [comment]
The link you posted is broken. Can you make sure the link and actual file name is correct.

Or, compress and attach the file here.

**Comment by haneefdm** [comment]
I am going to close this soon. Please provide the compressed SVD file for us to look at.
