### ISSUE TITLE
The extension is still disassembling after closing the disassembly window

### ISSUE THREAD

**Issue by hongshui3000** [Marus/cortex-debug#781]
After closing the disassembly window, the extension plug-in is still disassembling, even if it is reconnected, it will continue to disassemble. You can only stop disassembly by restarting vscode

**Comment by haneefdm** [comment]
We don't disassemble unless VSCode asks for it and we have no relationship with the lifecycle of the disassembly window. I think I have told you this before.

You should file this issue with the main VSCode repo.
