### ISSUE TITLE
JLink debugging not working

### ISSUE THREAD

**Issue by JoshuaYonathan** [Marus/cortex-debug#785]
Cortex-Debug v-1.6.7
ARM GNU Toolchain 12.2.MPACBTI-Bet1
JLink v-7.82d

The JLink server appears and says "Waiting for GDB connection...". After ~5 seconds it times out. Debug console and terminal logs attached. The JLink server and GDB works when I run it manually in the terminal but not using the same arguments cortex-debug uses.

**I am using the ST-Link v2 -> JLink firmware provided by SEGGER for compatibility with the ST-Link hardware on my evaluation board.

This has worked in the past with v-1.4.4 of Cortex-Debug but it no longer does. I will try with another version of the ARM GNU Toolchain and see if that is the issue.

[debug_console.txt](https://github.com/Marus/cortex-debug/files/10147864/debug_console.txt)
[terminal.txt](https://github.com/Marus/cortex-debug/files/10147865/terminal.txt)

**Comment by JoshuaYonathan** [comment]
Using the ARM GNU Toolchain v-11.3 with Cortex-Debug v-1.4.4 will work correctly. Using the latest version of cortex-debug with this version of the arm gnu toolchain will not work with the same issue I reported above. Using v-12.2 of the arm toolchain will not work with cortex-debug v-1.4.4, it hangs forever when I press the "play" button.

**Comment by haneefdm** [comment]
Wrong JLink gdb server. Try JLinkGDBServerCL.exe

You are using the graphical version that is not meant to be used from command-line

**Comment by haneefdm** [comment]
You should see a lot more information the terminal window....where JLink is running.

**Comment by JoshuaYonathan** [comment]
> 

This fixed it for me, thanks.
