### ISSUE TITLE
"console" argument in "launch.json"

### ISSUE THREAD

**Issue by blueted2** [Marus/cortex-debug#789]
Are there any plans to support the "console" launch argument to enable running gdb in an external console ?

**Comment by haneefdm** [comment]
No. GDB will always run in the Debug Console. That is the VSCode way. In this console, you can issue gdb commands

I C/C++ cpptools extension (and other extensions that run programs on your PC), they have the option to use an externalConsole and that is for the debuggee. Not gdb. Embedded programs are typically not interactive or have consoles. They may use things like UART which you can certainly monitor within VSCode or externally. There is also self-hosting and this can be used in the 'TERMINAL' window for the GDB server.
