### ISSUE TITLE
Error: init mode failed (unable to connect to the target)

### ISSUE THREAD

**Issue by lievenFlux** [Marus/cortex-debug#791]
hello, last week i was trying out cortex-debug with a custom stm32 board and a stlink v2 isol programmer. i was able to get it working for the first time and saw some values of variables of the program. however when i stepped through the breakpoints it hangs and saw the programer working for more then 15 minutes so i decided to close the connection. 
after that i can no longer connect to any of my stm32 boards.

```
Info : auto-selecting first available session transport "hla_swd". To override use 'transport select <transport>'.
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
Info : clock speed 2000 kHz
Info : STLINK V2J40S7 (API v2) VID:PID 0483:3748
Info : Target voltage: 3.409612
Error: init mode failed (unable to connect to the target)


make: *** [upload_combo_jtag] Error 1
```

i have googled this error and tried to use a stm utility with connect under reset but that didn't work.
these are the configurations:

launch.json
```
{
  "version": "0.0.1",
  "projectName": "lst_sampler",
  "configurations": [
    {
      "name": "STlink attach",
      "cwd": "${workspaceRoot}",
      "executable": "${workspaceRoot}/build/lst_sampler/lst_sampler.elf",
      "request": "attach",
      "type": "cortex-debug",
      "servertype": "stutil",
      "device": "STM32F405RGT6",
      "interface": "jtag",
      //"runToMain": true, 
      "preLaunchTask": "Build all",
      // "preLaunchCommands": ["Build all"], 
      "svdFile": "", 
      "swoConfig": {}
    }
  ]
}
```
settings.json
```
{
  "cortex-debug.gdbPath": "/opt/homebrew/bin/arm-none-eabi-gdb",
  "cortex-debug.stutilPath": "/opt/homebrew/bin/st-util",
  "cortex-debug.armToolchainPath": "/opt/homebrew/bin/"
}
```

any idea what happened or how to resolve this ?

**Comment by haneefdm** [comment]
This is way beyond our expertise. We use STLink gdb server and it does what it does. You can see the full command line used in the Debug Console. I would run it from the command line in the directory where the server lives and see if you can make that work. Reads its docs. Your best option is to contact ST.

**Comment by lievenFlux** [comment]
ok thanks for your answer. will try what you suggest. i'll close this.

**Comment by haneefdm** [comment]
Also, I would try ST's official gdb-server. `stutil` is not the official one.
