### ISSUE TITLE
XRTOS with uC/OS-II does not display task names

### ISSUE THREAD

**Issue by CIPop** [Marus/cortex-debug#798]
The following code will set the task name:

```C
  OSTaskNameSet(OSPrioCur, (INT8U*)"StartupTask()", &err);
```

The XRTOS viewer will display "???":
<img width="1265" alt="Screenshot 2023-01-07 at 7 12 24 PM" src="https://user-images.githubusercontent.com/8635911/211178843-72d5b714-5213-4159-bb2d-80166d2dcfcb.png">

OS Task name can still be obtained exploring the TCB listed by XRTOS:

<img width="373" alt="Screenshot 2023-01-07 at 7 13 54 PM" src="https://user-images.githubusercontent.com/8635911/211178871-2bc006d8-c928-4171-a9b7-2281d3e9ad53.png">

**Comment by PhilippHaefele** [comment]
Thanks for reporting the issue. Please note that the development of the RTOS View has moved to https://github.com/mcu-debug/rtos-views

I will have a look into this. Would be nice if you can supply your `os_cfg.h` file here, so i can better reproduce the issue.

Thanks

**Comment by PhilippHaefele** [comment]
Got it reproduced. Missed one expression when porting over to `mcu-debug/rtos-views`

**Comment by CIPop** [comment]
Thank you @PhilippHaefele ! That was very fast :).

**Comment by PhilippHaefele** [comment]
No problem and thanks to @haneefdm a released version 0.0.3 is already available from the marketplace. Have fun 👨‍💻
