### ISSUE TITLE
How to display RAM and Flash usage during debugging?

### ISSUE THREAD

**Issue by MarioPL98** [Marus/cortex-debug#801]
Hello. How do I check how much ram do my variables use and how much flash space the code takes? I'm looking for something similar to this:
![image](https://user-images.githubusercontent.com/16231640/211954721-776272ad-2cf2-4868-b057-dbdf0d1154f7.png)
This is a screenshot from STM32CubeIde showing Build Analyzer.

**Comment by haneefdm** [comment]
This has nothing to with our debugger. Your compiler/linker is supposed to give you those stats. Note where the info is presented -- "Build Analyzer". We are not a build tool

We have no idea what memories you have, how many, internal, external. Zero information. This info is in the Elf file but not straight forward to look at and you can probably use one of the elf tools to get the same info (look for Elf sections).
