### ISSUE TITLE
In SVD viewer, the "Refresh" button updates the registers of only one peripheral in which the cursor is located

### ISSUE THREAD

**Issue by AndreySmirnov81** [Marus/cortex-debug#803]
![Снимок экрана 2023-01-17 104837](https://user-images.githubusercontent.com/19325847/212839283-f9b7fb29-71d6-4951-8d5b-7bcb41c0a740.png)

**Comment by thegecko** [comment]
@AndreySmirnov81 would you expect this refresh command to refresh all peripheral values or just the expanded ones?

**Comment by AndreySmirnov81** [comment]
@thegecko
Only expanded.

**Comment by AndreySmirnov81** [comment]
It would be nice if there was a "collapse all" button.

**Comment by haneefdm** [comment]
> would you expect this refresh command to refresh all peripheral values

That would totally stall the debugger. We could be talking several megabytes of transfers. We should just refresh whatever is expanded.

**Comment by AndreySmirnov81** [comment]
> @thegecko Only expanded.

Similar to how it is done for `Pause`

![изображение](https://user-images.githubusercontent.com/19325847/215803660-55377e1a-0972-4b6d-958b-225a29167214.png)

**Comment by haneefdm** [comment]
> Similar to how it is done for Pause

Yes

**Comment by thegecko** [comment]
> Similar to how it is done for Pause

Please see #813. There is a subtle difference between the pause (stopped) state of debug and the "global" refresh in that the refresh would act upon all running sessions rather than the one which paused (stopped).

**Comment by haneefdm** [comment]
From a user point of view, it will appear like what happens when you Pause a session.
