### ISSUE TITLE
The SVD viewer performs unnecessary reading of registers when expanding the display of register fields

### ISSUE THREAD

**Issue by AndreySmirnov81** [Marus/cortex-debug#805]
1. When expanding the display of register fields, an unnecessary reading of ALL registers of given peripheral is performed.
2. I think that when expanding the display of register fields, reading should not be performed at all, since the register value is already known and displayed.
![изображение](https://user-images.githubusercontent.com/19325847/212847453-8fe25c87-85da-4ee0-9fc0-02402497ab4e.png)

**Comment by haneefdm** [comment]
Addressed in https://github.com/mcu-debug/svd-viewer
