### ISSUE TITLE
XRTOS keeps turning on after restarting vscode

### ISSUE THREAD

**Issue by itzandroidtab** [Marus/cortex-debug#811]
After turning off the XRTOS view in the command window it turns itself back on after a restart of vscode.

**Comment by haneefdm** [comment]
This issue belongs in the https://github.com/mcu-debug/rtos-views repo.

Can you please create this issue over there?

But, how are you turning off the XRTOS view? There should have been a setting to remember your preference. But there is a command in the Command Palette. Could you please try that as a workaround?

<img width="600" alt="image" src="https://user-images.githubusercontent.com/41269583/214620661-740ee373-84f2-4ed9-b369-73e44fb6ba7f.png">

**Comment by itzandroidtab** [comment]
@haneefdm Thank you for your response. I will create a issue in rtos-views.

That is also the only way I was able to turn it off. But every time it will turn back on
https://youtu.be/jFtUWc5dhno
