### ISSUE TITLE
SVD viewer: missing and unnecessary `Copy Value` buttons for register fields

### ISSUE THREAD

**Issue by AndreySmirnov81** [Marus/cortex-debug#812]
Missing for `read-only`:
![изображение](https://user-images.githubusercontent.com/19325847/215784347-b3da5780-0a17-4e4f-a4c3-8c893daa4c08.png)

Unnecessary for `write-only`:
![изображение](https://user-images.githubusercontent.com/19325847/215784651-14c0b7f9-a4e6-436f-87e0-22fd6ad3d47b.png)

OK for `read-write`:
![изображение](https://user-images.githubusercontent.com/19325847/215785475-97ef8f81-c761-4152-a0b3-9056b9a8de67.png)

**Comment by haneefdm** [comment]
This issue has been addressed in https://github.com/mcu-debug/svd-viewer

That will be the new home of SVD and will be removed from this repo when appropriate.

**Comment by AndreySmirnov81** [comment]
Thanks!

@haneefdm please look at the following comment:
https://github.com/mcu-debug/svd-viewer/commit/199e26eef71dbaeff1c06028506e851787feb51d#r100383410
