### ISSUE TITLE
Better look of the Reset buttom

### ISSUE THREAD

**Issue by Eplankton** [Marus/cortex-debug#828]
Well....It appears that the current icon of `reset` doesn't render well on my screen, and it looks just blur, I suggest some svg to replace it.
They're lightning-like, for example:
![bolt-thunder-svgrepo-com](https://user-images.githubusercontent.com/86543401/219866769-4e03ea6d-595a-4302-81a5-7b274f94fc15.svg)
![lightning-svgrepo-com (1)](https://user-images.githubusercontent.com/86543401/219866775-db4fcc44-4b5c-4a57-97cb-a9e2fe9543df.svg)
![kdisknav](https://user-images.githubusercontent.com/86543401/219866778-b94ba796-9250-4e4b-b66f-c1c0d7a8b37c.svg)

**Comment by haneefdm** [comment]
Thank you for taking the time. Not sure what theme you are using but in general I thought the existing one looked okay and maybe not the best for light themes. Btw, our Reset icon is already an SVG. I do want to stick with the conventions and guidelines from Microsoft/VSCode. I want it to resemble something like a power/restart/reset button. Here is my attempt at it in various themes. I started with the SVG that VSCode had for the Restart button. When using SVG, the light/dark modes don't work well unless you supply an icon for each. It takes some work to create one icon that works for all themes.

Abyss
<img width="214" alt="image" src="https://user-images.githubusercontent.com/41269583/219878662-f4876c8d-22c0-40c0-b5fe-ac4f71077f10.png">

Dark+ (default)
<img width="214" alt="image" src="https://user-images.githubusercontent.com/41269583/219878645-e3c2e3fd-27e2-454a-b3da-20818b5c21d2.png">

Light+ (default)
<img width="214" alt="image" src="https://user-images.githubusercontent.com/41269583/219878623-3ffc4c9b-6a57-4d48-a5a5-e10e01a8411b.png">

**Comment by haneefdm** [comment]
Btw, you can experiment with SVGs yourself with various themes by replacing the file

~/.vscode/extensions/marus25.cortex-debug-X.Y.Z/images/reset.svg

or you can perhaps edit 

~/.vscode/extensions/marus25.cortex-debug-X.Y.Z/package.json

**Comment by haneefdm** [comment]
Here are the two SVG files, if someone wants to tweak them.

![reset-dark](https://user-images.githubusercontent.com/41269583/219882692-e16c9d9a-e6bc-4fe7-a9cd-e465a3b69d50.svg)

![reset-light](https://user-images.githubusercontent.com/41269583/219882693-fd26ed9f-7200-428d-aa51-ac8a9218be18.svg)

And, here is the MS one for the built-in restart
![restart](https://user-images.githubusercontent.com/41269583/219882767-7250055b-a99b-46a1-8b34-c0ce9430690a.svg)

And, my package.json looks like this now
```JSON
            {
                "command": "cortex-debug.resetDevice",
                "title": "Reset device",
                "icon": {
                    "dark": "images/reset-dark.svg",
                    "light": "images/reset-light.svg"
                }
            },
```

**Comment by selectstriker2** [comment]
I think the reset icon looks just fine, and a I'm not sure that a lightning bolt makes sense in that context. It is interesting to know that the icons are tweakable though.

**Comment by Eplankton** [comment]
> 这是两个 SVG 文件，如果有人想调整它们的话。
> 
> ![重置-暗](https://user-images.githubusercontent.com/41269583/219882692-e16c9d9a-e6bc-4fe7-a9cd-e465a3b69d50.svg)
> 
> ![重置-亮](https://user-images.githubusercontent.com/41269583/219882693-fd26ed9f-7200-428d-aa51-ac8a9218be18.svg)
> 
> 而且，这是用于内置重启的 MS ![重启](https://user-images.githubusercontent.com/41269583/219882767-7250055b-a99b-46a1-8b34-c0ce9430690a.svg)
> 
> 而且，我的 package.json 现在看起来像这样
> 
> ```json
>             {
>                 "command": "cortex-debug.resetDevice",
>                 "title": "Reset device",
>                 "icon": {
>                     "dark": "images/reset-dark.svg",
>                     "light": "images/reset-light.svg"
>                 }
>             },
> ```

Thanks, I shall replace it by myself, and it just looks awesome.

**Comment by PhilippHaefele** [comment]
@haneefdm Just for clarification. Are you planning to replace the icon by the one(s) you showed above?

I like them more than the current one as it is more clear that it is a kind of reset

**Comment by Eplankton** [comment]
> @haneefdm Just for clarification. Are you planning to replace the icon by the one(s) you showed above?
> 
> I like them more than the current one as it is more clear that it is a kind of reset

Oh, sorry...I don't mean that. I just replace the icon on my OWN pc since the developer has told me where the file is, nothing else.

**Comment by haneefdm** [comment]
@PhilippHaefele Yes, I will replace the Reset button in the next release. As you can see, they work much better for various themes and looks more like a Reset. I found the SVG for the MS Restart, now that MS published all of their icons.

I am going to close this
