### ISSUE TITLE
Unable to read variables during 2nd breakpoint stop

### ISSUE THREAD

**Issue by tdjastrzebski** [Marus/cortex-debug#831]
I have been experiencing this problem forever, but now it really stops me from debugging so decided to report it.
The first time execution stops at a breakpoint everything works as expected, variable values properly show up in RUN AND DEBUG 

<img width="1232" alt="debug-problem-1" src="https://user-images.githubusercontent.com/7325277/222142875-2152e1ac-42da-4868-9d31-9bb4e35ec671.png">

During the second stop at **the same breakpoint** variables do not show up in RUN AND DEBUG panel, but on hoover they still do.

<img width="1194" alt="debug-problem-2" src="https://user-images.githubusercontent.com/7325277/222143131-934c0a28-9de5-4adc-89f3-032e05de23c5.png">
And, finally, during the third stop variables do not show at all. On hoover only little empty box is displayed.   
The issue is probably related to #808 

DEBUG CONSOLE window below 

2nd stop
<img width="1361" alt="debug-problem-4" src="https://user-images.githubusercontent.com/7325277/222144599-066d80e3-85fb-4350-a924-e7aec0d186bd.png">

3rd stop and hoover
<img width="755" alt="debug-problem-3" src="https://user-images.githubusercontent.com/7325277/222144625-ea963499-6666-4a91-bb56-4be0b88dd41d.png">

Environment: OpenOCD 0.12, GCC 12.2.1, Cortex-Debug the latest 1.6.10.
With OpenOCD 0.11 and GCC 10.3 results are the same.

**Comment by tdjastrzebski** [comment]
Cortex-Debug 1.6.11-pre4 seems to fix the hoover issue but variable values in  RUN AND DEBUG panel still do not show up during the 2nd and subsequent breakpoint stops.

**Comment by haneefdm** [comment]
Can I see your launch.json and the output from the Debug Console?

**Comment by tdjastrzebski** [comment]
@haneefdm Here it is, console output attached.
```JSON
{
    "name": "Debug (OpenOCD)",
    "type":"cortex-debug",
    "request": "launch",
    "servertype":"openocd",
    "showDevDebugOutput": "both",
    "cwd": "${workspaceRoot}",
    "executable": "BUILD/debug/${workspaceRootFolderName}.elf",
    "svdFile": "STM32L4x2.svd",
    "runToEntryPoint": "main",
    "device": "STM32L432KCUx",
    "searchDir": ["${env:OpenOCD}/scripts"],
    "serverArgs": [
        "-c hla_serial 066EFF535488524867153759"
    ],
    "configFiles": [
        "/interface/stlink.cfg",
        "/target/stm32l4x.cfg",
    ],
    "interface": "swd",
    "swoConfig": {
        "enabled": true,
        "cpuFrequency": 180000000,
        "swoFrequency": 2000000,
        "source": "probe",
        "decoders": [
            { "type": "console", "label": "ITM", "port": 0 }
        ]
    },
}
```
[console ouput.txt](https://github.com/Marus/cortex-debug/files/10873908/console.ouput.txt)

**Comment by haneefdm** [comment]
Is there anything in the STACK window? If you don't see a stack, then you will not see any variables either.

You can also set "showDevDebugOutput": "vscode" and attach that console output? We are pretty sure we sent VSCode the stack information and it then has to request variables -- which it kinda seems like it did.

**Comment by tdjastrzebski** [comment]
CALL STACK info is always displayed correctly, DEBUG output with "showDevDebugOutput": "vscode" atached.
[console ouput 2.txt](https://github.com/Marus/cortex-debug/files/10875893/console.ouput.2.txt)
<img width="756" alt="debug-problem-5" src="https://user-images.githubusercontent.com/7325277/222555852-ea76199f-8d6e-4865-8a21-36232a7eb240.png">

**Comment by haneefdm** [comment]
Aha. I know exactly why that is happening. Bug in our SW and perhaps even a change in how more recent versions of gdb work. A fix is on the way

**Comment by haneefdm** [comment]
Do you mind trying the latest 1.7.x pre-release?

https://github.com/Marus/cortex-debug/releases

Eager to hear feedback

**Comment by haneefdm** [comment]
If you enable pre-releases within VSCode, this release will also be available over there. Note that this release has a LOT of changes -- mostly related to this issue. New features as well like `Live Watch`. A LOT of code had to be re-written/re-factored

**Comment by tdjastrzebski** [comment]
@haneefdm Thank you for your help. It seems that in 1.7.0-pre1 the problem still persist. Console output attached.
[console output 3.txt](https://github.com/Marus/cortex-debug/files/10888036/console.output.3.txt)

**Comment by haneefdm** [comment]
Could you try this release please.

https://github.com/Marus/cortex-debug/releases/tag/v1.7.1-pre1

This was a huge change in our code base. I had been testing it for a while and it was already supposed to be in 1.7.0 but I missed it.

**Comment by tdjastrzebski** [comment]
As far as I can tell, now it works as expected! Thank you for your effort, it is much appreciated.

**Comment by haneefdm** [comment]
Thanks for reporting back.

Do, globals, statics in the 'VARIABLES' Panel, and expressions in the 'WATCH' windows also work properly? I know, it is hard to tell...

Take your time, no hurry.

**Comment by haneefdm** [comment]
I am going to close this issue...

**Comment by tdjastrzebski** [comment]
Everything seems to works as expected, thanks again, it is probably one of the most important issue fix.
