### ISSUE TITLE
nm and objdump commands add custom parameters

### ISSUE THREAD

**Issue by hongshui3000** [Marus/cortex-debug#834]
The cortex debug extension uses nm and objdump to get some information, but the nm and objdump commands I use need some parameter settings to work. Is it possible to provide a parameter interface

Similar to lauch gdb
![image](https://user-images.githubusercontent.com/25566498/222636852-7704f4db-3a8e-4e09-ada7-85cad0d690e1.png)

not work nm and objdump don't work without my configure core parameters  “--xtensa-core=hifi4vfp7”
![image](https://user-images.githubusercontent.com/25566498/222636893-6fe7ec02-f61d-42a7-8f65-07375aac7a0f.png)

**Comment by haneefdm** [comment]
Sorry, no. You can always wrap any program we launch with a script/executable of your own.

When we truly deal with more than Cortex-M GNU toolchain, I will consider it. I won't want death by a thousand cuts.
