### ISSUE TITLE
Remove Cortex Registers view

### ISSUE THREAD

**Issue by PhilippHaefele** [Marus/cortex-debug#838]
As with V1.2.0 registers moved to the variable section the `Cortex Registers` view should be removed. 

From release notes:
> **Registers**: `Registers` are now available in the `Variables` panel. You can now change the values of registers. But more importantly, unlike the `Registers` panel, this will track your current thread/frame in the `Call Stack` window. This means that registers are now shown in the context of the current frame. What we had before in the `Registers` panel was information we had at the time a halt/breakpoint was hit and potentially incorrect when you refreshed -- this was because there was no API in VSCode for extensions to track the Call Stack window. **`The old Registers panel will be DEPRECATED`**

We had a lot of deprecation time (over 1 year now).

Therefore i suggest to remove it in the upcoming release (pre-release 1.9.0).

**Comment by haneefdm** [comment]
Hehe. I am scared of doing it. Because people think it is actually accurate and I am sure there will be complaints. I was hoping VSCode would fix the issue where we could track the current program/thread/frame. The issue on VSCode/MS side is still open.

**Comment by haneefdm** [comment]
Yes, I will hide it in the next release.

**Comment by PhilippHaefele** [comment]
> Yes, I will hide it in the next release.

Thanks

One thing we need to consider when removing the view, is that it currently houses the `Enable Hex mode` / `Enable Natural mode` button. There's a command for that, but maybe we can move this button somewhere else (variables view?)

**Comment by haneefdm** [comment]
Yup. Doesn't work. That panel/window is created much before cortex-debug is enabled and it appears that extensions cannot add to the title bars. Strange but true.

Registers Panel is now gone.

**Comment by haneefdm** [comment]
> Back then, I didn't know how to add buttons to one of VSCode built-in panels. Maybe it is possible now.

I finally figured out how to add a button to the VARIABLES title bar. Very obtuse way. Will be removing `Enable/Disable hex mode` from the context menu as it is really global to the entire window.

<img width="292" alt="image" src="https://user-images.githubusercontent.com/41269583/224074603-4b0a8c9c-943a-492f-a33e-b4bb8b689ae3.png">

I wanted to add at the beginning but I don't know how to

**Comment by PhilippHaefele** [comment]
> > Back then, I didn't know how to add buttons to one of VSCode built-in panels. Maybe it is possible now.
> 
> I finally figured out how to add a button to the VARIABLES title bar. Very obtuse way. Will be removing `Enable/Disable hex mode` from the context menu as it is really global to the entire window.
> 
> <img alt="image" width="292" src="https://user-images.githubusercontent.com/41269583/224074603-4b0a8c9c-943a-492f-a33e-b4bb8b689ae3.png">
> 
> I wanted to add at the beginning but I don't know how to

Just tested it with the latest pre-relase and i really like it.
