### ISSUE TITLE
Can't configure ST-LINK_gdbserver port number

### ISSUE THREAD

**Issue by schiltztool** [Marus/cortex-debug#839]
One of the default arguments for `servertype` `stlink` is `-p 50000` which is causing the ST-LINK_gdbserver to fail to connect to my ST-Link debugger. 

Running ST-LINK_gdbserver from the command line with the `-p 61234` solves the issue, but I can't add the argument to `serverArgs` because it is already defined by the extension and I get a `PARSE ERROR: Argument: -p (--port-number) Argument already set!` error from the gdb server.

Overriding default arguments with `configFiles` also seems to do nothing for `servertype` `stlink`

**Comment by haneefdm** [comment]
You did not describe your environment. Nowadays, there are too many combos of OSes, containers, WSL, etc.

*No, you cannot override the port we determined was free*. My question is why is port 50000 busy? Why is that even failing on the command-line?

**Comment by schiltztool** [comment]
Sorry, my environment is just a windows 10 laptop.

port 50000 ended up being busy because of a process running in the background that I forgot to kill.

I needed to include the `-m 1` flag in `serverArgs` to specify the paID to debug
