### ISSUE TITLE
Cortex debug View Disassembly (Function) some small suggestions for improvement

### ISSUE THREAD

**Issue by hongshui3000** [Marus/cortex-debug#845]
This feature is very useful when viewing assembly lightly (better than Microsoft's assembly， more concise )

Some small improvements are needed in my use:
1. I hope that after closing the disassembly function window, the disassembly function window will not pop up automatically when I repeatedly run this function.

2. When disassembling multiple functions, the disassembly window can automatically switch to the current disassembly function window when running to a certain function.

3. In the C code, select the right-click menu of the function name to have an option to directly execute the command to disassemble the function

In addition to the above two points, it almost meets my daily debugging and assembly needs
the main thing is the first point

Also to mention, You can set the debugger to always show show disassembly (Cortex-Debug: Set Force Disassembly command)
This is no longer working in the current version

**Comment by haneefdm** [comment]
We have nothing to do with the display, lifecycle management, user interface, etc. of the Disassembly window. It belongs to VSCode main repo.

We only provide the instructions (almost in text format)  according to the protocol when asked. We don't even know who is asking and why and what they are doing with the data. Perhaps our format is more compact than what MS (you mean cpptools) does. And, btw, not even cpp tools owns the disassembly window. We all use the same one from VSCode.

I think I mentioned to you all of this before. All the old disassembly functions are going to be removed from Cortex-Debug. Forgot to remove it from the command palette
