### ISSUE TITLE
Use standard `program` keyword in `launch.json` file against `executable`

### ISSUE THREAD

**Issue by denis-shienkov** [Marus/cortex-debug#847]
Hi.

It is strange, why are used the `executable` keyword to specify a path to the executable ELF file, instead of e.g. standard `program` keyword?

Is it possible to add support and for the `program` keyword too to be consistent with other debuggers?

**Comment by denis-shienkov** [comment]
@haneefdm Sorry, but, where is it completed?

**Comment by haneefdm** [comment]
https://stackoverflow.com/questions/12999850/what-are-the-differences-between-a-program-an-executable-and-a-process#:~:text=A%20program%20is%20a%20collection,can%20execute%20on%20the%20CPU.

**Comment by denis-shienkov** [comment]
Ahh, sorry, thanks.
