### ISSUE TITLE
Updated BlackMagic "launch.json" script segments

### ISSUE THREAD

**Issue by wmaxfield** [Marus/cortex-debug#866]
Here is two moderately tested (with stm32f103) Black Magic launch.json scripts.  Your current script works, but has some settings that do nothing according to VSCode complaints.  Tested OSX Monterey, clone stlink updated to BlackMagic:
        {
            "name": "BMP attach",
            "cwd": "${workspaceRoot}",
            "executable": "${workspaceRoot}/build/blink2.elf", // replace with your executable
            "request": "attach",    
            "type": "cortex-debug",
            "servertype": "bmp",
            "interface": "swd",
            "device": "STM32F103",
            "BMPGDBSerialPort": "/dev/cu.usbmodem4C99B0AB1",  // Use whatever serial port makes sense for your OS and BMP setup
            "runToEntryPoint": "main",
        },
        {
            "name": "BMP Debug",
            "cwd": "${workspaceRoot}",
            "executable": "${workspaceRoot}/build/blink2.elf", // replace with your executable
            "request": "launch",    
            "preLaunchTask": "Build STM", // using stm32-for-vscode extension, this is the build task
            "type": "cortex-debug",
            "servertype": "bmp",
            "interface": "swd",
            "device": "STM32F103",
            "BMPGDBSerialPort": "/dev/cu.usbmodem4C99B0AB1",  // Use whatever serial port makes sense for your OS and BMP setup
            "runToEntryPoint": "main" // runToMain is deprecated.
        }

**Comment by haneefdm** [comment]
Feel free to edit the Wiki. Most of our Wikis are user contributed. I updated it already but if you could check fo accuracy. I put the most important attributes first that say what debug/gdb-server to use and the type of debug session

https://github.com/Marus/cortex-debug/wiki/Black-Magic-Probe-Specific-Configuration
