### ISSUE TITLE
JLink probe is connected, but still no debugging

### ISSUE THREAD

**Issue by tcao** [Marus/cortex-debug#87]
I'm in OSX 10.13.6, JLink V6.32h, VSC 1.26.1, and Cortex-Debug 0.1.21. 
When I tried to debug nRF52 DK, Adapter Output shows JLink is connected, but I still get error "Debug adapter process has terminated unexpectedly"
Any idea what's going on?
![jlink](https://user-images.githubusercontent.com/678077/44931704-d8f00480-ad1f-11e8-81ec-a753c7d76220.png)

**Comment by bikeNomad** [comment]
I have the same problem with the same versions of software. How did you get the "Adapter Output" window? I don't have one.

**Comment by Travis-Spidertracks** [comment]
I got this error when arm-none-eabi-gdb was not available on my path. But I think this might be a catch-all for a number of errors

**Comment by sbomber** [comment]
I experienced similar behavior.  It was because VS Code was open when I installed arm-none-eabi-gdb.  Therefore, the running instance of VS Code did not have the updated PATH.

**Comment by Marus** [comment]
When you get this error can you click on the "Debug adapter process has terminated unexpectedly"  and see if it gives any additional details?

**Comment by huzhanbo1996** [comment]
Has anyone solved this problem? I have the same issue. The debug will stop in 1s after it started, but it works before it stops.

**Comment by huzhanbo1996** [comment]
> When you get this error can you click on the "Debug adapter process has terminated unexpectedly" and see if it gives any additional details?

my vs code give sometimes "read error", some times "exit code:-1"
