### ISSUE TITLE
Does coretex-debug support armclang?

### ISSUE THREAD

**Issue by DavidA2014** [Marus/cortex-debug#872]
Hi, Does coretex-debug support the armclang toolset, or does it only support the gnu arm toolchain?

Just a suggestion: could you enable 'Discussions' for this project so that Q&A could be separated from Issues?

**Comment by haneefdm** [comment]
You can use any compiler you want. I know we have had IAR users here. Ultimately, they all produce an elf file conforming to the ARM specification -- that can be debugged by GDB.

So, you only need some tools gdb/nm/objdump from the ARM GNU toolchain to debug 

> Just a suggestion: could you enable 'Discussions' for this project so that Q&A could be separated from Issues?

Good idea. Not sure I can do that. I don't own the repo but I will look into it. I maintain this project.

**Comment by Eplankton** [comment]
> Hi, Does coretex-debug support the armclang toolset, or does it only support the gnu arm toolchain?
> 
> Just a suggestion: could you enable 'Discussions' for this project so that Q&A could be separated from Issues?

For armclang (or armcc) toolchain, you can choose to use both `axf` and `elf` binary.

**Comment by haneefdm** [comment]
Both are ELF formats I believe. You can use either. I don't think there is a difference. If you are in Unix, you can do `file blah.axf` and it will tell you what the format actually is.
