### ISSUE TITLE
Question/Clarification: How does cortex-debug handle RTT?

### ISSUE THREAD

**Issue by NOhs** [Marus/cortex-debug#876]
Sorry for this rather broad question which does not fit the two provided issue templates. I am currently investigating using RTT on an automated embedded work bench. The major goal is to capture test output and to synchronize target and host if necessary during more complex testing scenarios. With cortex-debug, RTT is very comfortable to use. So I was wondering how cortex-debug handles RTT via J-Link.

1) Does cortex-debug use the official SDK?
2) Does cortex-debug use other means to setup RTT?
2.1) If so is this a publicly shared package that I could re-use for my purposes?

Thanks in advantage for any help (also other suggestions that maybe I am unaware of).

**Comment by haneefdm** [comment]
RTT is FW created and distributed by SEGGER. It is free and anyone can use it. If you install the JLink SW, you will find the FW in this directory `<install-dir>/JLink/Samples/RTT`

Cortex-Debug just follows what the FW does and what the gdb-server (OpenOCD or JLinkGDBServer) documents. Please read their documents. The setup is quite different between OpenOCD and JLink.

Also, you don't have to use cortex-debug. You can use any telnet-like program to read/write data yourself. Note that RTT uses your existing debug pins (SWD) to connect to the device.
