### ISSUE TITLE
Can't debug with zephyr-sdk because ENOENT error

### ISSUE THREAD

**Issue by abarnas-airly** [Marus/cortex-debug#877]
**Describe the bug**
I am trying to setup launch.json to debug a zephyr application using zephyr-sdk

**Expected behavior**

After hitting F5 I want to start a debug session but it ends wit ENOENT error

**Environment (please complete the following information):**

 - Cortex-Debug Version (this extension) v1.8.0
 - OS: Linux Ubuntu 22.04 LTS
 - GDB Version: GNU gdb (Zephyr SDK 0.16.0) 12.1
 - Compiler Toolchain Version: arm-zephyr-eabi-gcc (Zephyr SDK 0.16.0) 12.2.0

**Please include `launch.json`**

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "App",
            "cwd": "${workspaceRoot}",
            "executable": "build/zephyr/zephyr.elf",
            "request": "launch",
            "servertype": "openocd",
            "configFiles": ["${workspaceRoot}/boards/arm/nucleo_l412rb_p/support/openocd.cfg"],
            "gdbPath": "~/zephyr-sdk-0.16.0/arm-zephyr-eabi/bin/arm-zephyr-eabi-gdb",
            "type": "cortex-debug",
            "device": "stm32l412RB",
            "interface": "swd",
            "svdFile": "${workspaceRoot}/boards/arm/nucleo_l412rb_p/support/stm32l412.svd",
            "showDevDebugOutput": "raw" 
        }
    ]
}
```

**Attach text from `Debug Console`**

```
Reading symbols from ~/zephyr-sdk-0.16.0/arm-zephyr-eabi/bin/arm-zephyr-eabi-objdump --syms -C -h -w /home/adrian/zephyrproject/fw-next-gen-pm-board/build/zephyr/zephyr.elf
Reading symbols from ~/zephyr-sdk-0.16.0/arm-zephyr-eabi/bin/arm-zephyr-eabi-nm --defined-only -S -l -C -p /home/adrian/zephyrproject/fw-next-gen-pm-board/build/zephyr/zephyr.elf
Launching GDB: ~/zephyr-sdk-0.16.0/arm-zephyr-eabi/bin/arm-zephyr-eabi-gdb -q --interpreter=mi2
1-gdb-version
Error: ~/zephyr-sdk-0.16.0/arm-zephyr-eabi/bin/arm-zephyr-eabi-nm failed! statics/global/functions may not be properly classified: Error: spawn ~/zephyr-sdk-0.16.0/arm-zephyr-eabi/bin/arm-zephyr-eabi-nm ENOENT
    Expecting `nm` next to `objdump`. If that is not the problem please report this.
Could not start GDB process, does the program exist in filesystem?
Error: spawn ~/zephyr-sdk-0.16.0/arm-zephyr-eabi/bin/arm-zephyr-eabi-gdb ENOENT
```
**Already checked**
I have tried to run both command from debug log:
`~/zephyr-sdk-0.16.0/arm-zephyr-eabi/bin/arm-zephyr-eabi-objdump --syms -C -h -w /home/adrian/zephyrproject/fw-next-gen-pm-board/build/zephyr/zephyr.elf`
`~/zephyr-sdk-0.16.0/arm-zephyr-eabi/bin/arm-zephyr-eabi-nm --defined-only -S -l -C -p /home/adrian/zephyrproject/fw-next-gen-pm-board/build/zephyr/zephyr.elf`
Both works fine as well as:
`~/zephyr-sdk-0.16.0/arm-zephyr-eabi/bin/arm-zephyr-eabi-gdb`

**Comment by haneefdm** [comment]
The `~` is only understood by a shell. It is not an official OS pathname. You can use `"${env:HOME}/...."` 

https://code.visualstudio.com/docs/editor/variables-reference#_environment-variables
