### ISSUE TITLE
WATCH  variable *(int*)$psp@10  shows <TypeError: Cannot read properties of undefined (reading 'startsWith')>

### ISSUE THREAD

**Issue by googlehim** [Marus/cortex-debug#881]
### Please make you search through our existing [issues](https://github.com/Marus/cortex-debug/issues?q=type:issue) (both open and closed)

**Describe the bug**
WATCH  *(int*)$psp@10  shows <TypeError: Cannot read properties of undefined (reading 'startsWith')>

**To Reproduce**
1. cortex-m4 c project, set breakpoint on HardFault_Handler
2. run a fault test, hit breakpoint on HardFault_Handler
3. VARIABLES->Registers->psp 0x20fdbcd8
4. WATCH->*(int*)0x20fdbcd8@10: [10]
                                 0: 0x20fd0be0
                                 1: 0x1
                                  ...
6. WATCH->*(int*)$psp@10: <TypeError: Cannot read properties of undefined (reading 'startsWith')>

**Expected behavior**
show variable array of psp like *(int*)0x20fdbcd8@10 does.

**Screenshots**
![image](https://github.com/Marus/cortex-debug/assets/9864527/d17f6aa3-53f6-4947-8a70-97921a82c6d7)

**Environment (please complete the following information):**

 - Cortex-Debug Version (this extension) [v1.6.7]
 - vscode 1.70.2
 - OS: [Linux Ubuntu 22.04]
 - GDB Version: [gcc-arm-none-eabi-10.3-2021.10/bin/arm-none-eabi-gdb]
 - Compiler Toolchain Version: [gcc-arm-none-eabi-10.3-2021.10]

**Please include `launch.json`**

*Note: We are unlikely to look at the issue if you do not supply this*
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug with OpenOCD",
            "cwd": "${workspaceRoot}",
            "executable": "app.elf",
            "request": "launch",
            "type": "cortex-debug",
            "servertype": "openocd",
            "serverpath": "/openocd/0.10.0-15/bin/openocd",
            "configFiles": [
                "target/mcu.cfg",
            ],
            "showDevDebugOutput": "none",
        },

    ]
}
```

**Comment by haneefdm** [comment]
Could you try the pre-release version 1.11.2 (available from the VSCode marketplace)?

I understand what `$psp` would be but not `$psp@10`. That may be a real problem but first, we should try the latest version.

**Comment by googlehim** [comment]
First thank you for your work.

I try to switch to pre-release version and got this:

> Can't install 'mcu-debug.peripheral-viewer' extension because it is not compatible with the current version of Visual Studio Code (version 1.70.2).

However I successfully upgrade to Cortex-Debug-V1.10.0, the problem seems gone:

`$psp@10` : Display psp as array with 10 elements. Is this feature supported official?

![image](https://github.com/Marus/cortex-debug/assets/9864527/205f26e6-c851-41fe-a8d5-31d5b2af1d0a)
