### ISSUE TITLE
Change backward slash to forward slash when passing console command to gdb

### ISSUE THREAD

**Issue by schiltztool** [Marus/cortex-debug#885]
I'm on windows 10 with [V1.11.3-pre2](https://github.com/Marus/cortex-debug/releases/tag/v1.11.3-pre2)

I'm trying to add a preRestartCommand 
``` json   
"preRestartCommands": [
   "load ${workspaceFolder}/build/PROJECT"
]
```
but gdb fails with the error 
```
31-interpreter-exec console "load C:\Repos\PROJECT/build/PROJECT"
-> &"C:ReposPROJECT/build/PROJECT: No such file or directory.\n"
C:ReposPROJECT/build/PROJECT: No such file or directory.
-> 31^error,msg="C:ReposPROJECT/build/PROJECT: No such file or directory."
```

**Describe the solution you'd like**
Back slashes to get converted to forward slashes when sending console commands to gdb.

**Describe alternatives you've considered**
I've tried setting an environment variable with the correct path in CMAKE then referencing the environment variable instead of `workspaceFolder`, but that requires a reload of VSCode any time the variable changes.

**Comment by haneefdm** [comment]
Can't accept this. preRestart is for all sorts of gdb commands and we cannot change characters randomly. We don't even analyze the commands and never intend to

You need to find another way. A restart btw, was never intended to reload/reprogram the device.
