### ISSUE TITLE
How about using CMSIS-DAP ?

### ISSUE THREAD

**Issue by zhangzq71** [Marus/cortex-debug#888]
**Describe the solution you'd like**
I am using cmsis-dap adapter, is it possible to use it in cortex-debug?

**Comment by haneefdm** [comment]
Yes. You need to pick a gdb-server such as openocd, pyocd, stlink, etc. We don't support any HW directly. Only via gdb-server SW

**Comment by zhangzq71** [comment]
> Yes. You need to pick a gdb-server such as openocd, pyocd, stlink, etc. We don't support any HW directly. Only via gdb-server SW

thanks, I got it, it works.
