### ISSUE TITLE
Adding GDB Path for Linux Cripples Debugging in macOS

### ISSUE THREAD

**Issue by ekawahyu** [Marus/cortex-debug#896]
**Describe the bug**
I am working with STM32 multiplatform builds. On macOS, debugging is done with arm-none-eabi-gdb, but on Linux it is gdb-multiarch. Adding GDB path for Linux debugging renders macOS debugging unusable. This may or may not specific to STM32, but I have no way to test with other platform. But I do know that this does not work with Renode (external debugging).

**To Reproduce**
1. Start any STM32 Makefile project, and you will need to run the build on macOS and Linux.
2. Create simple launch.json file:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug",
            "cwd": "${workspaceFolder}",
            "executable": "executable.elf",
            "request": "launch",
            "type": "cortex-debug",
            "runToEntryPoint": "main",
            "servertype": "stlink",
        }
    ]
}
```
3. At this point, debugging on macOS should work just fine.
4. Switch to Linux machine and add settings.json file:
```
{
    "cortex-debug.gdbPath.linux": "/usr/bin/gdb-multiarch"
}
```
5. Debugging on Linux should work just fine.
6. Now switch back to macOS, debugging won't work with nothing shown on Debug Console, no error messages.

**Expected behavior**
With/without adding "cortex-debug.gdbPath.linux" configuration, debugging on macOS should work and ignore this Linux config.

**Environment (please complete the following information):**

[comment]: <> Whenever possible, please make sure you are using the latest versions of VSCode and our extension

 - Cortex-Debug Version: v1.10.0
 - OS: macOS Monterey 12.6.3, Ubuntu Linux 20.04.5 LTS
 - GDB Version on macOS: GNU gdb (GNU Arm Embedded Toolchain 10.3-2021.10) 10.2.90.20210621-git
 - GDB Version on Linux: GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2

**Please include `launch.json`**
Please see description above for both `launch.json` and `settings.json`

**Attach text from `Debug Console`**
Debug Console is empty, no error, no log.

**Workaround**
Temporary workaround I made in settings.json is as follows:
```
{
    "cortex-debug.gdbPath.linux": "/usr/bin/gdb-multiarch",
    "cortex-debug.gdbPath.osx": null,
}
```
With this workaround, I can do debugging on macOS and everything seems to work just fine. I don't see any Cortex-Debug documentation mentioning about the requirement to put all of gdb paths? Is this expected?

**Comment by haneefdm** [comment]
Thank you for reporting this issue. It is a defect. It should be fixed in the next update v1.11.x
