### ISSUE TITLE
How to set `--elf` for pyocd to debug with FreeRTOS?

### ISSUE THREAD

**Issue by yyjdelete** [Marus/cortex-debug#903]
**Is your feature request related to a problem? Please describe.**
Sometimes pyocd require some extra debug info from elf files to debug with FreeRTOS, but how to set this in cortex-debug?
https://github.com/pyocd/pyOCD/blob/376d3f49db411a152d1ab5998967862707ae46fd/pyocd/rtos/freertos.py#L353

Didn't see an option for this
https://github.com/Marus/cortex-debug/wiki/PyOCD-Specific-Configuration-Options
And cortex-debug will not pass `executable` to pyocd as `--elf` by default

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by haneefdm** [comment]
use `serverArgs` in launch.json
