### ISSUE TITLE
Synchronize display of breakpoints (with their type) with the breakpoints entered manually in the debug console

### ISSUE THREAD

**Issue by yguel** [Marus/cortex-debug#904]
**Is your feature request related to a problem? Please describe.**
Currently, it is not possible to chose to define hardware or software breakpoints from the graphical user interface. With a nucleo_wb55rg as a test board, connected through an OpenOcd gdb server, the behavior observed when setting breakpoints is as follow:

- breakpoints are hardware breakpoints since code is in flash and if I set many many breakpoints graphically and start the debugging session I receive the following error in the debug console:
```
"Cannot insert hardware breakpoint 36.\n"
Cannot insert hardware breakpoint 36.
-> &"Could not insert hardware breakpoints:\n"
Could not insert hardware breakpoints:
-> &"You may have requested too many hardware breakpoints/watchpoints.\n"
You may have requested too many hardware breakpoints/watchpoints.
```
- if use the gdb command "info breakpoints" in the debug console after setting the breakpoint through the GUI the type of the breakpoints is: ''breakpoint''
- I can set a breakpoint using the command ''hbreak main.c:42'' in the debug console and if I use the gdb command "info breakpoints" in the debug console I get:
```
From client: evaluate({"expression":"info breakpoints","frameId":4096,"context":"repl"})
65-interpreter-exec console "info breakpoints"
-> ~"2       breakpoint     keep y   0x080008f4 in main at /workdir/my-sdk/zephyr/samples/basic/blinky/src/main.c:37\n"
2       breakpoint     keep y   0x080008f4 in main at /workdir/my-sdk/zephyr/samples/basic/blinky/src/main.c:37
-> ~"3       hw breakpoint  keep y   0x0800090a in main at /workdir/my-sdk/zephyr/samples/basic/blinky/src/main.c:42\n"
3       hw breakpoint  keep y   0x0800090a in main at /workdir/my-sdk/zephyr/samples/basic/blinky/src/main.c:42
{"output":"","token":65,"outOfBandRecord":[],"resultRecords":{"resultClass":"done","results":[]}}
```
I get correctly 2 breakpoints with different type: ''breakpoint'' and ''hw breakpoint''
However in the gui the second breakpoint does not appear.

What is very confusing, is that there will only be hardware breakpoint, however breakpoints are recorded as "software breakpoints" and not "hardware breakpoint" except if they are entered manually (although, it is probably a problem related to openOCD and not cortex-debug)
- If I delete all the breakpoints manually, If I enter the ''delete'' command for instance. All breakpoints are indeed deleted however they still appear in the GUI.

**Describe the solution you'd like**
- I would like a button and/or a background process that update/synchronize the GUI with the breakpoints entered manually in the debug console.
- I would like that, in the GUI, the extra information about the type of the breakpoints is available (even if the information is strangely erroneous) at least synchronized with the list of breakpoints received from a command like ''info breakpoints''
- I would like to be able to change the type of the breakpoint from the GUI

**Describe alternatives you've considered**
Display of breakpoints: using gdb command ''info breakpoints''.
Change type of breakpoint: delete the breakpoint, create new breakpoint with new type (either in debug console or with the GUI)

**Additional context**

**Comment by haneefdm** [comment]
Thanks for the suggestion.

Sorry. We can't/don't monitor what commands you are entering in the debug console. For all we know you are running complicated scripts. We also don't want to fetch all breakpoints all the time.

There is also the fact that VSCode does not support all of what is possible with gdb. So, we have a translation problem.

Many other hurdles.
