### ISSUE TITLE
Raspberry Pi/ Pico SDK/ Ubuntu: Need SUDO as opencd prefix

### ISSUE THREAD

**Issue by torlarse** [Marus/cortex-debug#910]
**Describe the bug**
When running GDB from command line on my Raspberry Pi, I get a `permission denied` error if I don't prepend `sudo` to the `openocd` command. When I try debugging from VS Code on the Pi, I get that same error.

**To Reproduce**
1. On a Raspberry Pi Pico, follow [Getting Started guide](https://datasheets.raspberrypi.com/pico/getting-started-with-pico.pdf), chapter 6.3
2. Test GDB debugger from command line without `sudo` -> fail
3. Add `sudo` to `openocd` command -> success
4. Configure VS Code as in Chapter 7.3
5. Press F5

**Expected behavior**

The debugger to run, being able to set breakpoints. 

**Environment:**

-  Raspberry Pi, using the Pico SDK
 - Cortex-Debug Version: 1.12.0
 - OS: Linux Ubuntu 22.04 LTS, Windows 11
 - GDB Version: 1.11.3 multi-arch
 - Compiler Toolchain Version: GCC 10.3.1 arm-none-eabi

**launch.json:**
```
{
    "version": "0.2.0",
    "configurations": [

        {
            "name": "Pico Debug",
            "cwd": "${workspaceRoot}",
            "executable": "${command:cmake.launchTargetPath}",
            "request": "launch",
            "type": "cortex-debug",
            "servertype": "openocd",
            "gdbPath" : "gdb-multiarch",
            "device": "RP2040",
            "showDevDebugOutput": "raw",
            "configFiles": [
                "interface/raspberrypi-swd.cfg",
                "target/rp2040.cfg"
            ],
            "svdFile": "${env:PICO_SDK_PATH}/src/rp2040/hardware_regs/rp2040.svd",
            "runToEntryPoint": "main",
            "postRestartCommands": [
                "break main",
                "continue"
            ]
        }
    ]
}
```
**Debug console**
```
Cortex-Debug: VSCode debugger extension version 1.12.0 git(d7a405a). Usage info: https://github.com/Marus/cortex-debug#usage
Reading symbols from objdump-multiarch --syms -C -h -w /home/pi/pico/pico-examples/build/hello_world/usb/hello_usb.elf
Reading symbols from nm-multiarch --defined-only -S -l -C -p /home/pi/pico/pico-examples/build/hello_world/usb/hello_usb.elf
Launching GDB: gdb-multiarch -q --interpreter=mi2
1-gdb-version
Error: nm-multiarch failed! statics/global/functions may not be properly classified: Error: spawn nm-multiarch ENOENT
    Expecting `nm` next to `objdump`. If that is not the problem please report this.
Error: objdump failed! statics/globals/functions may not be properly classified: Error: spawn objdump-multiarch ENOENT    ENOENT means program not found. If that is not the issue, please report this problem.Launching gdb-server: openocd -c "gdb_port 50000" -c "tcl_port 50001" -c "telnet_port 50002" -s /home/pi/pico/pico-examples -f /home/pi/.vscode/extensions/marus25.cortex-debug-1.12.0/support/openocd-helpers.tcl -f interface/raspberrypi-swd.cfg -f target/rp2040.cfg
    Please check TERMINAL tab (gdb-server) for output from openocd
Finished reading symbols from objdump: Time: 283 ms
Finished reading symbols from nm: Time: 253 ms
OpenOCD: GDB Server Quit Unexpectedly. See gdb-server output in TERMINAL tab for more details.
```

Terminal:

```
[2023-07-17T19:10:37.029Z] SERVER CONSOLE DEBUG: onBackendConnect: gdb-server session connected. You can switch to "DEBUG CONSOLE" to see GDB interactions.
openocd -c "gdb_port 50000" -c "tcl_port 50001" -c "telnet_port 50002" -s /home/pi/pico/pico-examples -f /home/pi/.vscode/extensions/marus25.cortex-debug-1.12.0/support/openocd-helpers.tcl -f interface/raspberrypi-swd.cfg -f target/rp2040.cfg
Open On-Chip Debugger 0.12.0-g97d1e6e (2023-07-16-20:26)
Licensed under GNU GPL v2
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
CDLiveWatchSetup
Warn : TMS/SWDIO moved to GPIO 8 (pin 24). Check the wiring please!
adapter speed: 5000 kHz

Info : Hardware thread awareness created
Info : Hardware thread awareness created
Info : Listening on port 50001 for tcl connections
Info : Listening on port 50002 for telnet connections
Info : BCM2835 GPIO JTAG/SWD bitbang driver
Error: open: Permission denied

[2023-07-17T19:10:37.150Z] SERVER CONSOLE DEBUG: onBackendConnect: gdb-server session closed
GDB server session ended. This terminal will be reused, waiting for next session to start...
```

The info and the error shown from terminal, is exactly the same I get from running OpenOCD GDB server in command line without `sudo`. So I would like Cortex debugger to pass the command 

```
sudo openocd -c "gdb_port 50000" -c "tcl_port 50001" -c "telnet_port 50002" -s /home/pi/pico/pico-examples -f /home/pi/.vscode/extensions/marus25.cortex-debug-1.12.0/support/openocd-helpers.tcl -f interface/raspberrypi-swd.cfg -f target/rp2040.cfg
```

I could not easily find any command that would solve the problem in the [attribute docs](https://github.com/Marus/cortex-debug/blob/master/debug_attributes.md). If I missed something obvious, sorry!

**Comment by haneefdm** [comment]
Never heard of this. We never required `sudo`. Not sure why your system needs this. Please talk to your sys-admin.

We will also not get into the business of `sudo`ing commands we launch ... with the security implications that come with it.

**Comment by haneefdm** [comment]
You can write your own wrapper script for anything we launch. We will not do that. You have control over what we launch so in a sense you can do whatever you want.

I never heard of this issue before in the last several issues. Why don't you contact the OpenOCD folks and ask them why you need `sudo` all of a sudden. Not sure where you got your openocd and what it may be accessing (devices, file systems, etc.) that is protected

**Comment by haneefdm** [comment]
If you know how to write a shell/perl/python script, then you know how to write a wrapper script. Nothing to do with VSCode.

1. Create a script that launches openocd the way you want to. It can be a one-liner. Put it somewhere like `/home/username/bin/myopenocd.sh` and make sure you set execute permission on it. Remember that `sudo` requires a password and not sure how you are going to get around it
2. For cortexdebug, tell it that your openocd path is `/home/username/bin/myopenocd.sh`. It won't know what the hell it is and it will do what the script says.

Thanks. Please have a friend/colleague help you.

I recommend why on earth you need to `sudo` first instead of looking for weird workarounds. Maybe, you installed openocd as root and you don't have permission to execute it. I don't know.

**Comment by haneefdm** [comment]
I found something that may be relevant.

https://elinux.org/Accessing_Devices_without_Sudo#:~:text=On%20Linux%2C%20OpenOCD%20requires%20superuser,user%20for%20the%20root%20password.

https://elinux.org/Running_OpenOCD_on_Linux#OpenOCD_and_Permissions
