### ISSUE TITLE
Remove --no-reset argument from st-util argument list

### ISSUE THREAD

**Issue by ArmoredPony** [Marus/cortex-debug#925]
Is there a particular reason why the `--no-reset` option is [included](https://github.com/Marus/cortex-debug/blob/2afa4d903667841ff1fb856a4dd7a858f52ba095/src/stutil.ts#L104) in the default arguments list for st-util? Since there is a `serverArgs` parameter available, I would leave it to user to decide. This question was also raised in #623.

**Comment by haneefdm** [comment]
I am the sole maintainer of cortex-debug right now. Support for st-util has been added 4-6 years ago by @Marus I think and it's been there forever. So, I am not likely to change it in any way without understanding the implications. Maybe it was to support both launch and attach?

If @Marus blesses the change, I am okay with it (but still have to deal with complaints), or else, it will stay the way it is. I don't want existing users to get mad at us for changing *anything* without understanding the impact. No, adding additional things to `launch.json` is not a good solution.

I recommend you move to one of the ST official gdb-servers. Like st-link, jlink or openocd where you are likely to get support from us and the community.

You can also create your own wrapper for st-util. Maybe st-util folks can give guidance.

I am going to leave this open for a while in face @Marus responds.
