### ISSUE TITLE
Change the download command for OpenOCD configurations

### ISSUE THREAD

**Issue by florianhumblot** [Marus/cortex-debug#934]
**Is your feature request related to a problem? Please describe.**
I'm trying to get cortex-debug to work with ESP32 based devices using a J-Link debug probe.
I've gotten OpenOCD + J-Link + xtensa gdb to work  in the command line, but now I'd like to to be integrated in vscode.
Right now, my config looks like:

```json
{
    "name": "Cortex Debug",
    "cwd": "${workspaceFolder}",
    "executable": "./build/myproject.elf",
    "request": "launch",
    "type": "cortex-debug",
    "runToEntryPoint": "main",
    "servertype": "openocd",
    "configFiles": [
        "${workspaceFolder}/esp32.cfg"
    ],
    "openOCDLaunchCommands": [
        "adapter speed 6000"
    ],
    "toolchainPrefix": "xtensa-esp32-elf",
    "showDevDebugOutput": "raw"
}
``` 
[esp32.cfg as a .txt should that content matter](https://github.com/Marus/cortex-debug/files/12660933/esp32.cfg.txt)
I get an error about erasing the flash:
 > Failed to launch GDB: Error erasing flash with vFlashErase packet (from target-download)

[Full log](https://github.com/Marus/cortex-debug/files/12660953/cortex-debug.log)

According to the esp32 docs, you can upload the binary using the openocd command `program_esp <filename> \[address\] \[verify\] \[reset\] \[exit\]` where only the filename is required, and the address is required if the file is a binary file.

Using the command line I can start openocd: `openocd -s ./tcl -f ./esp32.cfg -c 'adapter speed 6000'` 
And then connect GDB to that session: `xtensa-esp32-elf-gdb -ex 'target remote localhost:3333' ./build/myproject.elf`

During the session I can reprogram the ESP by running these commands in GDB:
`program_esp build/myproject.elf 0x10000`
`read build/myproject.elf` 

If would be cool if I could override the default way to flash/erase the chip that cortex-debug triggers in OpenOCD using options or a script of some kind. 
It may also be that I just misunderstood the docs and that this is already possible but I think that the main issue is the calling of `vFlashErase` which doesn't seem implemented or something for the ESP32 target

**Comment by haneefdm** [comment]
You can already do this in multiple ways. You can override the launch commands and do whatever you like. If you want to send a command to openocd (or any gdb server), you do use the gdb `monitor` command; See

https://github.com/haneefdm/psoc6hello/blob/a1e5f856aed5081ca347ce8391d4e84f728d3408/Hello_World_1/.vscode/launch.json#L49
https://github.com/haneefdm/psoc6hello/blob/a1e5f856aed5081ca347ce8391d4e84f728d3408/Hello_World_1/.vscode/launch.json#L207

You should probably read the wiki and all the things that can go into your launch.json
https://github.com/Marus/cortex-debug/wiki/Cortex-Debug-Under-the-hood
https://github.com/Marus/cortex-debug/blob/master/debug_attributes.md

It all depends on how well you know gdb and your gdb server.
