### ISSUE TITLE
Is There have a way to enable intellisense and autocomplete in internal debug console?

### ISSUE THREAD

**Issue by Tracker647** [Marus/cortex-debug#936]
It's really inconvenient, I can use intellisense and autocomplete when I debugging Gcc-C/C++/Python project, but these features not working when debugging my develop board, I don't know it's my debugger(arm-none-eabi-gdb) or extension reason.

If the problem is not extension based, how to enable intellisense and autocomplete in internal debug console? or better idea that I can call external terminal to debug my program so I can use intellisense and autocomplete, and maintain the debug view of vscode GUI?

**Comment by haneefdm** [comment]
We only handle debugging. Intellisense and general editing is handled by VSCode and the cpptools extension (also by MS)

The entire user interface belongs to VSCode. And, no we will not support external console for your code or debug.
