### ISSUE TITLE
View FreeRTOS Queue contents in cortex-debug

### ISSUE THREAD

**Issue by srobertjames** [Marus/cortex-debug#937]
**Is your feature request related to a problem? Please describe.**
When debugging a FreeRTOS project, I need to know the contents of a FreeRTOS Queue

**Describe the solution you'd like**
Similar to vscode watches: A table or tree showing FreeRTOS Queues, their size, and their contents (as an array)

**Describe alternatives you've considered**
1. Looking at the `u` member in the watches, and then looking at the memory view
2. Other debuggers seem to support this

**Additional context**

**Comment by haneefdm** [comment]
Sorry, wrong extension. The RTOS extension is 

https://github.com/mcu-debug/rtos-views

Please submit the issue there. This is not a debugger feature per see. RTOS, memory, SVD are all split up and now work with many debuggers, independent of each other.
