### ISSUE TITLE
"Couldn't find a compatible version of Cortex-Debug with this version of Code."

### ISSUE THREAD

**Issue by Pharap** [Marus/cortex-debug#94]
When trying to install the extension I get the message
> Couldn't find a compatible version of Cortex-Debug with this version of Code.

I'm using Visual Studio Code version 1.16.1 on Windows 8.

![version](https://user-images.githubusercontent.com/2933055/46112043-15a90180-c1e1-11e8-8c2b-36d7b9703b57.png)

**Comment by Marus** [comment]
I'm sorry - not maintaining the project to work with older versions of VSCode - you'll have to update to VS Code v 1.28 or above for version 0.2+; (The 0.1.x versions of cortex-debug will install on VSCode 0.18 or above - but can't guarantee full compatibility with all the versions)
