### ISSUE TITLE
Add ThreadX support in XRTOS window

### ISSUE THREAD

**Issue by tdjastrzebski** [Marus/cortex-debug#940]
With the release of STM32U5 MCU family ThreadX is officially supported by ST and some valuable packages depend on it so it gains popularity. Therefore I suggest adding ThreadX support in XRTOS window.

**Comment by haneefdm** [comment]
As you can see in our top-level readme.md file. All RTOS's are donations made by the community. I have nothing against any RTOS. I need a volunteer(s) who is knowledgeable in the said RTOS to implement and support it.

https://github.com/mcu-debug/rtos-views#contributors-and-maintainers

**Comment by haneefdm** [comment]
Closing this as it does not belong to this extension
