### ISSUE TITLE
supported cortex-r devices?

### ISSUE THREAD

**Issue by frank-amy** [Marus/cortex-debug#942]
### Please make you search through our existing [issues](https://github.com/Marus/cortex-debug/issues?q=type:issue) (both open and closed)
Please visit the correct repo to file an issue. If this is an issue with
* Peripherals/SVD Viewer: [https://github.com/mcu-debug/peripheral-viewer](https://github.com/mcu-debug/peripheral-viewer)
* Memory Viewer: [https://github.com/mcu-debug/memview](https://github.com/mcu-debug/memview)
* RTOS Viewer: [https://github.com/mcu-debug/rtos-views](https://github.com/mcu-debug/rtos-views)
* the debugger itself, continue below

**Describe the bug**

**To Reproduce**
1. Start debug session
4. See issue

**Expected behavior**

[comment]: <> A clear and concise description of what you expected to happen.

**Screenshots**

[comment]: <> If applicable, add screenshots to help explain your problem.

**Environment (please complete the following information):**

[comment]: <> Whenever possible, please make sure you are using the latest versions of VSCode and our extension

 - Cortex-Debug Version (this extension) [e.g. 0.2.3]
 - OS: [e.g. Linux Ubuntu 18.04 LTS, Windows 11, etc.]
 - GDB Version: [e.g. 1.11.1]
 - Compiler Toolchain Version: [e.g. arn-none-eabi V 11.1]

**Please include `launch.json`**

*Note: We are unlikely to look at the issue if you do not supply this*
```
Paste launch.json contents here
```

**Attach text from `Debug Console`**

Please enable debug output in your launch.json (`"showDevDebugOutput": "raw"`). It this is too large, please attach it as a file
```
Paste Debug Console contents here
```

**Additional context**

**Comment by haneefdm** [comment]
It already works. Many people reported it as working on Cortex-R and even other architectures like Xtensa, RISC-V, etc.
