### ISSUE TITLE
serverArgs are put in quotes 

### ISSUE THREAD

**Issue by dani9** [Marus/cortex-debug#945]
i tried to set jlink target interface speed via
```
"serverArgs": [
    "-speed 2000"
],
```
the resulting command is:
`JLinkGDBServer -singlerun -nogui -if swd -port 50000 -swoport 50001 -telnetport 50002 -device STM32F446RC "-speed 2000"`

now I get the warning:
`WARNING: Unknown command line parameter -speed 2000 found.`

Without quotes around `-speed 2000` the JLinkGDBServer command is working as expected.

**Comment by romancardenas** [comment]
Try with:
```
"serverArgs": [
    "-speed",
    "2000"
],
```

**Comment by dani9** [comment]
thanks that worked
