### ISSUE TITLE
Add VScode 1.70 support

### ISSUE THREAD

**Issue by mrx23dot** [Marus/cortex-debug#948]
The last version that supported on Windows 7,
many embedded development is still done on Windows 7, some products need decades of support.

**Comment by haneefdm** [comment]
What is not working? If VSCode works, we should work as well. We don't have any platform-specific code.

Submit a proper bug report. This is the not the right way.

**Comment by haneefdm** [comment]
You need to log into github to report an issue properly

**Comment by haneefdm** [comment]
That is a problem with VSCode. The API's we use require a later version of VSCode

You can try to install an older version of our extension. Not sure which. And, we cannot support older versions. Maybe from a year ago. good luck.
