### ISSUE TITLE
Debugging MIMXRT1064 chip failed

### ISSUE THREAD

**Issue by NineSwords-Z** [Marus/cortex-debug#951]
Hello, I'm having some problems debugging MIMXRT1064 chip with Cortex-Debug, here is the print information, has anyone used this chip? Is there anything wrong with the Launch file?

**launch script**
    "configurations": [
        {
            "cwd": "${workspaceRoot}",
            "executable": "./debug/MIMXRT1064.elf",
            "name": "J-Link",
            "request": "launch",
            "type": "cortex-debug",
            "servertype": "jlink",
            "device": "MIMXRT1064XXX6A",
            "searchDir": [],
            "liveWatch": {
                "enabled": true,
                "samplesPerSecond": 10
            },
            "runToEntryPoint": "main",
            "showDevDebugOutput": "none",
            "interface": "swd",
            "svdFile": "./MIMXRT1064.svd",
            "serverArgs": ["-SettingsFile", "D:\\WorkSpace\\STM32CubeMX\\scons-CortexM\\MIMXRT1064\\JLink_iled_blinky.jlink"],
            // "showDevDebugTimestamps": true,
            "preLaunchTask": "Build"
        },
    ]

**DEBUG CONSOLE**
Cortex-Debug: VSCode debugger extension version 1.12.1 git(652d042). Usage info: https://github.com/Marus/cortex-debug#usage
Reading symbols from C:/Program Files (x86)/GNU Arm Embedded Toolchain/10 2021.10/bin/arm-none-eabi-objdump.exe --syms -C -h -w D:/WorkSpace/STM32CubeMX/scons-CortexM/MIMXRT1064/debug/MIMXRT1064.elf
Reading symbols from c:/program files (x86)/gnu arm embedded toolchain/10 2021.10/bin/arm-none-eabi-nm.exe --defined-only -S -l -C -p D:/WorkSpace/STM32CubeMX/scons-CortexM/MIMXRT1064/debug/MIMXRT1064.elf
Launching GDB: "C:\\Program Files (x86)\\GNU Arm Embedded Toolchain\\10 2021.10\\bin\\arm-none-eabi-gdb.exe" -q --interpreter=mi2
    IMPORTANT: Set "showDevDebugOutput": "raw" in "launch.json" to see verbose GDB transactions here. Very helpful to debug issues or report problems
Launching gdb-server: "C:\\Program Files\\SEGGER\\JLink\\JLinkGDBServerCL.exe" -singlerun -nogui -if swd -port 50000 -swoport 50001 -telnetport 50002 -device MIMXRT1064XXX6A -SettingsFile "D:\\WorkSpace\\STM32CubeMX\\scons-CortexM\\MIMXRT1064\\JLink_iled_blinky.jlink"
    Please check TERMINAL tab (gdb-server) for output from C:\Program Files\SEGGER\JLink\JLinkGDBServerCL.exe
Finished reading symbols from objdump: Time: 72 ms
Finished reading symbols from nm: Time: 73 ms
C:\Program Files (x86)\GNU Arm Embedded Toolchain\10 2021.10\bin\arm-none-eabi-gdb.exe: warning: Couldn't determine a path for the index cache directory.
Output radix now set to decimal 10, hex a, octal 12.

**gdb-server TERMINAL**
Waiting for gdb server to start...[2023-11-08T01:22:54.285Z] SERVER CONSOLE DEBUG: onBackendConnect: gdb-server session connected. You can switch to "DEBUG CONSOLE" to see GDB interactions.
"C:\\Program Files\\SEGGER\\JLink\\JLinkGDBServerCL.exe" -singlerun -nogui -if swd -port 50000 -swoport 50001 -telnetport 50002 -device MIMXRT1064XXX6A -SettingsFile "D:\\WorkSpace\\STM32CubeMX\\scons-CortexM\\MIMXRT1064\\JLink_iled_blinky.jlink"
SEGGER J-Link GDB Server V7.92n Command Line Version

JLinkARM.dll V7.92n (DLL compiled Oct 31 2023 15:16:49)

Command line: -singlerun -nogui -if swd -port 50000 -swoport 50001 -telnetport 50002 -device MIMXRT1064XXX6A -SettingsFile D:\WorkSpace\STM32CubeMX\scons-CortexM\MIMXRT1064\JLink_iled_blinky.jlink
-----GDB Server start settings-----
GDBInit file:                  none
GDB Server Listening port:     50000
SWO raw output listening port: 50001
Terminal I/O port:             50002
Accept remote connection:      localhost only
Generate logfile:              off
Verify download:               off
Init regs on start:            off
Silent mode:                   off
Single run mode:               on
Target connection timeout:     0 ms
------J-Link related settings------
J-Link Host interface:         USB
J-Link script:                 none
J-Link settings file:          D:\WorkSpace\STM32CubeMX\scons-CortexM\MIMXRT1064\JLink_iled_blinky.jlink
------Target related settings------
Target device:                 MIMXRT1064XXX6A
Target device parameters:      none
Target interface:              SWD
Target interface speed:        4000kHz
Target endian:                 little

Connecting to J-Link...
J-Link is connected.
Firmware: J-Link  V11 compiled Aug 2 2023 10:34:01
Hardware: V11.00
S/N: 601012370
Feature(s): FlashBP, GDB, JFlash, FlashDL, RDI
Checking target voltage...
Target voltage: 3.33 V
Listening on TCP/IP port 50000
Connecting to target...
Halting core...
Connected to target
Waiting for GDB connection...Connected to 0000:0000:0000:0000:0000:0000:0000:0001
GDB client (conn. 888) requested target.xml from GDB Server
Reading common registers: Read register 'r0' (4 bytes) from hardware: 0xF4010000
Read register 'r1' (4 bytes) from hardware: 0x09000000
Read register 'r2' (4 bytes) from hardware: 0x28000020
Read register 'r3' (4 bytes) from hardware: 0x28000020
Read register 'r4' (4 bytes) from hardware: 0x1C230070
Read register 'r5' (4 bytes) from hardware: 0x703A2020
Read register 'r6' (4 bytes) from hardware: 0xCC4A58C1
Read register 'r7' (4 bytes) from hardware: 0xE8FF0120
Read register 'r8' (4 bytes) from hardware: 0x00032000
Read register 'r9' (4 bytes) from hardware: 0x00000000
Read register 'r10' (4 bytes) from hardware: 0x00000000
Read register 'r11' (4 bytes) from hardware: 0x00800F40
Read register 'r12' (4 bytes) from hardware: 0x00000080
Read register 'sp' (4 bytes) from hardware: 0xE8FF0120
Read register 'lr' (4 bytes) from hardware: 0x43270070
Read register 'pc' (4 bytes) from hardware: 0xF2260070
Read register 'xpsr' (4 bytes) from hardware: 0x00000021
Read 4 bytes @ address 0x700026F2 (Data = 0x2B00681B)
Read 2 bytes @ address 0x700026F2 (Data = 0x681B)
Received monitor command: halt
Halting target CPU...
...Target halted (PC = 0x700026F2)
Received monitor command: reset
Resetting target
Downloading 1024 bytes @ address 0x00000000
Downloading 13708 bytes @ address 0x00000400
Downloading 8 bytes @ address 0x0000398C
Downloading 4 bytes @ address 0x00003994
Downloading 4 bytes @ address 0x00003998
Downloading 100 bytes @ address 0x0000399C
Writing register 'pc' = 0x000004BC
Received monitor command: reset
Resetting target
Read 4 bytes @ address 0x000004BC (Data = 0x4816B672)
Read 2 bytes @ address 0x000004BC (Data = 0xB672)
Connected to 0000:0000:0000:0000:0000:0000:0000:0001
GDB client (conn. 884) requested target.xml from GDB Server
Reading common registers: Read register 'r0' (4 bytes) from hardware: 0x1D230070
Read register 'r1' (4 bytes) from hardware: 0xB83A2020
Read register 'r2' (4 bytes) from hardware: 0x1D230070
Read register 'r3' (4 bytes) from hardware: 0xF0900000
Read register 'r4' (4 bytes) from hardware: 0x00200070
Read register 'r5' (4 bytes) from hardware: 0x703A2020
Read register 'r6' (4 bytes) from hardware: 0x782F5638
Read register 'r7' (4 bytes) from hardware: 0xF0000000
Read register 'r8' (4 bytes) from hardware: 0x00032000
Read register 'r9' (4 bytes) from hardware: 0x00000000
Read register 'r10' (4 bytes) from hardware: 0x00000000
Read register 'r11' (4 bytes) from hardware: 0x00800F40
Read register 'r12' (4 bytes) from hardware: 0xFE010000
Read register 'sp' (4 bytes) from hardware: 0x00000220
Read register 'lr' (4 bytes) from hardware: 0x29532100
Read register 'pc' (4 bytes) from hardware: 0x1C230070
Read register 'xpsr' (4 bytes) from hardware: 0x00000041
Read 4 bytes @ address 0x7000231C (Data = 0x4B10B672)
Read 2 bytes @ address 0x7000231C (Data = 0xB672)
Reading 64 bytes @ address 0x00001C00
Read 2 bytes @ address 0x00001C24 (Data = 0xF7FE)
Read 4 bytes @ address 0x000004BC (Data = 0x4816B672)
Read 2 bytes @ address 0x000004BC (Data = 0xB672)
Setting breakpoint @ address 0x00001C24, Kind = 2, Type = THUMB, BPHandle = 0x0001
Starting target CPU...

**Comment by haneefdm** [comment]
I could not see what problem you are seeing. "some problems" is rather vague.

You can see every command we are executing. Do they all work from the command line?
