### ISSUE TITLE
Unable to read peripheral memory with probe-rs

### ISSUE THREAD

**Issue by kossnikita** [Marus/cortex-debug#952]
**Describe the bug**
Peripheral reading does not work with gdb server probe-rs. While the rest of the debug generally works fine. Variables and stack are displayed. Breakpoints work fine. I'm not sure this issue is related to the extension or the gdb server. Perhaps similar to #210 

**To Reproduce**
1. run `cargo-embed` with gdb server
2. run cortex-debug with `attach`
3. Read peripherals with [peripheral-viewer](https://github.com/mcu-debug/peripheral-viewer)
4. See issue
5. execute `-data-read-memory-bytes 0x40021000 32`
6. See issue again

**Expected behavior**

Reading peripherals returns correct status data.

**Screenshots**

![image](https://github.com/Marus/cortex-debug/assets/39294101/59d6c154-ab61-4c9b-ba23-2c20d679154b)

![image](https://github.com/Marus/cortex-debug/assets/39294101/3a7f8f44-5875-4ea2-9ad3-11dce4b5d23d)

**Environment:**

 - Cortex-Debug v1.12.1
 - OS: W11
 - GDB Version: GNU gdb (Arm GNU Toolchain 13.2.rel1 (Build arm-13.7)) 13.2.90.20231008-git
 - Compiler Toolchain Version: thumbv7em-none-eabi
 - probe-rs 0.21.1
 - rustc 1.73.0 (cc66ad468 2023-10-03)

**launch.json**

```json
"type": "cortex-debug",
"request": "attach",
"executable": "${workspaceFolder}/target/thumbv7em-none-eabi/debug/app",
"name": "cortex-debug",
"preLaunchTask": "GDB Server",
"servertype": "external",
"gdbTarget": "localhost:2345",
"svdFile": "${workspaceFolder}/AT32F415.svd",
"showDevDebugOutput": "raw"
```

**Attach text from `Debug Console`**

```
-data-read-memory-bytes 0x40021000 32
138-data-read-memory-bytes 0x40021000 32
-> 138^error,msg="Unable to read memory."
Unable to read memory. (from data-read-memory-bytes 0x40021000 32)
```

**Additional context**
```
<-- {"command":"evaluate","arguments":{"expression":"-data-read-memory-bytes 0x40021000 32","frameId":4096,"context":"repl"},"type":"request","seq":67}
--> {"seq":374,"type":"event","event":"output","body":{"category":"stderr","output":"105-data-read-memory-bytes 0x40021000 32\n"}}
--> {"seq":375,"type":"event","event":"output","body":{"category":"stderr","output":"-> 105^error,msg=\"Unable to read memory.\"\r\n"}}
--> {"seq":376,"type":"response","request_seq":67,"command":"evaluate","success":false,"message":"Unable to read memory. (from data-read-memory-bytes 0x40021000 32)","body":{"error":{"id":8,"format":"Unable to read memory. (from data-read-memory-bytes 0x40021000 32)","showUser":true}}}
<-- {"command":"scopes","arguments":{"frameId":4096},"type":"request","seq":68}
--> {"seq":377,"type":"event","event":"output","body":{"category":"stderr","output":"106-stack-info-frame --thread 1 --frame 0\n"}}
--> {"seq":378,"type":"event","event":"output","body":{"category":"stderr","output":"-> 106^done,frame={level=\"0\",addr=\"0x0800ba1a\",func=\"at32f4xx_hal::timer::delay::SysDelay::delay\",file=\"src\\\\timer/delay.rs\",fullname=\"D:\\\\Rust\\\\at32f4xx-hal\\\\src\\\\timer\\\\delay.rs\",line=\"54\",arch=\"armv7e-m\"}\r\n"}}
```

**Comment by haneefdm** [comment]
> Peripheral reading does not work with gdb server probe-rs. While the rest of the debug generally works fine. Variables and stack are displayed. Breakpoints work fine. I'm not sure this issue is related to the extension or the gdb server. Perhaps similar to https://github.com/Marus/cortex-debug/issues/210

It could be neither. Some devices simply will not allow reads of certain types of memory. You can try to read those locations using gdb (Use the Debug Console) and see if that works.
