### ISSUE TITLE
preAttachCommands list executed after GDB connect to GDB Server (openOCD)

### ISSUE THREAD

**Issue by Upsylonbare** [Marus/cortex-debug#953]
I am trying to translate this [gdbscript](https://github.com/STMicroelectronics/wiki-stm32mp-addons/blob/5.0.0/gdb-scripts/Setup.gdb) to a launch.json file in order to attach gdb to my target regardingly to ST advice using this script.

Before the line that connects to the target, there is [those two line](https://github.com/STMicroelectronics/wiki-stm32mp-addons/blob/1b1df002788c9f2f99741f4cf8a9c1f1fda7b3f5/gdb-scripts/Setup.gdb#L109) that set memory attributes.

I need to set this two line before, the connection to the gdb-server (OpenOCD) in my case.
So I interested in the attributes **preAttachCommands** **preLaunchCommands** :
To me **preAttachCommands** means a set of commands runs before a remote connection as I have not seen any other attributes to do that.

But the fact is that I saw in the documentation that the description for the two attributes are the same :

Attribute| Type | Launch/ Attach | Description
-- | -- | -- | --
preAttachCommands | string[] | Attach | Additional GDB Commands to be executed at the start of the main attach sequence (immediately after attaching to target).
preLaunchCommands | string[] | Launch | Additional GDB Commands to be executed at the start of the main launch sequence (immediately after attaching to target).

And after the setup of my configuration I saw that commands from preAttachCommands are not even send (from preAttachCommands), and the command I want to send just after the connection are correctly send (from preLaunchCommands).

Extract from my launch json :

```json
"preAttachCommands": [
	// "set confirm off",
	"set mem inaccessible-by-default",
	"mem 0 4 ro 8 nocache"
],
"preLaunchCommands": [
	"set remote hardware-breakpoint-limit 6",
	"set remote hardware-watchpoint-limit 4",
	"monitor cortex_a smp off",
	"monitor if {[target current] == \"stm32mp15x.cpu1\"} {targets stm32mp15x.cpu0}",
]
```

Logs :

```txt
11-target-select extended-remote localhost:50011
.....
-> 11^connected
12-interpreter-exec console "set mem inaccessible-by-default"
-> 12^done
```

Do I use the wrong attributes for my purpose ? Is there a way to "enable" preAttachCommands ? How can I help there ?

**Comment by haneefdm** [comment]
There are so many ways already to do what you need. You can use the `.gdbinit` file in the current directory. Or you can pass extra command line options to gdb. Note that `attach` is a decades old term used by gdb to indicate attaching to a running program. It is not about attaching to a gdb-server

```
            "debuggerArgs": [
                "-x",
                "myscript.txt"
            ],
```

See gdb documentation (especially, section 2.1.4.4)

https://sourceware.org/gdb/current/onlinedocs/gdb.html/Initialization-Files.html#Initialization-Files
https://sourceware.org/gdb/current/onlinedocs/gdb.html/Startup.html#Startup

Please also read our wiki

https://github.com/Marus/cortex-debug/wiki/Cortex-Debug-Under-the-hood

Please close this issue if you find what you need. The current meaning of `preAttachCommands` is not going to change
