### ISSUE TITLE
VSCode version 1.28 disables cortex-debug use of gdb

### ISSUE THREAD

**Issue by myxyplyxyt** [Marus/cortex-debug#96]
cortex-debug allowed me to debug a non-trivial application on STM32F7 discovery board using VSCode on Windows, OS X, and on Ubuntu 18.04.

It worked fine on VSCode version 1.27.2, but the VSCode team changed the debugger front end for version 1.28.

I would be willing to supply the application source code which works on 1.27.2 to try on the discovery board, if you wanted to find a work-around for the new front end on 1.28.

**Comment by jonsole** [comment]
I have the same issue after upgrading to 1.28.  When debugging is started the debugger seems to get stuck with no VARIABLES shown in the sidebar and just Pause,Restart and Stop commands available.

As a workaround, opening the debug console and pressing return seems to wake up the debugger.

**Comment by myxyplyxyt** [comment]
Thanks Jon,

     I tried a view things, but never considered just hitting return.

**Comment by myxyplyxyt** [comment]
Workaround works just fine

**Comment by 0ge** [comment]
I think this is a regression and that the issue should be reopened.
