### ISSUE TITLE
blank output in the RTT terminal

### ISSUE THREAD

**Issue by Hermann-Core** [Marus/cortex-debug#962]
**Describe the bug**
**To Reproduce**
1. Start debug session
2. open the RTT Terminal

**Expected behavior**

I will like to see the RTT prints in the RTT Terminal. For some strange reasons, I'm unable to get the RTT prints in my Terminal. It was working before with the same setup. I use the JLink Firmware in my STM32F3Discovery board.

**Screenshots**

![image](https://github.com/Marus/cortex-debug/assets/65020150/a401fbf0-b37b-4bbc-a35c-54cd2f64b30d)

**Environment (please complete the following information):**

 - Cortex-Debug Version : 1.12.1
 - OS: Windows 11 22H2
 - GDB Version: 12.2.1
 - Compiler Toolchain Version: ti-arm-eabi V 15.0.7

**Please include `launch.json`**

*Note: We are unlikely to look at the issue if you do not supply this*
```
{
        "name": "JLink Debug",
        "request": "launch",
        "type": "cortex-debug",
        "cwd": "${workspaceFolder}",
        "executable": "${workspaceFolder}/bin/debug/bootloader.out",
        "loadFiles": [
          "${workspaceFolder}/bin/debug/bootloader.hex",
          "${workspaceFolder}/bin/debug/application.hex"
        ],
        "symbolFiles": [
          {"file": "${workspaceFolder}/bin/debug/bootloader.out"},
          {"file": "${workspaceFolder}/bin/debug/application.out"}
        ],
        "servertype": "jlink",
        "serverpath": "${env:ProgramFiles}/SEGGER/JLink/JLinkGDBServerCL.exe",
        "runToEntryPoint": "main",
        "device": "STM32F303VC",
        "showDevDebugOutput": "raw",
        "rttConfig": {
          "enabled": true,
          "address": "auto",
          "decoders": [
              {
                  "label": "",
                  "port": 0,
                  "type": "console",
                  "iencoding": "utf8",
              }
          ]
        },
        "preLaunchTask": "CMake: build",
        "svdPath": "${workspaceFolder}/device/config/SVD_file/STM32F303.svd"
      },
```

**Attach text from `Debug Console`**

Please enable debug output in your launch.json (`"showDevDebugOutput": "raw"`). It this is too large, please attach it as a file

![image](https://github.com/Marus/cortex-debug/assets/65020150/3343a778-2ae3-4b8a-b44a-b7a20ccb3dcf)

**Additional context**

**Comment by haneefdm** [comment]
Screenshots are nice, but need the full text from the Debug Console and the Terminal(gdb-server). We an see that JLink started successfully and even printed its header. We are simply waiting for JLInk to give us something to print. It is not clear to me JLINK found your control block. Make sure that is happening by looking at the address where the control block should be.

**Comment by Hermann-Core** [comment]
> Screenshots are nice, but need the full text from the Debug Console and the Terminal(gdb-server). We an see that JLink started successfully and even printed its header. We are simply waiting for JLInk to give us something to print. It is not clear to me JLINK found your control block. Make sure that is happening by looking at the address where the control block should be.

It suddenly begin the work. I saimply restarted Vs Code. Dont really know what happened
