### ISSUE TITLE
Starts openocd on port 50000 but timeouts 

### ISSUE THREAD

**Issue by giellamo** [Marus/cortex-debug#97]
I haven't been able to se arm-none-eabi-gdb to be called.

    {
    "version": "0.2.0",

    "configurations": [

        {
            "type": "cortex-debug",

            "request": "attach",

            "servertype": "openocd",

            "cwd": "${workspaceRoot}",

            "executable": "./build/vsa2-control.elf",

            "name": "Debug (OpenOCD)",

            "configFiles": [
                "./stm32f4discovery.cfg"
            ]

        }
    ]
    }

and on settings:

    "cortex-debug.armToolchainPath":"/home/giellamo/projects/tools/gcc-arm-none-eabi/",

    "cortex-debug.openocdPath": "/usr/bin/openocd"

I've tried both
"cortex-debug.armToolchainPath" : "/home/giellamo/projects/tools/gcc-arm-none-eabi/"
and 
"cortex-debug.armToolchainPath": "/home/giellamo/projects/tools/gcc-arm-none-eabi/bin"

**Comment by Marus** [comment]
Sorry - I've been unable to keep up with this project for the last number of months and am only been able to get back to this now. Are you still trying to use the tools and running into this issue?

From the information you posed I would have expected that 
"cortex-debug.armToolchainPath": "/home/giellamo/projects/tools/gcc-arm-none-eabi/bin"
in your settings should allow it to find the GDB (assuming it is actually in that directory, but you do need to include the "bin" part).

Did you get anything in "Adapter Output" in the Output tab (should be in the drop-down selector)?
