### ISSUE TITLE
Issues with JTAG and RISC-V target

### ISSUE THREAD

**Issue by romancardenas** [Marus/cortex-debug#972]
**Describe the bug**

I'm currently working with a [SparkFun RED-V Thing Plus](https://www.sparkfun.com/products/15799). To flash/debug, I'm using the JLINK server and the JTAG interface.

When launching the debug session, cortex-debug manages to flash the binary, but it never halts on main, and the board eventually gets ejected from my computer.

**Expected behavior**

I expected cortex-debug to halt on the first line of my `main` function and wait for further commands.

**Environment**

 - Cortex-Debug Version (this extension) v1.12.1
 - OS: MacOS 14.1.2
 - GDB Version: 12.1
 - Compiler Toolchain Version: rustc 1.75.0 for riscv32imc-unknown-none-elf targets

**`launch.json`**

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Debug example (JLINK)",
            "type": "cortex-debug",
            "preLaunchTask": "cortex-debug: build example",
            "device": "FE310", 
            "request": "launch",
            "servertype": "jlink",
            "cwd": "${workspaceRoot}",
            "executable": "${workspaceRoot}/target/riscv32imc-unknown-none-elf/debug/examples/${input:example}",
            "interface": "jtag",
            "svdFile": "${workspaceRoot}/hifive.svd",
            "gdbPath": "riscv64-unknown-elf-gdb",
            "toolchainPrefix": "riscv64-unknown-elf",
            "runToEntryPoint": "main",
            "showDevDebugOutput": "raw" 
        },
    ],
    "inputs": [
		{
            "id": "example",
            "type": "command",
            "command": "extension.commandvariable.pickStringRemember",
            "args": {
                "key": "example",
                "description": "Select example:",
                "default": "wait_poll",
                "options": [
                    "wait_poll",
                    "wait_interrupt",
                    "full",
                    "rgb_gpio",
                    "button",
                ]
            }
		},
    ]
}
```

**`Debug Console`**

```
-> 9^done
10-file-exec-and-symbols "/Users/rcardenas/embedded-rust/riscv-xdevs/target/riscv32imc-unknown-none-elf/debug/examples/wait_poll"
-> 10^done
11-target-select extended-remote localhost:50000
-> =thread-group-started,id="i1",pid="42000"
-> =thread-created,id="1",group-id="i1"
-> ~"wait_poll::__risc_v_rt__main () at examples/wait_poll.rs:58\n"
wait_poll::__risc_v_rt__main () at examples/wait_poll.rs:58
-> ~"58\t    loop {}\n"
58	    loop {}
-> *stopped,frame={addr="0x20010ee8",func="wait_poll::__risc_v_rt__main",args=[],file="examples/wait_poll.rs",fullname="/Users/rcardenas/embedded-rust/riscv-xdevs/examples/wait_poll.rs",line="58",arch="riscv:rv32"},thread-id="1",stopped-threads="all"
mi2.status = stopped
Program stopped, probably due to a reset and/or halt issued by debugger
-> 11^connected
12-interpreter-exec console "monitor halt"
-> 12^done
13-interpreter-exec console "monitor reset"
-> @"Resetting target\r\n"
Resetting target
-> 13^done
14-target-download
-> 14+download,{section=".text",section-size="51672",total-size="1292656"}
-> 14+download,{section=".text",section-sent="15712",section-size="51672",total-sent="15712",total-size="1292656"}
-> 14+download,{section=".rodata",section-size="9848",total-size="1292656"}
-> 14^done,address="0x20010000",load-size="61520",transferred-bits="492160",write-rate="12304"
15-interpreter-exec console "monitor reset"
-> @"Resetting target\r\n"
Resetting target
-> 15^done
Returning dummy thread-id to workaround VSCode issue with pause button not working
Returning dummy stack frame to workaround VSCode issue with pause button not working: {"threadId":1,"startFrame":0,"levels":20}
16-break-insert -t --function main
-> 16^done,bkpt={number="1",type="breakpoint",disp="del",enabled="y",addr="0x20010d1e",func="wait_poll::__risc_v_rt__main",file="examples/wait_poll.rs",fullname="/Users/rcardenas/embedded-rust/riscv-xdevs/examples/wait_poll.rs",line="35",thread-groups=["i1"],times="0",original-location="-function main"}
17-exec-continue --all
-> 17^running
-> *running,thread-id="all"
mi2.status = running
```

**Comment by haneefdm** [comment]
As you can see from the debug output, we did everything (no errors) and are just waiting on gdb to do its thing. We cannot make any magic happen. It is up to gdb and your Jlink configuration.

Maybe you have a bug in your startup code and your program never gets to main. **Please make sure you can do everything from the command line.**

Perhaps your chip vendor did not implement the reset properly. A reset should start from the beginning and stop at the first instruction.

**Comment by romancardenas** [comment]
Thanks for your reply! I already suspected that the issue was not cortex-debug, but I hope you can help me (or at least point me where to ask). I face similar issues on terminal. I've been reading the traces of JLinkGDBServer and noticed a couple of weird things to me:

It first connects to my board successfully and prints the value of the registers. So far so good.

It eventually receives a `halt`() command and seems to work:
```
Received monitor command: halt
Halting target CPU...
...Target halted (PC = 0x20010F70)
```

Next, it receives a `reset` command and also looks OK:
```
Received monitor command: reset
Resetting target
Downloading 15712 bytes @ address 0x20010000
Downloading 15616 bytes @ address 0x20013D60
Downloading 16032 bytes @ address 0x20017A60
Downloading 4758 bytes @ address 0x2001B900
Downloading 9880 bytes @ address 0x2001CBA0
Writing register 'pc' = 0x20010000
Comparing flash   [....................] Done.
```

Important stuff: The flash starts at 0x20000000, but the first lines are reserved for the JLink debugger. That is why my binary starts at 0x20010000- In fact, the `_start` symbol of my binary is at that address. It looks like the PC is correctly set after this reset.

Next, it re-resets the target again (I don't know why) and puts a break point at 0x20010D7E:
```
Read 2 bytes @ address 0x20010D7E (Data = 0xC2AA)
Setting breakpoint @ address 0x20010D7E, Kind = 2, Type = THUMB, BPHandle = 0x0001
```

This address is one of the first lines of my `main`:

```asm
20010d72 <main>:
20010d72: 13 01 01 bb  	addi	sp, sp, -1104
20010d76: 23 26 11 44  	sw	ra, 1100(sp)
20010d7a: 37 05 f0 3f  	lui	a0, 261888
20010d7e: aa c2        	sw	a0, 68(sp) // <-- here
20010d80: aa d6        	sw	a0, 108(sp)
20010d82: 01 45        	li	a0, 0
20010d84: aa ca        	sw	a0, 84(sp)

...
```

Then, the `17-exec-continue --all` instruction from cortex-debug makes the program start. I can verify that my board starts executing main without stopping at all (a bunch of LEDs blink according to my app). Once the app is done, this happens in cortex-debug console:
```

Program
-> ~" received signal SIGTRAP, Trace/breakpoint trap.\n"
 received signal SIGTRAP, Trace/breakpoint trap.
-> ~"0xdeadbeef in ?? ()\n"
0xdeadbeef in ?? ()
-> *stopped,reason="signal-received",signal-name="SIGTRAP",signal-meaning="Trace/breakpoint trap",frame={addr="0xdeadbeef",func="??",args=[],arch="riscv:rv32"},thread-id="1",stopped-threads="all"
```

This is exactly when my board gets ejected from my computer and everything hangs.

So it seems that the break point at main does not trigger. However, the program ran well, so it must have passed that point.

Any ideas?

**Comment by romancardenas** [comment]
Is it normal that the breakpoint is not at `0x20010d72`, but at `0x20010d7e`? I tried to put the breakpoint at another symbol and it also shows this strange offset

**Comment by haneefdm** [comment]
> Is it normal that the breakpoint is not at `0x20010d72`, but at `0x20010d7e`? I tried to put the breakpoint at another symbol and it also shows this strange offset

We rarely deal with addresses. It is all symbolic and we let gdb deal with it. It is also up to your linker on how addresses are translated.

> Then, the 17-exec-continue --all instruction from cortex-debug makes the program start

Minor correction. No, it does not make your program start. It makes it continue from wherever it is currently paused.

Please close this issue if we cannot identify an actual defect. We try to keep our list short

**Comment by haneefdm** [comment]
If it works with another debugger/IDE, please look at all the gdb commands that are being sent and try to duplicate them. Our extension is super customizable.

Hope that helps
